local var_0_0 = require("protobuf")

module("affix_hrl_pb", package.seeall)

local var_0_1 = {
	AFFIX_NET_REC_FIELD_LIST = {}
}

AFFIX_NET_REC = var_0_0.Descriptor()
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD = var_0_0.FieldDescriptor()
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD = var_0_0.FieldDescriptor()
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.name = "id"
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.full_name = ".common.affix_net_rec.id"
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.number = 1
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.index = 0
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.label = 2
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.has_default_value = false
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.default_value = 0
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.type = 13
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD.cpp_type = 3
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.name = "level"
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.full_name = ".common.affix_net_rec.level"
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.number = 2
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.index = 1
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.label = 2
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.has_default_value = false
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.default_value = 0
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.type = 13
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD.cpp_type = 3
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.name = "type"
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.full_name = ".common.affix_net_rec.type"
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.number = 3
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.index = 2
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.label = 2
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.has_default_value = false
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.default_value = 0
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.type = 13
var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD.cpp_type = 3
AFFIX_NET_REC.name = "affix_net_rec"
AFFIX_NET_REC.full_name = ".common.affix_net_rec"
AFFIX_NET_REC.nested_types = {}
AFFIX_NET_REC.enum_types = {}
AFFIX_NET_REC.fields = {
	var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_ID_FIELD,
	var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_LEVEL_FIELD,
	var_0_1.AFFIX_NET_REC_FIELD_LIST.AFFIX_NET_REC_TYPE_FIELD
}
AFFIX_NET_REC.is_extendable = false
AFFIX_NET_REC.extensions = {}
affix_net_rec = var_0_0.Message(AFFIX_NET_REC)

return affix_hrl_pb
