slot0 = require("protobuf")

module("ban_hrl_pb", package.seeall)

slot1 = {
	BANNED_I18N_NET_REC_FIELD_LIST = {}
}
BANNED_I18N_NET_REC = slot0.Descriptor()
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD = slot0.FieldDescriptor()
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD = slot0.FieldDescriptor()
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD = slot0.FieldDescriptor()
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.name = "type"
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.full_name = ".common.banned_i18n_net_rec.type"
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.number = 1
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.index = 0
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.label = 2
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.has_default_value = false
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.default_value = 0
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.type = 13
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.cpp_type = 3
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.name = "language"
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.full_name = ".common.banned_i18n_net_rec.language"
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.number = 2
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.index = 1
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.label = 2
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.has_default_value = false
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.default_value = ""
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.type = 9
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.cpp_type = 9
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.name = "string"
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.full_name = ".common.banned_i18n_net_rec.string"
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.number = 3
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.index = 2
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.label = 1
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.has_default_value = false
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.default_value = ""
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.type = 9
slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.cpp_type = 9
BANNED_I18N_NET_REC.name = "banned_i18n_net_rec"
BANNED_I18N_NET_REC.full_name = ".common.banned_i18n_net_rec"
BANNED_I18N_NET_REC.nested_types = {}
BANNED_I18N_NET_REC.enum_types = {}
BANNED_I18N_NET_REC.fields = {
	slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD,
	slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD,
	slot1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD
}
BANNED_I18N_NET_REC.is_extendable = false
BANNED_I18N_NET_REC.extensions = {}
banned_i18n_net_rec = slot0.Message(BANNED_I18N_NET_REC)

return ban_hrl_pb
