local var_0_0 = require("protobuf")

module("ban_hrl_pb", package.seeall)

local var_0_1 = {
	BANNED_I18N_NET_REC_FIELD_LIST = {}
}

BANNED_I18N_NET_REC = var_0_0.Descriptor()
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD = var_0_0.FieldDescriptor()
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD = var_0_0.FieldDescriptor()
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD = var_0_0.FieldDescriptor()
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.name = "type"
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.full_name = ".common.banned_i18n_net_rec.type"
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.number = 1
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.index = 0
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.label = 2
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.has_default_value = false
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.default_value = 0
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.type = 13
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD.cpp_type = 3
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.name = "language"
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.full_name = ".common.banned_i18n_net_rec.language"
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.number = 2
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.index = 1
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.label = 2
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.has_default_value = false
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.default_value = ""
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.type = 9
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD.cpp_type = 9
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.name = "string"
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.full_name = ".common.banned_i18n_net_rec.string"
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.number = 3
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.index = 2
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.label = 1
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.has_default_value = false
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.default_value = ""
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.type = 9
var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD.cpp_type = 9
BANNED_I18N_NET_REC.name = "banned_i18n_net_rec"
BANNED_I18N_NET_REC.full_name = ".common.banned_i18n_net_rec"
BANNED_I18N_NET_REC.nested_types = {}
BANNED_I18N_NET_REC.enum_types = {}
BANNED_I18N_NET_REC.fields = {
	var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_TYPE_FIELD,
	var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_LANGUAGE_FIELD,
	var_0_1.BANNED_I18N_NET_REC_FIELD_LIST.BANNED_I18N_NET_REC_STRING_FIELD
}
BANNED_I18N_NET_REC.is_extendable = false
BANNED_I18N_NET_REC.extensions = {}
banned_i18n_net_rec = var_0_0.Message(BANNED_I18N_NET_REC)

return ban_hrl_pb
