local var_0_0 = require("protobuf")

module("item_hrl_pb", package.seeall)

local var_0_1 = {
	ITEM_NET_REC_FIELD_LIST = {},
	CONVER_ITEM_REC_FIELD_LIST = {},
	MATERIAL_NET_REC_FIELD_LIST = {},
	OVERDUE_NOTIFICATION_FIELD_LIST = {}
}

ITEM_NET_REC = var_0_0.Descriptor()
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD = var_0_0.FieldDescriptor()
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD = var_0_0.FieldDescriptor()
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD = var_0_0.FieldDescriptor()
CONVER_ITEM_REC = var_0_0.Descriptor()
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD = var_0_0.FieldDescriptor()
MATERIAL_NET_REC = var_0_0.Descriptor()
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD = var_0_0.FieldDescriptor()
OVERDUE_NOTIFICATION = var_0_0.Descriptor()
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD = var_0_0.FieldDescriptor()
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD = var_0_0.FieldDescriptor()
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.name = "id"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.full_name = ".common.item_net_rec.id"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.number = 1
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.index = 0
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.label = 2
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.has_default_value = false
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.default_value = 0
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.type = 13
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.cpp_type = 3
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.name = "num"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.full_name = ".common.item_net_rec.num"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.number = 2
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.index = 1
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.label = 2
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.has_default_value = false
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.default_value = 0
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.type = 5
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.cpp_type = 1
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.name = "time_valid"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.full_name = ".common.item_net_rec.time_valid"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.number = 3
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.index = 2
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.label = 1
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.has_default_value = false
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.default_value = 0
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.type = 13
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.cpp_type = 3
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.name = "convert_from"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.full_name = ".common.item_net_rec.convert_from"
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.number = 4
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.index = 3
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.label = 1
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.has_default_value = false
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.default_value = nil
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.message_type = CONVER_ITEM_REC
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.type = 11
var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.cpp_type = 10
ITEM_NET_REC.name = "item_net_rec"
ITEM_NET_REC.full_name = ".common.item_net_rec"
ITEM_NET_REC.nested_types = {}
ITEM_NET_REC.enum_types = {}
ITEM_NET_REC.fields = {
	var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD,
	var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD,
	var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD,
	var_0_1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD
}
ITEM_NET_REC.is_extendable = false
ITEM_NET_REC.extensions = {}
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.name = "id"
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.full_name = ".common.conver_item_rec.id"
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.number = 1
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.index = 0
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.label = 2
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.has_default_value = false
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.default_value = 0
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.type = 13
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.cpp_type = 3
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.name = "num"
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.full_name = ".common.conver_item_rec.num"
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.number = 2
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.index = 1
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.label = 2
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.has_default_value = false
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.default_value = 0
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.type = 5
var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.cpp_type = 1
CONVER_ITEM_REC.name = "conver_item_rec"
CONVER_ITEM_REC.full_name = ".common.conver_item_rec"
CONVER_ITEM_REC.nested_types = {}
CONVER_ITEM_REC.enum_types = {}
CONVER_ITEM_REC.fields = {
	var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD,
	var_0_1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD
}
CONVER_ITEM_REC.is_extendable = false
CONVER_ITEM_REC.extensions = {}
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.name = "id"
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.full_name = ".common.material_net_rec.id"
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.number = 1
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.index = 0
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.label = 2
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.has_default_value = false
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.default_value = 0
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.type = 13
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.cpp_type = 3
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.name = "num"
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.full_name = ".common.material_net_rec.num"
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.number = 2
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.index = 1
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.label = 2
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.has_default_value = false
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.default_value = 0
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.type = 13
var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.cpp_type = 3
MATERIAL_NET_REC.name = "material_net_rec"
MATERIAL_NET_REC.full_name = ".common.material_net_rec"
MATERIAL_NET_REC.nested_types = {}
MATERIAL_NET_REC.enum_types = {}
MATERIAL_NET_REC.fields = {
	var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD,
	var_0_1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD
}
MATERIAL_NET_REC.is_extendable = false
MATERIAL_NET_REC.extensions = {}
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.name = "id"
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.full_name = ".common.overdue_notification.id"
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.number = 1
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.index = 0
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.label = 2
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.has_default_value = false
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.default_value = 0
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.type = 13
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.cpp_type = 3
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.name = "num"
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.full_name = ".common.overdue_notification.num"
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.number = 2
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.index = 1
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.label = 2
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.has_default_value = false
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.default_value = 0
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.type = 13
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.cpp_type = 3
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.name = "time_valid"
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.full_name = ".common.overdue_notification.time_valid"
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.number = 3
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.index = 2
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.label = 2
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.has_default_value = false
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.default_value = 0
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.type = 13
var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.cpp_type = 3
OVERDUE_NOTIFICATION.name = "overdue_notification"
OVERDUE_NOTIFICATION.full_name = ".common.overdue_notification"
OVERDUE_NOTIFICATION.nested_types = {}
OVERDUE_NOTIFICATION.enum_types = {}
OVERDUE_NOTIFICATION.fields = {
	var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD,
	var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD,
	var_0_1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD
}
OVERDUE_NOTIFICATION.is_extendable = false
OVERDUE_NOTIFICATION.extensions = {}
conver_item_rec = var_0_0.Message(CONVER_ITEM_REC)
item_net_rec = var_0_0.Message(ITEM_NET_REC)
material_net_rec = var_0_0.Message(MATERIAL_NET_REC)
overdue_notification = var_0_0.Message(OVERDUE_NOTIFICATION)

return item_hrl_pb
