slot0 = require("protobuf")

module("p38_pb", package.seeall)

slot1 = {
	CS_38014_FIELD_LIST = {},
	LOG_NET_REC_FIELD_LIST = {}
}
CS_38014 = slot0.Descriptor()
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD = slot0.FieldDescriptor()
LOG_NET_REC = slot0.Descriptor()
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD = slot0.FieldDescriptor()
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD = slot0.FieldDescriptor()
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.name = "log_list"
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.full_name = ".p38.cs_38014.log_list"
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.number = 1
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.index = 0
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.label = 3
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.has_default_value = false
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.default_value = {}
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.message_type = LOG_NET_REC
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.type = 11
slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.cpp_type = 10
CS_38014.name = "cs_38014"
CS_38014.full_name = ".p38.cs_38014"
CS_38014.nested_types = {}
CS_38014.enum_types = {}
CS_38014.fields = {
	slot1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD
}
CS_38014.is_extendable = false
CS_38014.extensions = {}
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.name = "event_name"
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.full_name = ".p38.log_net_rec.event_name"
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.number = 1
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.index = 0
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.label = 2
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.has_default_value = false
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.default_value = ""
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.type = 9
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.cpp_type = 9
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.name = "attribute_json"
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.full_name = ".p38.log_net_rec.attribute_json"
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.number = 2
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.index = 1
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.label = 2
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.has_default_value = false
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.default_value = ""
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.type = 9
slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.cpp_type = 9
LOG_NET_REC.name = "log_net_rec"
LOG_NET_REC.full_name = ".p38.log_net_rec"
LOG_NET_REC.nested_types = {}
LOG_NET_REC.enum_types = {}
LOG_NET_REC.fields = {
	slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD,
	slot1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD
}
LOG_NET_REC.is_extendable = false
LOG_NET_REC.extensions = {}
cs_38014 = slot0.Message(CS_38014)
log_net_rec = slot0.Message(LOG_NET_REC)

return p38_pb
