local var_0_0 = require("protobuf")

module("p38_pb", package.seeall)

local var_0_1 = {
	CS_38014_FIELD_LIST = {},
	LOG_NET_REC_FIELD_LIST = {}
}

CS_38014 = var_0_0.Descriptor()
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD = var_0_0.FieldDescriptor()
LOG_NET_REC = var_0_0.Descriptor()
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD = var_0_0.FieldDescriptor()
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD = var_0_0.FieldDescriptor()
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.name = "log_list"
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.full_name = ".p38.cs_38014.log_list"
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.number = 1
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.index = 0
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.label = 3
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.has_default_value = false
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.default_value = {}
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.message_type = LOG_NET_REC
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.type = 11
var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD.cpp_type = 10
CS_38014.name = "cs_38014"
CS_38014.full_name = ".p38.cs_38014"
CS_38014.nested_types = {}
CS_38014.enum_types = {}
CS_38014.fields = {
	var_0_1.CS_38014_FIELD_LIST.CS_38014_LOG_LIST_FIELD
}
CS_38014.is_extendable = false
CS_38014.extensions = {}
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.name = "event_name"
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.full_name = ".p38.log_net_rec.event_name"
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.number = 1
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.index = 0
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.label = 2
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.has_default_value = false
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.default_value = ""
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.type = 9
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD.cpp_type = 9
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.name = "attribute_json"
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.full_name = ".p38.log_net_rec.attribute_json"
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.number = 2
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.index = 1
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.label = 2
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.has_default_value = false
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.default_value = ""
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.type = 9
var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD.cpp_type = 9
LOG_NET_REC.name = "log_net_rec"
LOG_NET_REC.full_name = ".p38.log_net_rec"
LOG_NET_REC.nested_types = {}
LOG_NET_REC.enum_types = {}
LOG_NET_REC.fields = {
	var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_EVENT_NAME_FIELD,
	var_0_1.LOG_NET_REC_FIELD_LIST.LOG_NET_REC_ATTRIBUTE_JSON_FIELD
}
LOG_NET_REC.is_extendable = false
LOG_NET_REC.extensions = {}
cs_38014 = var_0_0.Message(CS_38014)
log_net_rec = var_0_0.Message(LOG_NET_REC)

return p38_pb
