slot0 = require("protobuf")

module("p41_pb", package.seeall)

slot1 = {
	SC_41001_FIELD_LIST = {},
	TOWER_INFO_FIELD_LIST = {}
}
SC_41001 = slot0.Descriptor()
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD = slot0.FieldDescriptor()
TOWER_INFO = slot0.Descriptor()
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD = slot0.FieldDescriptor()
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD = slot0.FieldDescriptor()
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.name = "info_list"
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.full_name = ".p41.sc_41001.info_list"
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.number = 1
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.index = 0
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.label = 3
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.has_default_value = false
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.default_value = {}
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.message_type = TOWER_INFO
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.type = 11
slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD.cpp_type = 10
SC_41001.name = "sc_41001"
SC_41001.full_name = ".p41.sc_41001"
SC_41001.nested_types = {}
SC_41001.enum_types = {}
SC_41001.fields = {
	slot1.SC_41001_FIELD_LIST.SC_41001_INFO_LIST_FIELD
}
SC_41001.is_extendable = false
SC_41001.extensions = {}
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.name = "area"
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.full_name = ".p41.tower_info.area"
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.number = 1
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.index = 0
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.label = 2
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.has_default_value = false
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.default_value = 0
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.type = 13
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD.cpp_type = 3
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.name = "stage"
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.full_name = ".p41.tower_info.stage"
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.number = 2
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.index = 1
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.label = 2
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.has_default_value = false
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.default_value = 0
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.type = 13
slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD.cpp_type = 3
TOWER_INFO.name = "tower_info"
TOWER_INFO.full_name = ".p41.tower_info"
TOWER_INFO.nested_types = {}
TOWER_INFO.enum_types = {}
TOWER_INFO.fields = {
	slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_AREA_FIELD,
	slot1.TOWER_INFO_FIELD_LIST.TOWER_INFO_STAGE_FIELD
}
TOWER_INFO.is_extendable = false
TOWER_INFO.extensions = {}
sc_41001 = slot0.Message(SC_41001)
tower_info = slot0.Message(TOWER_INFO)

return p41_pb
