slot0 = require("protobuf")

module("p51_pb", package.seeall)

slot1 = {
	SC_51001_FIELD_LIST = {},
	HISTORY_DATA_NET_REC_FIELD_LIST = {}
}
SC_51001 = slot0.Descriptor()
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD = slot0.FieldDescriptor()
HISTORY_DATA_NET_REC = slot0.Descriptor()
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD = slot0.FieldDescriptor()
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD = slot0.FieldDescriptor()
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.name = "data_list"
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.full_name = ".p51.sc_51001.data_list"
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.number = 1
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.index = 0
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.label = 3
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.has_default_value = false
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.default_value = {}
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.message_type = HISTORY_DATA_NET_REC
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.type = 11
slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD.cpp_type = 10
SC_51001.name = "sc_51001"
SC_51001.full_name = ".p51.sc_51001"
SC_51001.nested_types = {}
SC_51001.enum_types = {}
SC_51001.fields = {
	slot1.SC_51001_FIELD_LIST.SC_51001_DATA_LIST_FIELD
}
SC_51001.is_extendable = false
SC_51001.extensions = {}
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.name = "id"
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.full_name = ".p51.history_data_net_rec.id"
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.number = 1
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.index = 0
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.label = 2
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.has_default_value = false
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.default_value = 0
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.type = 13
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD.cpp_type = 3
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.name = "data"
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.full_name = ".p51.history_data_net_rec.data"
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.number = 2
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.index = 1
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.label = 2
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.has_default_value = false
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.default_value = "0"
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.type = 4
slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD.cpp_type = 4
HISTORY_DATA_NET_REC.name = "history_data_net_rec"
HISTORY_DATA_NET_REC.full_name = ".p51.history_data_net_rec"
HISTORY_DATA_NET_REC.nested_types = {}
HISTORY_DATA_NET_REC.enum_types = {}
HISTORY_DATA_NET_REC.fields = {
	slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_ID_FIELD,
	slot1.HISTORY_DATA_NET_REC_FIELD_LIST.HISTORY_DATA_NET_REC_DATA_FIELD
}
HISTORY_DATA_NET_REC.is_extendable = false
HISTORY_DATA_NET_REC.extensions = {}
history_data_net_rec = slot0.Message(HISTORY_DATA_NET_REC)
sc_51001 = slot0.Message(SC_51001)

return p51_pb
