local var_0_0 = require("protobuf")

module("team_hrl_pb", package.seeall)

local var_0_1 = {
	MIMIR_NET_REC_FIELD_LIST = {},
	HERO_INFO_NET_REC_FIELD_LIST = {},
	HERO_NET_REC_FIELD_LIST = {},
	EQUIP_NET_REC_FIELD_LIST = {},
	ASTROLABE_NET_REC_FIELD_LIST = {}
}

MIMIR_NET_REC = var_0_0.Descriptor()
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD = var_0_0.FieldDescriptor()
HERO_INFO_NET_REC = var_0_0.Descriptor()
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD = var_0_0.FieldDescriptor()
HERO_NET_REC = var_0_0.Descriptor()
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD = var_0_0.FieldDescriptor()
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD = var_0_0.FieldDescriptor()
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD = var_0_0.FieldDescriptor()
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD = var_0_0.FieldDescriptor()
EQUIP_NET_REC = var_0_0.Descriptor()
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD = var_0_0.FieldDescriptor()
ASTROLABE_NET_REC = var_0_0.Descriptor()
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD = var_0_0.FieldDescriptor()
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD = var_0_0.FieldDescriptor()
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.name = "mimir_id"
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.full_name = ".common.mimir_net_rec.mimir_id"
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.number = 1
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.index = 0
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.label = 2
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.has_default_value = false
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.default_value = 0
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.type = 13
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD.cpp_type = 3
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.name = "chip_list"
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.full_name = ".common.mimir_net_rec.chip_list"
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.number = 2
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.index = 1
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.label = 3
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.has_default_value = false
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.default_value = {}
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.type = 13
var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD.cpp_type = 3
MIMIR_NET_REC.name = "mimir_net_rec"
MIMIR_NET_REC.full_name = ".common.mimir_net_rec"
MIMIR_NET_REC.nested_types = {}
MIMIR_NET_REC.enum_types = {}
MIMIR_NET_REC.fields = {
	var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_MIMIR_ID_FIELD,
	var_0_1.MIMIR_NET_REC_FIELD_LIST.MIMIR_NET_REC_CHIP_LIST_FIELD
}
MIMIR_NET_REC.is_extendable = false
MIMIR_NET_REC.extensions = {}
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.name = "hero_id"
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.full_name = ".common.hero_info_net_rec.hero_id"
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.number = 1
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.index = 0
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.label = 2
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.has_default_value = false
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.default_value = 0
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.type = 13
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD.cpp_type = 3
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.name = "owner_id"
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.full_name = ".common.hero_info_net_rec.owner_id"
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.number = 2
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.index = 1
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.label = 1
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.has_default_value = false
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.default_value = "0"
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.type = 4
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD.cpp_type = 4
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.name = "hero_type"
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.full_name = ".common.hero_info_net_rec.hero_type"
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.number = 3
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.index = 2
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.label = 2
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.has_default_value = false
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.default_value = 0
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.type = 13
var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD.cpp_type = 3
HERO_INFO_NET_REC.name = "hero_info_net_rec"
HERO_INFO_NET_REC.full_name = ".common.hero_info_net_rec"
HERO_INFO_NET_REC.nested_types = {}
HERO_INFO_NET_REC.enum_types = {}
HERO_INFO_NET_REC.fields = {
	var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_ID_FIELD,
	var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_OWNER_ID_FIELD,
	var_0_1.HERO_INFO_NET_REC_FIELD_LIST.HERO_INFO_NET_REC_HERO_TYPE_FIELD
}
HERO_INFO_NET_REC.is_extendable = false
HERO_INFO_NET_REC.extensions = {}
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.name = "hero_id"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.full_name = ".common.hero_net_rec.hero_id"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.number = 1
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.index = 0
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.label = 2
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.has_default_value = false
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.default_value = 0
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.type = 13
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD.cpp_type = 3
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.name = "star"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.full_name = ".common.hero_net_rec.star"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.number = 2
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.index = 1
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.label = 2
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.has_default_value = false
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.default_value = 0
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.type = 13
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD.cpp_type = 3
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.name = "exp"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.full_name = ".common.hero_net_rec.exp"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.number = 3
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.index = 2
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.label = 2
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.has_default_value = false
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.default_value = 0
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.type = 13
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD.cpp_type = 3
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.name = "equip_list"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.full_name = ".common.hero_net_rec.equip_list"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.number = 4
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.index = 3
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.label = 3
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.has_default_value = false
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.default_value = {}
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.message_type = EQUIP_NET_REC
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.type = 11
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD.cpp_type = 10
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.name = "astrolabe_list"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.full_name = ".common.hero_net_rec.astrolabe_list"
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.number = 5
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.index = 4
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.label = 3
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.has_default_value = false
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.default_value = {}
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.message_type = ASTROLABE_NET_REC
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.type = 11
var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD.cpp_type = 10
HERO_NET_REC.name = "hero_net_rec"
HERO_NET_REC.full_name = ".common.hero_net_rec"
HERO_NET_REC.nested_types = {}
HERO_NET_REC.enum_types = {}
HERO_NET_REC.fields = {
	var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_HERO_ID_FIELD,
	var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_STAR_FIELD,
	var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EXP_FIELD,
	var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_EQUIP_LIST_FIELD,
	var_0_1.HERO_NET_REC_FIELD_LIST.HERO_NET_REC_ASTROLABE_LIST_FIELD
}
HERO_NET_REC.is_extendable = false
HERO_NET_REC.extensions = {}
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.name = "equip_id"
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.full_name = ".common.equip_net_rec.equip_id"
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.number = 1
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.index = 0
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.label = 2
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.has_default_value = false
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.default_value = 0
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.type = 13
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD.cpp_type = 3
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.name = "prefab_id"
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.full_name = ".common.equip_net_rec.prefab_id"
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.number = 2
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.index = 1
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.label = 2
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.has_default_value = false
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.default_value = 0
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.type = 13
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD.cpp_type = 3
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.name = "exp"
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.full_name = ".common.equip_net_rec.exp"
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.number = 3
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.index = 2
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.label = 2
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.has_default_value = false
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.default_value = 0
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.type = 13
var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD.cpp_type = 3
EQUIP_NET_REC.name = "equip_net_rec"
EQUIP_NET_REC.full_name = ".common.equip_net_rec"
EQUIP_NET_REC.nested_types = {}
EQUIP_NET_REC.enum_types = {}
EQUIP_NET_REC.fields = {
	var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EQUIP_ID_FIELD,
	var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_PREFAB_ID_FIELD,
	var_0_1.EQUIP_NET_REC_FIELD_LIST.EQUIP_NET_REC_EXP_FIELD
}
EQUIP_NET_REC.is_extendable = false
EQUIP_NET_REC.extensions = {}
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.name = "astrolabe_id"
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.full_name = ".common.astrolabe_net_rec.astrolabe_id"
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.number = 1
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.index = 0
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.label = 2
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.has_default_value = false
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.default_value = 0
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.type = 13
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD.cpp_type = 3
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.name = "pos"
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.full_name = ".common.astrolabe_net_rec.pos"
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.number = 2
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.index = 1
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.label = 2
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.has_default_value = false
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.default_value = 0
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.type = 13
var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD.cpp_type = 3
ASTROLABE_NET_REC.name = "astrolabe_net_rec"
ASTROLABE_NET_REC.full_name = ".common.astrolabe_net_rec"
ASTROLABE_NET_REC.nested_types = {}
ASTROLABE_NET_REC.enum_types = {}
ASTROLABE_NET_REC.fields = {
	var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_ASTROLABE_ID_FIELD,
	var_0_1.ASTROLABE_NET_REC_FIELD_LIST.ASTROLABE_NET_REC_POS_FIELD
}
ASTROLABE_NET_REC.is_extendable = false
ASTROLABE_NET_REC.extensions = {}
astrolabe_net_rec = var_0_0.Message(ASTROLABE_NET_REC)
equip_net_rec = var_0_0.Message(EQUIP_NET_REC)
hero_info_net_rec = var_0_0.Message(HERO_INFO_NET_REC)
hero_net_rec = var_0_0.Message(HERO_NET_REC)
mimir_net_rec = var_0_0.Message(MIMIR_NET_REC)

return team_hrl_pb
