LazyLoad = import("game.LazyLoad"):GetInstance()

require("game/includeMod")
require("game/data/DataInclude")
require("game/battle/BattleInclude")
require("game/tools/StringTools")
require("game/tools/PrintTools")
require("game/bridge/BattleCallLua")
require("game/bridge/SDKCallBack")
require("game/bridge/CheckVersion")
require("game/bridge/BattlePolyhedronCall")
require("game/ConfigHelper")
require("game/chess/ChessInclude")
require("game/newchess/NewWarChessInclude")
require("game.dorm.DormInclude")
require("game/data/heroDataTemplate/HeroDataTemplateInclude")
