return {
	GAME_NEWCHESS_ATTRIBUTE_MOVE_POINT = {
		default = 60,
		min = 0,
		id = 1,
		enum = "GAME_NEWCHESS_ATTRIBUTE_MOVE_POINT",
		max = 200
	},
	GAME_NEWCHESS_ATTRIBUTE_DICE_MAX = {
		default = 6,
		min = 0,
		id = 2,
		enum = "GAME_NEWCHESS_ATTRIBUTE_DICE_MAX",
		max = 10
	},
	GAME_NEWCHESS_ATTRIBUTE_FOG_LENGTH = {
		default = 4,
		min = 0,
		id = 3,
		enum = "GAME_NEWCHESS_ATTRIBUTE_FOG_LENGTH",
		max = 99
	},
	GAME_NEWCHESS_ATTRIBUTE_BREAK_BOX = {
		default = 0,
		min = 0,
		id = 4,
		enum = "GAME_NEWCHESS_ATTRIBUTE_BREAK_BOX",
		max = 1
	},
	GAME_NEWCHESS_ATTRIBUTE_FIX_HOLE = {
		default = 0,
		min = 0,
		id = 5,
		enum = "GAME_NEWCHESS_ATTRIBUTE_FIX_HOLE",
		max = 1
	},
	GAME_NEWCHESS_ATTRIBUTE_CONTROL_PLATFORM = {
		default = 0,
		min = 0,
		id = 6,
		enum = "GAME_NEWCHESS_ATTRIBUTE_CONTROL_PLATFORM",
		max = 1
	},
	GAME_NEWCHESS_ATTRIBUTE_HOLD_DOWN_SPRINT = {
		default = 0,
		min = 0,
		id = 7,
		enum = "GAME_NEWCHESS_ATTRIBUTE_HOLD_DOWN_SPRINT",
		max = 1
	},
	GAME_NEWCHESS_ATTRIBUTE_MOVE_POINT_COST_TIMES = {
		default = 1000,
		min = 0,
		id = 8,
		enum = "GAME_NEWCHESS_ATTRIBUTE_MOVE_POINT_COST_TIMES",
		max = 10000
	},
	GAME_NEWCHESS_ATTRIBUTE_DICE_TO_MOVE_POINT_TIMES = {
		default = 1000,
		min = 0,
		id = 9,
		enum = "GAME_NEWCHESS_ATTRIBUTE_DICE_TO_MOVE_POINT_TIMES",
		max = 10000
	},
	GAME_NEWCHESS_ATTRIBUTE_EXPLORE_POINT = {
		default = 0,
		min = 0,
		id = 10,
		enum = "GAME_NEWCHESS_ATTRIBUTE_EXPLORE_POINT",
		max = 10000
	},
	GAME_NEWCHESS_ATTRIBUTE_FIRST_IN = {
		default = 0,
		min = 0,
		id = 11,
		enum = "GAME_NEWCHESS_ATTRIBUTE_FIRST_IN",
		max = 1
	},
	GAME_NEWCHESS_ATTRIBUTE_FINISH = {
		default = 0,
		min = 0,
		id = 12,
		enum = "GAME_NEWCHESS_ATTRIBUTE_FINISH",
		max = 1
	},
	GAME_NEWCHESS_ATTRIBUTE_CHANCE_DICE_SUM = {
		default = 0,
		min = 0,
		id = 13,
		enum = "GAME_NEWCHESS_ATTRIBUTE_CHANCE_DICE_SUM",
		max = 50
	},
	GAME_NEWCHESS_ATTRIBUTE_CHANCE_MARK = {
		default = 0,
		min = 0,
		id = 14,
		enum = "GAME_NEWCHESS_ATTRIBUTE_CHANCE_MARK",
		max = 10000
	},
	GAME_NEWCHESS_ATTRIBUTE_TASK_MARK = {
		default = 0,
		min = 0,
		id = 15,
		enum = "GAME_NEWCHESS_ATTRIBUTE_TASK_MARK",
		max = 10000
	},
	GAME_NEWCHESS_ATTRIBUTE_REVERSE_MECHANISM = {
		default = 0,
		min = 0,
		id = 16,
		enum = "GAME_NEWCHESS_ATTRIBUTE_REVERSE_MECHANISM",
		max = 1
	},
	GAME_NEWCHESS_ATTRIBUTE_TEMPORARY_FIX_HOLE = {
		default = 0,
		min = 0,
		id = 17,
		enum = "GAME_NEWCHESS_ATTRIBUTE_TEMPORARY_FIX_HOLE",
		max = 1
	},
	all = {
		GAME_NEWCHESS_ATTRIBUTE_MOVE_POINT,
		GAME_NEWCHESS_ATTRIBUTE_DICE_MAX,
		GAME_NEWCHESS_ATTRIBUTE_FOG_LENGTH,
		GAME_NEWCHESS_ATTRIBUTE_BREAK_BOX,
		GAME_NEWCHESS_ATTRIBUTE_FIX_HOLE,
		GAME_NEWCHESS_ATTRIBUTE_CONTROL_PLATFORM,
		GAME_NEWCHESS_ATTRIBUTE_HOLD_DOWN_SPRINT,
		GAME_NEWCHESS_ATTRIBUTE_MOVE_POINT_COST_TIMES,
		GAME_NEWCHESS_ATTRIBUTE_DICE_TO_MOVE_POINT_TIMES,
		GAME_NEWCHESS_ATTRIBUTE_EXPLORE_POINT,
		GAME_NEWCHESS_ATTRIBUTE_FIRST_IN,
		GAME_NEWCHESS_ATTRIBUTE_FINISH,
		GAME_NEWCHESS_ATTRIBUTE_CHANCE_DICE_SUM,
		GAME_NEWCHESS_ATTRIBUTE_CHANCE_MARK,
		GAME_NEWCHESS_ATTRIBUTE_TASK_MARK,
		GAME_NEWCHESS_ATTRIBUTE_REVERSE_MECHANISM,
		GAME_NEWCHESS_ATTRIBUTE_TEMPORARY_FIX_HOLE
	}
}
