return {
	TIMING_BUFF = 6,
	TIMING_START = 1,
	TIMING_WALK_OUT = 2,
	TIMING_WALK_INTO_OBJECT = 9,
	TIMING_ALL = 13,
	TIMING_INTERACT_OBJECT = 10,
	TIMING_TASK = 7,
	NEW_WARCHESS_TEMPLATE_DEFULT = 1,
	TIMING_WALK_OUT_OBJECT = 8,
	TIMING_CHANCE_CHOOSE = 5,
	TIMING_INTERACT = 4,
	HERO_HP_RATE = 100000,
	TIMING_GLOBAL_EVENT = 12,
	TIMING_FARCLICK_OBJECT = 11,
	TIMING_WALK_INTO = 3,
	HOME_STATUS = {
		MOVING = 2,
		FARCLICK = 4,
		NORMAL = 1,
		READY = 3
	},
	TASKTYPE = {
		NORMAL = 0,
		MAIN = 1
	},
	CHANCE_ITEM_STATUS = {
		NORMAL = 0,
		HIDE = 2,
		LOCK = 1
	},
	CHANCE_JUMP_TYPE = {
		LEFT_WITHOUTSAVE = 2,
		ATTRIBUTE_SWITCH_CHANCE = 8,
		DICE_SUM_SWITCH_CHANCE = 7,
		SELECT_CHANCE = 5,
		LEFT_WITHSAVE = 3,
		NEW_CHANCE = 1,
		DICE_SWITCH_CHANCE = 6,
		BATTLE = 4
	},
	EVENTPOOL_TYPE = {
		NEWWARCHESS_CHANCE = 2,
		NEWWARCHESS_EVENT = 1
	},
	HERO_EFFECT_TYPE = {
		DICESKILL = 2,
		BUFF = 1
	},
	TIPS_TYPE = {
		DICE = 3,
		SWITCH = 1,
		BUFF = 4,
		DANGEROUS = 2,
		NORMAL = 0
	},
	TIPS_NUM_COLOR = {
		GREEN = "#D6CE8C"
	},
	DICE_LIMIT_TYPE = {
		TWAIN = 1
	},
	SERVER_SEND_EVENTPARAMS_TYPE = {
		INT = 1,
		ARRAY = 2,
		TYPEID_AND_EVENTINFO = 4,
		ARRAY2 = 3,
		TYPEIDLIST_AND_EVENTINFO = 5
	},
	GLOBAL_EVENT_STATUS = {
		SUCCESS = 3,
		FAILD = 4,
		NORMAL = 0
	}
}
