return {
	[1009] = {
		cost = 100,
		name = "静滞射击",
		count = -1,
		type = 1,
		desc_negative = "若伤害的目标是<color=#CD6269>精英</color>或<color=#CD6269>Boss</color>，令其<color=#D0A3E2>进入控制抗性状态</color>。",
		desc_effect = "向队长当前锁定的目标造成500000点<color=#CD6269>风属性</color>伤害。若目标是精英或Boss，且可进入修正模式，则令其立刻<color=#D0A3E2>进入修正模式</color>。\n\n冷却时间15秒，可使用10次。",
		desc_background = "凝集大量神能聚合成束，对目标进行贯通射击，令其防御崩溃，丧失作战能力。\n\n简单粗暴，便携易用，但应对精英敌人的效果却不逊于任何先进武器，而这只是虚恒众多简约创造中的一个。对于虚恒人而言，最简单的往往最有效。",
		is_lock = 0,
		bg_name = "vhl_h_003",
		slot = 1,
		icon = "vhl_skill_1009",
		skill_id = 1009,
		lock_des = ""
	},
	[1004] = {
		cost = 100,
		name = "暗蚀力场",
		count = -1,
		type = 1,
		desc_negative = "力场内的所有敌方单位被<color=#CD6269>光</color>、<color=#CD6269>水</color>、<color=#CD6269>火</color>属性攻击命中后，回复其最大生命值的5%。\n\n力场内的所有我方<color=#CD6269>神能</color>类型修正者每秒减少20点神能，不受加成影响。",
		desc_effect = "向队长当前锁定目标的位置投放一个大型力场，持续15秒。\n\n力场内的所有敌方视骸单位<color=#D0A3E2>移动速度</color>降低80%，且每1.5秒受到400000点<color=#CD6269>暗属性</color>伤害。每受到一次力场伤害，<color=#CD6269>物理</color>抗性降低1%，可叠加，无上限，持续至关卡结束。\n\n冷却时间75秒，可使用2次。\n",
		desc_background = "释放一片逆向侵蚀力场，持续损伤和削弱力场内的视骸，使其在后续战斗中承受额外的伤害。\n\n该技术是侵蚀现象研究的意外成果，不过运作时会持续吸收神能，并将部分对敌方的伤害逆转为恢复效果，目前尚在隐科组改良计划清单中。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 1,
		icon = "vhl_skill_1004",
		skill_id = 1004,
		lock_des = "完成序章教程后解锁"
	},
	[1011] = {
		cost = 100,
		name = "急速冷却",
		count = -1,
		type = 1,
		desc_negative = "被冻结过的敌人受到<color=#CD6269>雷</color>、<color=#CD6269>光</color>、<color=#CD6269>暗</color>、<color=#CD6269>冰</color>属性伤害降低600%，不可叠加，持续至战斗结束。",
		desc_effect = "立刻<color=#D0A3E2>冻结</color>队长当前锁定目标的位置周围半径10米圆形范围内敌人，冻结持续时间30秒。被冻结的敌人受到<color=#CD6269>物理</color>、<color=#CD6269>风</color>、<color=#CD6269>水属性</color>伤害提升2000%。\n\n冷却时间60秒，可使用4次。",
		desc_background = "向目标位置投掷液氮罐，迅速冻结周围的普通敌人，令其变得脆弱易碎。\n\n冻结速度快，效果持久，最关键的是价格低廉。科尔盖约库尔支部坚称，液氮供应是他们与当地工厂签订过的采购协议里最划算的一个。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 1,
		icon = "vhl_skill_1011",
		skill_id = 1011,
		lock_des = "完成序章教程后解锁"
	},
	[1002] = {
		cost = 100,
		name = "乱流电场",
		count = -1,
		type = 1,
		desc_negative = "雷击会命中友方单位。命中己方单位时，造成12000点<color=#CD6269>雷属性</color>伤害，<color=#D0A3E2>移动速度</color>降低95%，持续10秒，不可刷新。每个己方单位被命中一次后，免疫本轮后续雷击。\n\n每次启动时，我方所有单位<color=#CD6269>物理</color>、<color=#CD6269>水</color>、<color=#CD6269>冰</color>属性攻击力降低80%，持续30秒，不可刷新。\n",
		desc_effect = "向队长当前锁定目标周围20米圆形范围内的随机一点发起雷击，每0.8秒打击一次，共10次，每次雷击命中敌人时造成300000-500000点<color=#CD6269>雷属性</color>伤害，并<color=#D0A3E2>清空抗性点数</color>，<color=#D0A3E2>禁锢</color>5秒，重复触发时刷新。\n\n技能启动后，全场友方单位<color=#CD6269>风属性</color>攻击力提高60%，持续20秒，不可刷新。\n\n冷却时间70秒，可使用3次。\n",
		desc_background = "制造一个环形电场，迅速释放闪电无差别打击目标区域，并致使麻痹与灼伤。\n\n该装备的设计初衷是用远端装置引导妙尔尼尔的力量，期望实现比托尔本人更稳定的战场支援，但奔腾的闪电似乎完全继承了托尔横冲直撞的作风，原因不明。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 1,
		icon = "vhl_skill_1002",
		skill_id = 1002,
		lock_des = "完成第一章后解锁"
	},
	[1003] = {
		cost = 100,
		name = "重力井",
		count = -1,
		type = 1,
		desc_negative = "技能启动后8秒，我方所有单位<color=#D0A3E2>移动速度</color>降低70%，持续12秒，不可刷新",
		desc_effect = "将战场较大范围内的非霸体敌方单位<color=#D0A3E2>聚集</color>到队长当前锁定目标的位置，<color=#D0A3E2>聚集</color>效果持续15秒。\n\n技能启动后10秒，<color=#D0A3E2>禁锢</color>该位置周围5米内的敌方单位10秒，不可刷新。\n\n冷却时间50秒，可使用2次。\n",
		desc_background = "放置一个扭曲锚点，形成区域性的重力井，将周围敌人拉拢至中心。随着扭曲效应的扩散，重力场的扰动将大幅影响我方的机动性。\n\n云歌石重力控制技术的战术化应用，曾被误认为是吸尘智械的改良方案而长期封存。",
		is_lock = 1,
		bg_name = "vhl_h_003",
		slot = 1,
		icon = "vhl_skill_1003",
		skill_id = 1003,
		lock_des = "完成第一章后解锁"
	},
	[1005] = {
		cost = 100,
		name = "心灵震荡",
		count = -1,
		type = 1,
		desc_negative = "引爆时，我方所有修正者受到90%最大生命值的<color=#CD6269>光属性</color>伤害，该伤害不会致死。",
		desc_effect = "将梦境装置校准至队长当前锁定目标的位置，并聚集能量，5秒后引爆。\n\n引爆时，将该位置周围10米圆形范围内的非精英人类敌人<color=#D0A3E2>转变为友方单位</color>，持续至关卡结束。所有非人类敌人受到1200000点<color=#CD6269>光属性</color>伤害。\n\n被转变的目标永久增加8000点基础攻击力。\n\n冷却时间70秒，可使用3次。",
		desc_background = "释放强烈的心灵干扰波，使波及的人类陷入异化认知的梦境中，从而成为我方的盟友。\n\n梦境装置的超载现象所衍生的特殊应用，但不可避免地伴随着破坏力强大的精神冲击，非专业人士禁止使用。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 1,
		icon = "vhl_skill_1005",
		skill_id = 1005,
		lock_des = "完成第一章后解锁"
	},
	[1010] = {
		cost = 100,
		name = "支援协议",
		count = -1,
		type = 1,
		desc_negative = "每次启动时，扰动因子+30",
		desc_effect = "呼叫6名科尔盖骸震对策部特工入场，支援战斗。\n\n可使用1次。",
		desc_background = "向科尔盖发送增援信号，委派一队特工进入战场提供支援。\n\n盟友能在你需要的时候随时抵达战场，以最高效的方式清除威胁，不过你恐怕得按他们的惯例来，即使这意味着一些混乱。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 1,
		icon = "vhl_skill_1010",
		skill_id = 1010,
		lock_des = "完成第一章后解锁"
	},
	[1001] = {
		cost = 100,
		name = "远火阵列",
		count = -1,
		type = 1,
		desc_negative = "每次启动时，扰动因子+15",
		desc_effect = "区域跟随锁定目标移动。\n\n向队长当前锁定的目标周围3米的圆形范围发起远程炮击，每0.2秒炮击一次，共20次，每次炮击命中敌人时造成200000-250000点<color=#CD6269>物理</color>伤害。\n\n冷却时间70秒，可使用3次。\n",
		desc_background = "呼叫轨道炮阵列，对目标区域进行密集炮击，对范围内的敌人造成毁灭性打击。\n\n由科尔盖提供的超视距火力支援，射速快，杀伤力惊人，不过这种突兀的火力投射不免会引发一些混乱。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 1,
		icon = "vhl_skill_1001",
		skill_id = 1001,
		lock_des = "完成第二章后解锁"
	},
	[1012] = {
		cost = 100,
		name = "高爆燃料桶",
		count = -1,
		type = 1,
		desc_negative = "每次启动时，扰动因子+10",
		desc_effect = "在队长当前锁定目标处引发一次剧烈爆炸，造成500000点<color=#CD6269>火属性</color>伤害。若该目标为<color=#CD6269>塔骸</color>、<color=#CD6269>精英</color>、<color=#CD6269>Boss</color>、或<color=#CD6269>霸体</color>单位，则造成3000000点<color=#CD6269>火属性</color>伤害。\n\n被伤害的敌人受到的<color=#CD6269>火属性</color>伤害提升40%，不可叠加，持续至战斗结束。\n\n冷却时间45秒，可使用5次。",
		desc_background = "向目标位置投掷混合燃料桶，引发剧烈爆炸冲击敌人，并令其难以耐受火焰。\n\n因为前线的一次爆炸事故，这种后勤物资被列入了战略物资清单中，据说科尔盖的部分指挥官很中意爆炸的威力，但高昂的成本一直让后勤部大为光火。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 1,
		icon = "vhl_skill_1012",
		skill_id = 1012,
		lock_des = "完成第二章后解锁"
	},
	[1008] = {
		cost = 100,
		name = "能级干扰",
		count = -1,
		type = 1,
		desc_negative = "武器启动后，当前场内所有<color=#CD6269>非视骸类</color>敌人攻击力提高350%，不可叠加，持续至关卡结束",
		desc_effect = "立刻<color=#D0A3E2>禁锢</color>当前场内所有视骸类敌人，禁锢持续时间15秒，不可刷新。\n\n武器启动后，当前场内所有<color=#CD6269>神能</color>修正者增加40点<color=#CD6269>神能</color>，不受加成影响。\n\n武器启动后，<color=#D0A3E2>所有敌方单位暂停刷新</color>（不含召唤物），持续30秒。进入<color=#D0A3E2>零时空间</color>可<color=#D0A3E2>提前结束该效果</color>。\n\n冷却时间60秒，可使用2次。\n",
		desc_background = "干涉和重塑战场的神能流向，禁锢视骸并为我方供给神能。\n\n该武器基于循理之环的原理制造，其链式效应会增强非视骸敌人的攻击能力。为此，海姆达尔提供了一份全面的操作指南，但由于内容过于详细和复杂，没有人真的读过。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 1,
		icon = "vhl_skill_1008",
		skill_id = 1008,
		lock_des = "完成序章教程后解锁"
	},
	[1007] = {
		cost = 100,
		name = "声光脉冲",
		count = -1,
		type = 1,
		desc_negative = "武器启动后，当前场内所有<color=#CD6269>视骸</color>类敌人获得80%最终伤害减免，不可叠加，持续至关卡结束。\n\n武器启动后，当前场内所有<color=#CD6269>神能</color>修正者减少40点神能，不受加成影响。\n\n<color=#CD6269>物理属性</color>、<color=#CD6269>水属性</color>、<color=#CD6269>冰属性</color>、<color=#CD6269>风属性</color>攻击命中被<color=#D0A3E2>眩晕</color>的敌人时，解除眩晕效果，并令其造成的伤害增加500%，不可叠加，持续至关卡结束。",
		desc_effect = "立刻<color=#D0A3E2>眩晕</color>当前场内所有人类敌人，持续20秒，不可刷新。\n\n武器启动后，<color=#D0A3E2>所有敌方单位暂停刷新</color>（不含召唤物），持续30秒。进入<color=#D0A3E2>零时空间</color>可<color=#D0A3E2>提前结束该效果</color>。\n\n冷却时间60秒，可使用2次。\n",
		desc_background = "释放精准调校的声光冲击，致使人类目标肌肉麻痹，失去方向感，丧失行动能力。\n\n这种非致命性装备在控制复杂场面时颇为有效，但目标若意外恢复知觉则会变得极具攻击性，该装备增强视骸和损耗神能的副作用也不容小视。因此科尔盖有时会主动干预局面避免事态升级，以减少对该装备的需求。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 1,
		icon = "vhl_skill_1007",
		skill_id = 1007,
		lock_des = "完成第一章后解锁"
	},
	[1006] = {
		cost = 100,
		name = "电晶过载",
		count = -1,
		type = 1,
		desc_negative = "武器启动后，当前场内所有<color=#CD6269>视骸</color>类敌人获得80%最终伤害减免，不可叠加，持续至关卡结束。\n\n武器启动后，当前场内所有<color=#CD6269>神能</color>修正者减少40点神能，不受加成影响。\n\n<color=#CD6269>雷属性</color>与<color=#CD6269>火属性</color>攻击命中被<color=#D0A3E2>禁锢</color>的敌人时，解除禁锢效果，并产生一次小范围爆炸。爆炸命中我方单位时，造成15000点<color=#CD6269>物理</color>伤害",
		desc_effect = "立刻<color=#D0A3E2>禁锢</color>当前场内所有智械类敌人，持续30秒，不可刷新。\n\n武器启动后，<color=#D0A3E2>所有敌方单位暂停刷新</color>（不含召唤物），持续30秒。进入<color=#D0A3E2>零时空间</color>可<color=#D0A3E2>提前结束该效果</color>。\n\n冷却时间60秒，可使用2次。\n",
		desc_background = "释放广域的共振波，引起战场上所有智械的电晶机件过载，实现暂时性的行动阻断。\n\n该装置是对抗智械部队的有效措施，但过载智械在意外重启时将执行自毁，装置运行的余波还将增强视骸，损耗神能，为此，科尔盖制定了严格的使用规程，以规避不必要的损失。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 1,
		icon = "vhl_skill_1006",
		skill_id = 1006,
		lock_des = "完成第二章后解锁"
	},
	[2001] = {
		cost = 100,
		name = "护盾力场",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "使当前场内所有己方修正者进入<color=#D0A3E2>无敌状态</color>，持续时间10秒，不可刷新。\n\n冷却时间40秒，可使用2次",
		desc_background = "利用便携式的力场发生器制造屏障力场，偏折所有针对我方的攻击。\n\n该装备防御性能卓越，但能耗较高，使用次数和持续时间都很有限，因此在常规战斗中尚不能完全取代传统的大盾。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 2,
		icon = "vhl_skill_2001",
		skill_id = 2001,
		lock_des = ""
	},
	[2004] = {
		cost = 100,
		name = "牺牲之焰",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "在队长所在位置引燃火焰，火焰会命中己方单位。己方单位被命中时，受到最大生命值50%的<color=#CD6269>火属性</color>伤害，并提高自身35%<color=#CD6269>火属性</color>伤害，持续30秒，不可刷新。\n\n冷却时间50秒，可使用2次",
		desc_background = "引燃神秘的咒火，以牺牲生命力为代价，换取掌控火焰的能力。\n\n强大的力量所需的代价同样巨大，可以肯定的是，它的所有者正走在一条阴影笼罩的道路上。",
		is_lock = 1,
		bg_name = "vhl_h_005",
		slot = 2,
		icon = "vhl_skill_2004",
		skill_id = 2004,
		lock_des = "完成序章教程后解锁"
	},
	[2005] = {
		cost = 100,
		name = "重整姿态",
		count = -1,
		type = 1,
		desc_negative = "每次启动时，扰动因子+5",
		desc_effect = "立刻进入持续时间5秒的<color=#D0A3E2>零时空间</color>，并刷新队长闪避效果冷却时间。\n\n冷却时间30秒，可使用4次",
		desc_background = "进入弥弥尔开启的零时空间，暂时避开周遭威胁并快速恢复状态。\n\n尽管弥弥尔大人有很多秘密，但讨好它却不算太难，给它一瓶精调可乐，它就会在能力范围内尽量满足你的要求。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 2,
		icon = "vhl_skill_2005",
		skill_id = 2005,
		lock_des = "完成序章教程后解锁"
	},
	[2002] = {
		cost = 100,
		name = "万愈气脉",
		count = -1,
		type = 1,
		desc_negative = "回复生命后的5秒内，若被敌方命中，将在命中后每秒损失5000点生命值，持续5秒",
		desc_effect = "在队长位置设置一片区域，启动3秒后，<color=#D0A3E2>恢复</color>该区域内所有己方单位32000点生命值。\n\n冷却时间45秒，可使用2次",
		desc_background = "模拟陵光的神能特性，在目标区域布下一片恢复气脉，进行群体治疗。\n云歌之变中，虚恒伤患众多，烛用这种方法大幅减轻了陵光的负担。但从记载上看，气脉恢复将导致伤患短暂的虚弱，需要小心看护。",
		is_lock = 1,
		bg_name = "vhl_h_003",
		slot = 2,
		icon = "vhl_skill_2002",
		skill_id = 2002,
		lock_des = "完成第一章后解锁"
	},
	[2003] = {
		cost = 100,
		name = "活血剂",
		count = -1,
		type = 1,
		desc_negative = "己方单位每受一次影响，最大生命值-5%，持续至关卡结束，可叠加，无上限",
		desc_effect = "提高队长周围半径12.5米圆形范围内所有己方单位的<color=#CD6269>雷</color>、<color=#CD6269>冰</color>、<color=#CD6269>物理</color>、<color=#CD6269>光</color>属性伤害30%，并获得1200点/秒的生命<color=#D0A3E2>回复</color>效果。持续15秒，不可刷新。\n\n冷却时间40秒，可使用3次",
		desc_background = "释放气雾状的刺激性药剂，激发战斗潜能与恢复效率，不过会带来一定的身体负担。\n\n弥楼衍的秘密武器，虽然气味一言难尽，副作用古怪，但在加尔动荡的街头中行走，随身携带一瓶仍是明智之选。",
		is_lock = 1,
		bg_name = "vhl_h_004",
		slot = 2,
		icon = "vhl_skill_2003",
		skill_id = 2003,
		lock_des = "完成第二章后解锁"
	},
	[2006] = {
		cost = 100,
		name = "热点",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "令全场敌人立刻以队长为攻击目标，队长防御力增加80%，持续20秒，不可刷新。\n\n冷却时间35秒，可使用3次。",
		desc_background = "释放广域的多频信号挑衅敌人，吸引其注意力集中至队长身上。\n\n当敌人被诱饵吸引而沉迷追逐，等待他们的将是无数的陷阱与伏击。赏金猎人的世界里，少有公平可言。",
		is_lock = 1,
		bg_name = "vhl_h_006",
		slot = 2,
		icon = "vhl_skill_2006",
		skill_id = 2006,
		lock_des = "完成第一章后解锁"
	},
	[2008] = {
		cost = 100,
		name = "泡影",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "使当前所有己方非修正者单位进入<color=#D0A3E2>无敌</color>状态，持续时间12秒，不可刷新。\n\n可使用1次。",
		desc_background = "展开幻象空间环绕友方，吸收并消解所有针对友方的攻击。\n\n薄雾微光，镜花水月，飘渺的虚影拥抱着挚爱的人们，不息的风暴只是一场转瞬即逝的梦。",
		is_lock = 1,
		bg_name = "vhl_h_005",
		slot = 2,
		icon = "vhl_skill_2008",
		skill_id = 2008,
		lock_des = "完成第一章后解锁"
	},
	[2007] = {
		cost = 100,
		name = "命运之线",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "若队长当前锁定的目标为非霸体敌人，则将该敌人立刻拖拽至队长处。\n\n冷却时间17秒，可使用12次。",
		desc_background = "发射数条傀儡丝线，束缚目标并将其拖拽至面前。\n\n弹指之间，宿命之线牢牢系住了所追之物，这不是华美舞步的序曲，仅仅是归于安宁的挽歌。",
		is_lock = 1,
		bg_name = "vhl_h_005",
		slot = 2,
		icon = "vhl_skill_2007",
		skill_id = 2007,
		lock_des = "完成第二章后解锁"
	},
	[3001] = {
		cost = 0,
		name = "闪避",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "令队长立刻尝试闪避或格挡。\n\n冷却时间5秒",
		desc_background = "指示队长立刻转为守备态势，规避或防御迫近的攻击。\n\n高威胁作战中，科尔盖特工的行动将受到精确的指挥，即使是基础的战术动作也经常通过指令直接传达。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 3,
		icon = "vhl_skill_3001",
		skill_id = 3001,
		lock_des = ""
	},
	[3002] = {
		cost = 0,
		name = "焦点打击",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "命令所有己方单位攻击队长当前锁定的目标。\n\n冷却时间2秒",
		desc_background = "指示小队发起联合作战，集中打击向指定的目标。\n\n集合所有力量的猛烈进攻，即使是再强大的对手也难以承受。科尔盖的人类特工通常以此战术消灭高威胁目标。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 3,
		icon = "vhl_skill_3002",
		skill_id = 3002,
		lock_des = ""
	},
	[3003] = {
		cost = 0,
		name = "多点突击",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "命令所有己方单位尽可能攻击不同的目标。\n\n冷却时间2秒",
		desc_background = "指示小队实施多线作战，分头执行对不同目标的打击。\n\n这种战术充分利用了成员个人的战斗能力，科尔盖的修正者们往往以此战术应对数量上占优的敌人。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 3,
		icon = "vhl_skill_3003",
		skill_id = 3003,
		lock_des = ""
	},
	[4001] = {
		cost = 0,
		name = "密集队形",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "令全队停止攻击，并聚集至队长周围。\n\n再次点击时恢复自由开火。",
		desc_background = "指挥小队成员收缩队形，快速集结在队长周围。\n\n这种队形有助于队员间的互相协作与支援，提升了应对各种突发状况的能力，常用于情报有限的侦察行动。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 4,
		icon = "vhl_skill_3004",
		skill_id = 4001,
		lock_des = ""
	},
	[4002] = {
		cost = 0,
		name = "机动队形",
		count = -1,
		type = 1,
		desc_negative = "无负面效果。",
		desc_effect = "令全队停止攻击，并尽可能远离队长。\n\n再次点击时恢复自由开火。",
		desc_background = "指挥小队成员展开队形，以队长为中心迅速分散。\n\n这种队形牺牲了成员间的即时支援，提升了团队应对广域威胁时的生存能力，常用于执行灾害区域的清理与支援任务。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 4,
		icon = "vhl_skill_3005",
		skill_id = 4002,
		lock_des = ""
	},
	[5001] = {
		cost = 100,
		name = "对兵战术I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对人类伤害提高10%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5001,
		lock_des = ""
	},
	[5002] = {
		cost = 200,
		name = "对兵战术II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对人类伤害提高20%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5002,
		lock_des = "完成第一章后解锁"
	},
	[5003] = {
		cost = 300,
		name = "对兵战术III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对人类伤害提高30%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5003,
		lock_des = "完成第二章后解锁"
	},
	[5004] = {
		cost = 100,
		name = "对钢战术I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对智械伤害提高10%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 0,
		bg_name = "vhl_h_003",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5004,
		lock_des = ""
	},
	[5005] = {
		cost = 200,
		name = "对钢战术II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对智械伤害提高20%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 1,
		bg_name = "vhl_h_003",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5005,
		lock_des = "完成第一章后解锁"
	},
	[5006] = {
		cost = 300,
		name = "对钢战术III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对智械伤害提高30%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 1,
		bg_name = "vhl_h_003",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5006,
		lock_des = "完成第二章后解锁"
	},
	[5007] = {
		cost = 100,
		name = "对骸战术I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对视骸伤害提高10%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 0,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5007,
		lock_des = ""
	},
	[5008] = {
		cost = 200,
		name = "对骸战术II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对视骸伤害提高20%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5008,
		lock_des = "完成第一章后解锁"
	},
	[5009] = {
		cost = 300,
		name = "对骸战术III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，对视骸伤害提高30%",
		desc_background = "常规的对策性增益，精英修正者们已经较少选用，妥善运用的话仍然具有一定价值。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5009,
		lock_des = "完成第二章后解锁"
	},
	[5035] = {
		cost = 120,
		name = "强攻I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，攻击力提高8%",
		desc_background = "精英修正者群体中备受欢迎的进攻性增益，作战部经过交涉获得其调用权限，旨在提供泛用性强化，提升整体作战效率。",
		is_lock = 0,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5035,
		lock_des = ""
	},
	[5036] = {
		cost = 240,
		name = "强攻II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，攻击力提高16%",
		desc_background = "精英修正者群体中备受欢迎的进攻性增益，作战部经过交涉获得其调用权限，旨在提供泛用性强化，提升整体作战效率。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5036,
		lock_des = "完成第一章后解锁"
	},
	[5037] = {
		cost = 360,
		name = "强攻III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，攻击力提高24%",
		desc_background = "精英修正者群体中备受欢迎的进攻性增益，作战部经过交涉获得其调用权限，旨在提供泛用性强化，提升整体作战效率。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5037,
		lock_des = "完成第二章后解锁"
	},
	[5038] = {
		cost = 120,
		name = "狂怒I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，会心伤害提高10%",
		desc_background = "在精英修正者中备受欢迎的进攻性增益，作战部通过交涉获得其调用权限，旨在强化关键打击以期迅速结束战斗。",
		is_lock = 0,
		bg_name = "vhl_h_005",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5038,
		lock_des = ""
	},
	[5039] = {
		cost = 240,
		name = "狂怒II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，会心伤害提高20%",
		desc_background = "在精英修正者中备受欢迎的进攻性增益，作战部通过交涉获得其调用权限，旨在强化关键打击以期迅速结束战斗。",
		is_lock = 1,
		bg_name = "vhl_h_005",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5039,
		lock_des = "完成第一章后解锁"
	},
	[5040] = {
		cost = 360,
		name = "狂怒III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，会心伤害提高30%",
		desc_background = "在精英修正者中备受欢迎的进攻性增益，作战部通过交涉获得其调用权限，旨在强化关键打击以期迅速结束战斗。",
		is_lock = 1,
		bg_name = "vhl_h_005",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5040,
		lock_des = "完成第二章后解锁"
	},
	[5010] = {
		cost = 100,
		name = "刚毅I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，受到的伤害降低10%",
		desc_background = "常规的防护性增益，精英修正者们已经较少选用，但其带来的生存能力仍然能在一些场合发挥效用。",
		is_lock = 0,
		bg_name = "vhl_h_004",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5010,
		lock_des = ""
	},
	[5011] = {
		cost = 200,
		name = "刚毅II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，受到的伤害降低20%",
		desc_background = "常规的防护性增益，精英修正者们已经较少选用，但其带来的生存能力仍然能在一些场合发挥效用。",
		is_lock = 1,
		bg_name = "vhl_h_004",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5011,
		lock_des = "完成第一章后解锁"
	},
	[5012] = {
		cost = 300,
		name = "刚毅III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，受到的伤害降低30%",
		desc_background = "常规的防护性增益，精英修正者们已经较少选用，但其带来的生存能力仍然能在一些场合发挥效用。",
		is_lock = 1,
		bg_name = "vhl_h_004",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5012,
		lock_des = "完成第二章后解锁"
	},
	[5013] = {
		cost = 100,
		name = "进攻型工事I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位基础攻击力提高400",
		desc_background = "进攻特化的携带式工程装备，具备快速部署能力，能够为局部作战提供进攻优势。\n\n拥有三种不同等级，以适应各类作战任务的需要。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5013,
		lock_des = ""
	},
	[5014] = {
		cost = 200,
		name = "进攻型工事II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位基础攻击力提高800",
		desc_background = "进攻特化的携带式工程装备，具备快速部署能力，能够为局部作战提供进攻优势。\n\n拥有三种不同等级，以适应各类作战任务的需要。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5014,
		lock_des = "完成第一章后解锁"
	},
	[5015] = {
		cost = 300,
		name = "进攻型工事III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位基础攻击力提高1200",
		desc_background = "进攻特化的携带式工程装备，具备快速部署能力，能够为局部作战提供进攻优势。\n\n拥有三种不同等级，以适应各类作战任务的需要。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5015,
		lock_des = "完成第二章后解锁"
	},
	[5016] = {
		cost = 100,
		name = "防护型工事I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位基础防御力提高1000",
		desc_background = "防护特化的携带式工程装备，具备快速部署能力，能够为局部作战提供防护优势。\n\n拥有三种不同等级，以适应各类作战任务的需要。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5016,
		lock_des = ""
	},
	[5017] = {
		cost = 200,
		name = "防护型工事II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位基础防御力提高2000",
		desc_background = "防护特化的携带式工程装备，具备快速部署能力，能够为局部作战提供防护优势。\n\n拥有三种不同等级，以适应各类作战任务的需要。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5017,
		lock_des = "完成第一章后解锁"
	},
	[5018] = {
		cost = 300,
		name = "防护型工事III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位基础防御力提高4000",
		desc_background = "防护特化的携带式工程装备，具备快速部署能力，能够为局部作战提供防护优势。\n\n拥有三种不同等级，以适应各类作战任务的需要。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5018,
		lock_des = "完成第二章后解锁"
	},
	[5023] = {
		cost = 100,
		name = "长效恢复剂",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "战斗开始60秒后生效。\n\n生效后，我方修正者每秒恢复120点生命值，持续至战斗结束。",
		desc_background = "缓释型治疗药剂，可在短暂延迟后提供稳定而持续的生命恢复。在快速对抗中作用有限，但能够在持久的消耗战中长时间维持战斗力。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_3",
		skill_id = 5023,
		lock_des = "完成第二章后解锁"
	},
	[5024] = {
		cost = 100,
		name = "急救药剂",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者生命值小于10%后，恢复12000点生命值，并在100秒内流失12000点生命值。\n\n仅生效一次。恢复效果无法抵挡致死伤害。",
		desc_background = "感应式药剂，紧急情况下将自动释放，为重伤者快速恢复生命，助其脱离危机。该药物的副作用将导致使用者缓慢流失生命，因此不宜用于常规治疗。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_3",
		skill_id = 5024,
		lock_des = "完成第二章后解锁"
	},
	[5041] = {
		cost = 300,
		name = "神能导向仪",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，修正系数降低80%，对普通敌人伤害提高40%",
		desc_background = "隐科组的战术研究成果，通过定向引导部分神能的流动大幅增强攻击威力。据说该研究曾经长期受阻，却因奥丁部分权能的启发而在短时间内顺利完成。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5041,
		lock_des = "完成第二章后解锁"
	},
	[5025] = {
		cost = 140,
		name = "无尽构筑I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，获得15%奥义值",
		desc_background = "阿卡德公会精英修正者的支援武装，能够为使用者提供一定的先发优势。流入公会前的多次转手让其价格远超正规渠道，但公会佣兵们很快就用它赚回了差价。",
		is_lock = 0,
		bg_name = "vhl_h_006",
		slot = 0,
		icon = "vhl_skill_generic_3",
		skill_id = 5025,
		lock_des = ""
	},
	[5026] = {
		cost = 280,
		name = "无尽构筑II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，获得30%奥义值",
		desc_background = "阿卡德公会精英修正者的支援武装，能够为使用者提供一定的先发优势。流入公会前的多次转手让其价格远超正规渠道，但公会佣兵们很快就用它赚回了差价。",
		is_lock = 1,
		bg_name = "vhl_h_006",
		slot = 0,
		icon = "vhl_skill_generic_3",
		skill_id = 5026,
		lock_des = "完成第一章后解锁"
	},
	[5027] = {
		cost = 420,
		name = "无尽构筑III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "我方修正者出场后，获得45%奥义值",
		desc_background = "阿卡德公会中精英修正者的支援武装，能够为使用者提供一定的先发优势。该装备为早期的高级型号，似乎不是一个佣兵公会可以得到的资源。",
		is_lock = 1,
		bg_name = "vhl_h_006",
		slot = 0,
		icon = "vhl_skill_generic_3",
		skill_id = 5027,
		lock_des = "完成第二章后解锁"
	},
	[5028] = {
		cost = 100,
		name = "神能灌注I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位修正系数提高10%",
		desc_background = "科研中心神取计划的重要成果，为普通武器附着神能，增强人类部队对抗精英视骸的能力。",
		is_lock = 0,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5028,
		lock_des = ""
	},
	[5029] = {
		cost = 200,
		name = "神能灌注II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位修正系数提高20%",
		desc_background = "科研中心神取计划的重要成果，为普通武器附着神能，增强人类部队对抗精英视骸的能力。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5029,
		lock_des = "完成第一章后解锁"
	},
	[5030] = {
		cost = 300,
		name = "神能灌注III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "场上非修正者友方单位修正系数提高30%",
		desc_background = "科研中心神取计划的重要成果，为普通武器附着神能，增强人类部队对抗精英视骸的能力。\n\n我们相信着人类的可能性，从未改变。",
		is_lock = 1,
		bg_name = "vhl_h_001",
		slot = 0,
		icon = "vhl_skill_generic_1",
		skill_id = 5030,
		lock_des = "完成第二章后解锁"
	},
	[5031] = {
		cost = 100,
		name = "敌情侦察I",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "敌方的攻击力降低5%",
		desc_background = "鸦家御刀众将在战前前往探查敌情，协助执行针对性防御，削弱敌方攻势。",
		is_lock = 0,
		bg_name = "vhl_h_005",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5031,
		lock_des = ""
	},
	[5032] = {
		cost = 200,
		name = "敌情侦察II",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "敌方的攻击力降低10%",
		desc_background = "鸦家御刀众将在战前前往探查敌情，协助执行针对性防御，削弱敌方攻势。",
		is_lock = 1,
		bg_name = "vhl_h_005",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5032,
		lock_des = "完成第一章后解锁"
	},
	[5033] = {
		cost = 300,
		name = "敌情侦察III",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "敌方的攻击力降低15%",
		desc_background = "鸦家御刀众将在战前前往探查敌情，协助部署针对性防御措施，以削弱敌方攻势。\n\n情报称曾有科尔盖小队因不可靠情报而部署失误遭遇全歼，不过这条情报本身同样不可靠。",
		is_lock = 1,
		bg_name = "vhl_h_005",
		slot = 0,
		icon = "vhl_skill_generic_2",
		skill_id = 5033,
		lock_des = "完成第二章后解锁"
	},
	[5034] = {
		cost = 300,
		name = "紧急维修",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "通讯链路塔生命值小于25%后，恢复最大生命值40%的血量。\n\n仅生效一次。无法抵挡致死伤害。",
		desc_background = "虚恒朔方提供的维护技术，能够快速修复机械结构的损伤，用于核心工事的紧急防护。\n\n原先是维护采矿智械的冷门技术，但正确运用能够决定一条战线的成败。",
		is_lock = 1,
		bg_name = "vhl_h_003",
		slot = 0,
		icon = "vhl_skill_generic_3",
		skill_id = 5034,
		lock_des = "完成第一章后解锁"
	},
	[5019] = {
		cost = 400,
		name = "C级派遣许可",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "战斗结束时，扰动因子-20",
		desc_background = "深空之眼将在战后派遣C级修正者队伍协助清理战场，恢复区域秩序。对他们来说这样的任务略显平淡，但他们依旧会尽职尽责。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_4",
		skill_id = 5019,
		lock_des = "完成第一章后解锁"
	},
	[5020] = {
		cost = 400,
		name = "公会委托协议",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "若场上未出现过视骸，战斗结束时，扰动因子-25",
		desc_background = "限于没有视骸活动的场合，阿卡德公会的佣兵小队将在战后协助战场清理。佣兵们虽然为钱卖命，但也不会做出无意义的牺牲。",
		is_lock = 1,
		bg_name = "vhl_h_006",
		slot = 0,
		icon = "vhl_skill_generic_4",
		skill_id = 5020,
		lock_des = "完成第二章后解锁"
	},
	[5021] = {
		cost = 500,
		name = "铃兰团召集令",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "若场上未出现过视骸，战斗结束时，扰动因子-25",
		desc_background = "限于没有视骸活动的场合，铃兰团骑士将在战后协助战场清理。受区域防卫任务和人力的限制，铃兰团通常无法派遣精锐力量出外作战。",
		is_lock = 1,
		bg_name = "vhl_h_007",
		slot = 0,
		icon = "vhl_skill_generic_4",
		skill_id = 5021,
		lock_des = "完成第二章后解锁"
	},
	[5022] = {
		cost = 500,
		name = "天禄安保合约",
		count = 1,
		type = 0,
		desc_negative = "无负面效果。",
		desc_effect = "战斗结束时，扰动因子-20",
		desc_background = "天禄贸易将在战后派遣安保队协助清理战场，恢复区域秩序。关于这支安保力量的公开信息并不充分，但足以证明其实力与效率值得信赖。",
		is_lock = 1,
		bg_name = "vhl_h_008",
		slot = 0,
		icon = "vhl_skill_generic_4",
		skill_id = 5022,
		lock_des = "完成第一章后解锁"
	},
	[6001] = {
		cost = 15000,
		name = "修正者指挥",
		count = 1,
		type = 0,
		desc_negative = "队长修正者出场后，扰动因子+2500。\n\n所有主动技能不可使用。",
		desc_effect = "允许直接指挥修正者进行战斗。",
		desc_background = "综合科主管已证实这一作战方式在部分高风险作战中的有效性，但我方作为人类的最终防线，作战决策中将不会考虑该主管介入的特定情形。\n\n因此我方指挥官需要掌握这种作战方式，以确保在最不利的情况下，仍能成功完成任务。",
		is_lock = 1,
		bg_name = "vhl_h_002",
		slot = 0,
		icon = "vhl_skill_generic_4",
		skill_id = 6001,
		lock_des = "完成第三章后解锁"
	},
	all = {
		1009,
		1004,
		1011,
		1002,
		1003,
		1005,
		1010,
		1001,
		1012,
		1008,
		1007,
		1006,
		2001,
		2004,
		2005,
		2002,
		2003,
		2006,
		2008,
		2007,
		3001,
		3002,
		3003,
		4001,
		4002,
		5001,
		5002,
		5003,
		5004,
		5005,
		5006,
		5007,
		5008,
		5009,
		5035,
		5036,
		5037,
		5038,
		5039,
		5040,
		5010,
		5011,
		5012,
		5013,
		5014,
		5015,
		5016,
		5017,
		5018,
		5023,
		5024,
		5041,
		5025,
		5026,
		5027,
		5028,
		5029,
		5030,
		5031,
		5032,
		5033,
		5034,
		5019,
		5020,
		5021,
		5022,
		6001
	}
}
