return {
	[2017] = {
		skill3 = "",
		skill2 = "自爆",
		information3 = "无法自主打开表层通道，一般会顺着自然的裂缝或者高级视骸打开的通道抵达表层。",
		type = 0,
		model_name = "2017_tpose",
		skill_desc6 = "",
		desc = "具有虫类特征的小型视骸。",
		race = 7,
		skill_desc2 = "移动至附近的敌人身边并自爆。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "单一个体的破坏力不大，但数量众多，通常会群体行动。",
		skill_desc1 = "向前飞扑一小段距离，攻击前方的敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "飞扑",
		id = 2017,
		information2 = "是啃食、破坏源层数据的主要战力，到达活动上限的个体，会寻找最近的目标并引爆自己。"
	},
	[2018] = {
		skill3 = "",
		skill2 = "铲击",
		information3 = "偶尔会在工厂的角落里看到它默默对着废旧的集装箱练习搬运技巧的身影。",
		type = 0,
		model_name = "2018_tpose",
		skill_desc6 = "",
		desc = "体型小巧的叉车型智械，能够穿梭于狭窄的空间进行作业。",
		race = 8,
		skill_desc2 = "双臂猛力向前方铲击，站在攻击路径上的敌人会被击飞。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "低级智械，主要在斯皮尔特工厂承担一些搬运或打杂的工作。",
		skill_desc1 = "左右两侧的机械臂依次向前挥击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "挥击",
		id = 2018,
		information2 = "虽然是工厂中最不受重视的存在，仍然兢兢业业地完成每天的任务。"
	},
	[2019] = {
		skill3 = "",
		skill2 = "浮游炮击",
		information3 = "由于搭载的系统对环境的变化过于敏感，为了避免误伤，削弱了它的部分战斗能力。",
		type = 0,
		model_name = "2019_tpose",
		skill_desc6 = "",
		desc = "体型小巧的巡查型智械，通过头部的装置发射激光扫描访客身份。",
		race = 8,
		skill_desc2 = "蓄力后向前射出光炮攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "斯皮尔特工业中负责侦查工作的智械，主要工作是侦查、引导秩序。",
		skill_desc1 = "快速向前射出激光攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "激光速射",
		id = 2019,
		information2 = "对于任何可能威胁到工厂安全的隐患，都会在第一时间发出警报。"
	},
	[2020] = {
		skill3 = "野蛮挥击",
		skill2 = "手枪射击",
		information3 = "普遍战斗能力不强，较为优秀的部分会提拔成为小队长。",
		type = 0,
		model_name = "2020_tpose",
		skill_desc6 = "",
		desc = "穿着轻型作战服的安保队员。",
		race = 6,
		skill_desc2 = "掏出手枪射击前方的敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "野蛮地挥舞步枪砸向敌人。",
		skill5 = "",
		information1 = "受雇于迷铁安保的低级部员，部分是从迷铁之家中直接选调的，也有在成立安保公司后再进行社招的。",
		skill_desc1 = "蹲下并端起步枪，对前方的敌人进行狙击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "远程狙击",
		id = 2020,
		information2 = "搭配有远程牵制的枪械作为武器，具体操纵熟练度亦不得而知，在打斗中弃甲逃跑也是完全有可能的。"
	},
	[2021] = {
		skill3 = "",
		skill2 = "致命旋转",
		information3 = "如果妨碍到它工作的话，就会变得十分暴躁。",
		type = 0,
		model_name = "2021_tpose",
		skill_desc6 = "",
		desc = "体型小巧的电锯型智械，拥有一定的破坏力",
		race = 8,
		skill_desc2 = "切换姿态，高速旋转着冲向敌人，持续一段时间。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "低级智械，主要在斯皮尔特工厂承担一些搬运或打杂的工作。",
		skill_desc1 = "并拢两侧的锯臂，向前使出全力一击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "热锯突进",
		id = 2021,
		information2 = "两侧装配的电锯能够快速高效地切割物品，并且不会产生高分贝的噪音。"
	},
	[2022] = {
		skill3 = "",
		skill2 = "蓄能散射",
		information3 = "最好不要站在它和工作台之间，否则会被当成需要焊接的货品给处理掉。",
		type = 0,
		model_name = "2022_tpose",
		skill_desc6 = "",
		desc = "体型小巧的焊枪型智械，拥有一定的破坏力",
		race = 8,
		skill_desc2 = "蓄力后向前射出光炮攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "低级智械，主要在斯皮尔特工厂承担一些搬运或打杂的工作。",
		skill_desc1 = "发射远距离炮击攻击前方的敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "聚能焊击",
		id = 2022,
		information2 = "远程攻击、控制手段为主。不具有逃跑和反击的手段，近身后很好对付，但在中远距离上时威胁较大。"
	},
	[2025] = {
		skill3 = "",
		skill2 = "蓄力冲撞",
		information3 = "被打败时会从机体深处传出含混的机械音，其意义恐怕只有它的创造者才知道。",
		type = 0,
		model_name = "2025_tpose",
		skill_desc6 = "",
		desc = "残缺的人形智械，仍然保留着强烈的战斗欲望",
		race = 8,
		skill_desc2 = "蓄力后对远处的敌人发动冲撞攻击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "研发「智械军团」的过程也并不是一帆风顺的。这些残破的人型智械就是初期研发过程中的失败品。",
		skill_desc1 = "抬起独臂，释放出一道强力电弧攻击远处的敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "高热电弧",
		id = 2025,
		information2 = "这种残破的人型智械虽然在机动力和输出火力上有所缺失，但机身骨架是完全按照B-01的先进设计制造的，如果因为它畸形的外表而粗心大意，那么势必会付出极为惨痛的代价。"
	},
	[2026] = {
		skill3 = "突变·重锤",
		skill2 = "突变·战戟",
		information3 = "被侵蚀的人类在视骸化前通常拥有不俗的体力。",
		type = 0,
		model_name = "2026_tpose",
		skill_desc6 = "",
		desc = "人类完全被视骸侵蚀后的产物，手持棍型武器，矫健的身形中蕴含着无穷的爆发力。",
		race = 7,
		skill_desc2 = "武器形态变化为战戟，向前劈砍后挑飞敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "武器形态变化为重锤，向前大范围横扫后跳起锤击敌人。",
		skill5 = "",
		information1 = "由裂隙来到表层的视骸个体完全侵蚀人类之后形成的物种，没有自主意识，就像是工蜂一般以蜂巢中蜂后的意志为主行动。",
		skill_desc1 = "武器形态变化为巨镰，向前劈砍后横扫攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "突变·巨镰",
		id = 2026,
		information2 = "使用棍型武器施展近距离的打击，会进行简单思考，有一定威胁性。"
	},
	[2027] = {
		skill3 = "",
		skill2 = "空间震波",
		information3 = "被侵蚀的人类在视骸化前通常拥有不俗的智力。",
		type = 0,
		model_name = "2027_tpose",
		skill_desc6 = "",
		desc = "人类完全被视骸侵蚀后的产物，手持杖型武器，以高傲的姿态展开远程攻击。",
		race = 7,
		skill_desc2 = "召唤一道强力震波攻击前方的敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "由裂隙来到表层的视骸个体完全侵蚀人类之后形成的物种，没有自主意识，就像是工蜂一般以蜂巢中蜂后的意志为主行动。",
		skill_desc1 = "对敌人站立的区域释放圆形地裂，造成持续性伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "灼热地裂",
		id = 2027,
		information2 = "使用杖型的武器发动远距离冲击，会进行简单思考，有一定威胁性。"
	},
	[2029] = {
		skill3 = "",
		skill2 = "狂乱利爪",
		information3 = "虽然不具备思考能力，但能依靠野兽的本能直觉行动，对危险相当警觉。",
		type = 0,
		model_name = "2029_tpose",
		skill_desc6 = "",
		desc = "兽类完全被视骸侵蚀后的产物，似乎在侵蚀过程中混入了人类的数据片段，因此有着兽人的外形。",
		race = 7,
		skill_desc2 = "向前方的敌人释放出两道锋利的爪击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "由裂隙来到表层的视骸个体完全侵蚀兽类之后形成的物种。",
		skill_desc1 = "发出震耳欲聋的咆哮，对周围的敌人造成伤害，并在短时间内增加自己的攻击力。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "暗影咆哮",
		id = 2029,
		information2 = "行动模式诡异多变，会使用锋利的爪牙作为武器撕裂敌人。"
	},
	[2030] = {
		skill3 = "激昂战意",
		skill2 = "防御姿态",
		information3 = "普遍战斗能力不强，较为优秀的部分会提拔成为小队长。",
		type = 0,
		model_name = "2030_tpose",
		skill_desc6 = "",
		desc = "体格强壮，身着厚重的保护装备。",
		race = 6,
		skill_desc2 = "举盾抵御敌人的伤害。由于全神贯注于前方，很容易被敌人绕后打断。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "展开进攻架势，提升攻击力。",
		skill5 = "",
		information1 = "受雇于迷铁安保的低级部员，部分是从迷铁之家中直接选调的，也有在成立安保公司后再进行社招的。",
		skill_desc1 = "举盾向前冲撞敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "盾冲",
		id = 2030,
		information2 = "搭配有近战用的剑盾作为武器，具体操纵熟练度亦不得而知，在打斗中弃甲逃跑也是完全有可能的。"
	},
	[2032] = {
		skill3 = "",
		skill2 = "冲刺裁决",
		information3 = "使用武士刀作为武器，抱着必胜的执念，不知伤痛、不知疲倦地挥舞。",
		type = 0,
		model_name = "2032_tpose",
		skill_desc6 = "",
		desc = "于远吕知的结合实验中诞生的人形视骸，是技术早期的试作品。",
		race = 7,
		skill_desc2 = "冲向敌人所在的位置，旋转身体攻向敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "原本是宫蛇家培养的武士，自愿接受了尚不稳定的视骸化改造。",
		skill_desc1 = "跳起旋转攻击一周后落地并给予敌人终结一击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "刀舞",
		id = 2032,
		information2 = "拥有最简单的思维能力，会以清除宫蛇家的一切敌人作为行动准则。"
	},
	[2033] = {
		skill3 = "",
		skill2 = "破风手里剑",
		information3 = "使用苦无作为武器，其上附着的毒物和易爆物会令战斗变得非常棘手。",
		type = 0,
		model_name = "2033_tpose",
		skill_desc6 = "",
		desc = "于远吕知的结合实验中诞生的人形视骸，是技术早期的试作品。",
		race = 7,
		skill_desc2 = "掷出三把手里剑攻击前方的敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "原本是宫蛇家培养的武士，自愿接受了尚不稳定的视骸化改造。",
		skill_desc1 = "跃向空中，掷出两把手里剑攻击敌人。若手里剑未命中，则落地一段时间后自动爆炸，造成小范围的伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "凌空手里剑",
		id = 2033,
		information2 = "拥有最简单的思维能力，会以清除宫蛇家的一切敌人作为行动准则。"
	},
	[2036] = {
		skill3 = "",
		skill2 = "爪击",
		information3 = "视骸化后它们的野兽本能和狩猎欲望会变得更强，利齿尖牙就是它们最有力的武器。",
		type = 0,
		model_name = "2036_tpose",
		skill_desc6 = "",
		desc = "脊柱高耸，姿态犹如野狗一般。",
		race = 7,
		skill_desc2 = "挥动双爪攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "兽种视骸的其中一种，由视骸侵蚀犬类生物诞生。",
		skill_desc1 = "蓄力跳至敌人身前，甩动锋利的尾巴进行攻击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "甩尾",
		id = 2036,
		information2 = "前爪更加偏向于人类手臂的构造，可能是在侵蚀过程中混杂了人类的数据片段所导致的。"
	},
	[2037] = {
		skill3 = "",
		skill2 = "十字斩",
		information3 = "独自构成的危害有限，但因其群居性和庞大的数量，一旦发现位面的裂口就会蜂拥而出，是骸震发生后令修正者最为头疼的敌人……",
		type = 0,
		model_name = "2037_tpose",
		skill_desc6 = "",
		desc = "脑袋圆形偏大，脸部的所有面积几乎都被巨大的独目所占据。",
		race = 7,
		skill_desc2 = "挥舞长矛进行十字形攻击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "有观测以来，可以追溯到活动痕迹最为久远的视骸类型，很大可能是所有视骸的雏形。",
		skill_desc1 = "挥舞长矛攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "兵蚁刺击",
		id = 2037,
		information2 = "手持由侵蚀晶体削成的尖锐长枪，喜欢成群地在源层活动，故得名蚁骸。"
	},
	[2038] = {
		skill3 = "",
		skill2 = "分解射线",
		information3 = "独自构成的危害有限，但因其群居性和庞大的数量，一旦发现位面的裂口就会蜂拥而出，是骸震发生后令修正者最为头疼的敌人……",
		type = 0,
		model_name = "2038_tpose",
		skill_desc6 = "",
		desc = "硕大的头部与细瘦的身体形成了强烈的反差，镶嵌在头部中央的独眼散发出让人不安的光线。",
		race = 7,
		skill_desc2 = "蓄力后发射激光攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "有观测以来，可以追溯到活动痕迹最为久远的视骸类型，很大可能是所有视骸的雏形。",
		skill_desc1 = "振动翅膀高速旋转三周，然后用力向前冲撞攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "离心冲撞",
		id = 2038,
		information2 = "具有飞行能力，能够在快速飞行的过程中用尖锐的双爪攻击敌人，故得名翼骸。"
	},
	[2040] = {
		skill3 = "",
		skill2 = "守卫、圣殿！",
		information3 = "据说这种智械刚投入使用时，吓坏了不少胆小的老师和学生，一时间千星学院内关于这类智械的怪谈层出不穷。",
		type = 0,
		model_name = "2040_tpose",
		skill_desc6 = "",
		desc = "为了融入千星学院优雅的环境而研发出的安保智械，拥有雕像般美丽的外表。尽管学生和市民都知道这种智械的存在，偶尔还是会被突然移动的雕像吓一跳！",
		race = 8,
		skill_desc2 = "举起长剑，蓄力后对远距离的敌人发动突刺攻击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "这类人形雕像类智械可以说是千星学院的特色和风景线了，经过更新迭代，如今已成为运用最广，适用性最好的类型。",
		skill_desc1 = "举起长剑，对近距离的敌人发动劈砍攻击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "就、就此止步",
		id = 2040,
		information2 = "虽说它们一动不动的模样与雕像并无二致，但身体表面隐隐流动的机械光泽赋予了它们别样的美感，成为许多美术系学生的临摹对象。"
	},
	[2041] = {
		skill3 = "",
		skill2 = "静谧暗域",
		information3 = "尽管它的战斗能力不是那么出色，在执行巡逻任务时，其优秀的侦查系统总是能第一时间捕捉到危险的气息。",
		type = 0,
		model_name = "2041_tpose",
		skill_desc6 = "",
		desc = "为了融入千星学院优雅的环境而研发出的安保智械，拥有雕像般美丽的外表。尽管学生和市民都知道这种智械的存在，偶尔还是会被突然移动的雕像吓一跳！",
		race = 8,
		skill_desc2 = "以自身为中心释放圆形能量场，对区域内的敌人造成减速效果。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "这类智械通常用于监视、警诫心怀不轨的入侵者，其侦查能力和机动性都十分优越。",
		skill_desc1 = "汇聚能量，发射一道高能脉冲攻击前方的敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "凌光脉冲",
		id = 2041,
		information2 = "设计者为了保证了它的机动性，不得不一次次削减其重量，直到符合最初的设计标准为止。"
	},
	[2043] = {
		skill3 = "信约之力",
		skill2 = "电能冲锋",
		information3 = "如此强大的智械也是有弱点的，只要击中那个关键的部位，就可以轻松打破Z-01的钢铁躯壳，不过……至今还没有人能完成这项挑战。",
		type = 0,
		model_name = "2043_tpose",
		skill_desc6 = "",
		desc = "犹如铁桶般坚固的外形，战场上所向披靡的存在。",
		race = 8,
		skill_desc2 = "张开护盾向前冲撞，随后挥舞充能机械臂横扫攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "近距离横扫攻击敌人。",
		skill5 = "",
		information1 = "战斗性能检测显示，兼容性、装甲抗性、火力输出均远超同档位智械。虽然在外部覆盖着几乎毫无缝隙的坚固护甲，但凭借背后的助推系统也能在短时间内爆发出惊人的机动性，所带来的机能过载也只有一瞬。",
		skill_desc1 = "挥舞蓄满电能的机械臂攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "震颤电击",
		id = 2043,
		information2 = "先进的科技压缩了材料成本和生产时间，由此Z-01信约型战争智械已经具备了量产化的条件。"
	},
	[2044] = {
		skill3 = "荣光使命",
		skill2 = "利钻火花",
		information3 = "根据型号装备了不同的手臂，有切割锯、电钻等不同的类型……",
		type = 0,
		model_name = "2044_tpose",
		skill_desc6 = "",
		desc = "生产线上的头号功臣，稳固的身躯上搭载着各种工具。",
		race = 8,
		skill_desc2 = "启动电钻模块，戳刺攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "双模块同时启动，冲撞攻击敌人。",
		skill5 = "",
		information1 = "<荣光>型智械身上搭载了许多工业生产用的装备，看上去扎实的形体使得它们可以负担许多繁重的任务。",
		skill_desc1 = "启动电锯模块，横扫攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "电锯横扫",
		id = 2044,
		information2 = "躯干和上肢比较强壮，使其可以负担许多繁重的生产作业。"
	},
	[2045] = {
		skill3 = "",
		skill2 = "疾速弹雨",
		information3 = "经常悠闲地游走在工厂各处，观察各个车间的工作状况。",
		type = 0,
		model_name = "2045_tpose",
		skill_desc6 = "",
		desc = "四肢灵活，动作迅捷，搭载了激光武器装置。",
		race = 8,
		skill_desc2 = "快速发射子弹攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "在A-06<荣光>智械正式投放后，A-03<胡杨>凭借着其低耗能和高精度的优势仍然有在生产。",
		skill_desc1 = "蓄力后向前射出光炮攻击敌人，在炮弹的落点附近会产生持续伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "侵蚀炮击",
		id = 2045,
		information2 = "因为生产任务被分走，部分<胡杨>型智械装备上了激光武器担当工厂内部平时的看护。"
	},
	[2049] = {
		skill3 = "",
		skill2 = "灵巧旋踢",
		information3 = "由于欧莫菲斯长期的和平景况，导致部分成员疏于练习，实际的战斗力有所下降。",
		type = 0,
		model_name = "2049_tpose",
		skill_desc6 = "",
		desc = "日常驻扎于千星学院的铃兰骑士团女性队员，主要负责维护星虹议会和千星学院艺术圣殿的安全。",
		race = 6,
		skill_desc2 = "跃起踢击并挑飞前方的敌人，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "作为欧莫菲斯治安的守护者，团员们接受过基础的战斗训练，搭配的武器一般为近战武器，部分特殊成员配有长弓。",
		skill_desc1 = "发射一道强有力的箭矢攻击远距离的敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "爆发箭矢",
		id = 2049,
		information2 = "不少成员对艺术怀有敬仰之情，但自己没办法成为艺术家，于是决心守卫艺术。"
	},
	[2050] = {
		skill3 = "辉耀突袭",
		skill2 = "英勇横扫",
		information3 = "由于欧莫菲斯长期的和平景况，导致部分成员疏于练习，实际的战斗力有所下降。",
		type = 0,
		model_name = "2050_tpose",
		skill_desc6 = "",
		desc = "日常驻扎于千星学院的铃兰骑士团男性队员，主要负责维护星虹议会和千星学院艺术圣殿的安全。",
		race = 6,
		skill_desc2 = "挥动长枪进行横扫，对近距离的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "冲刺至目标附近，举起长枪发动全力一击，对敌人造成伤害。",
		skill5 = "",
		information1 = "作为欧莫菲斯治安的守护者，团员们接受过基础的战斗训练，搭配的武器一般为近战武器，部分特殊成员配有长弓。",
		skill_desc1 = "举盾冲撞前方的敌人，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "卫护盾冲",
		id = 2050,
		information2 = "不少成员对艺术怀有敬仰之情，但自己没办法成为艺术家，于是决心守卫艺术。"
	},
	[2055] = {
		skill3 = "",
		skill2 = "幽萤·横扫",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2055_tpose",
		skill_desc6 = "",
		desc = "圣树遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "挥舞长戟斜劈后向前方扇形范围横扫攻击，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，出现后便以完全体的姿态存在。全身沾染着被污浊的液体，成为腐蚀巨树的，恶意的代行者。",
		skill_desc1 = "挥舞长戟向前劈击后接上挑攻击，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "幽萤·战戟",
		id = 2055,
		information2 = "可以发动更为强大的近距离打击，并能进行更深层次的思考。"
	},
	[2056] = {
		skill3 = "毒萤·障目",
		skill2 = "毒萤·掠影",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2056_tpose",
		skill_desc6 = "",
		desc = "圣树遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "挥舞法杖向下斜劈，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "挥舞法杖，从敌人脚下召唤一团毒雾，对敌人造成伤害。",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，从最初的就能以完全体的姿态存在。全身沾染着被污浊的液体，成为腐蚀巨树的，恶意的代行者。",
		skill_desc1 = "挥舞法杖召唤虫群，驱使虫群向前冲刺，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "毒萤·奔突",
		id = 2056,
		information2 = "可以发动更为强大的远距离冲击，并能进行更深层次的思考。"
	},
	[2057] = {
		skill3 = "斗者·变",
		skill2 = "斗者·破",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2057_tpose",
		skill_desc6 = "",
		desc = "真樱遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "手持长枪发动两连刺击，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "手持长枪，发动一系列富于变化的攻击，使敌人措手不及。",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，出现后便以完全体的姿态存在。猩红浸染它的身躯，其上伤痕密布，徘徊在战争的幻影中无法解脱。",
		skill_desc1 = "手持长枪刺向前方敌人，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "斗者·勇",
		id = 2057,
		information2 = "可以发动更为强大的近距离打击，并能进行更深层次的思考。"
	},
	[2058] = {
		skill3 = "",
		skill2 = "震洄",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2058_tpose",
		skill_desc6 = "",
		desc = "真樱遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "召唤一道强力震波攻击前方的敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，从最初的就能以完全体的姿态存在。猩红浸染它的身躯，其上伤痕密布，徘徊在战争的幻影中无法解脱。",
		skill_desc1 = "对敌人站立的区域释放圆形地裂，造成持续性伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "幽缚",
		id = 2058,
		information2 = "可以发动更为强大的远距离冲击，并能进行更深层次的思考。"
	},
	[2059] = {
		skill3 = "凌闪",
		skill2 = "碎风",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2059_tpose",
		skill_desc6 = "",
		desc = "奥山遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "手持长戟向前横扫并戳刺敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "手持长戟向前多次戳刺敌人，打出连环攻击。",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，出现后便以完全体的姿态存在。森皑白骨附着在关节各处，生与死的轮回之间，微光溢散。",
		skill_desc1 = "手持长戟向前戳刺，攻击前方的敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "荒灵",
		id = 2059,
		information2 = "可以发动更为强大的近距离打击，并能进行更深层次的思考。"
	},
	[2060] = {
		skill3 = "",
		skill2 = "幻海",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2060_tpose",
		skill_desc6 = "",
		desc = "奥山遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "从敌人脚下召唤出树状地刺进行攻击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，从最初的就能以完全体的姿态存在。森皑白骨附着在关节各处，生与死的轮回之间，微光溢散。",
		skill_desc1 = "向前释放球状能量体，对攻击范围内的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "旋星",
		id = 2060,
		information2 = "可以发动更为强大的远距离冲击，并能进行更深层次的思考。"
	},
	[2061] = {
		skill3 = "矫跃",
		skill2 = "利爪",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2061_tpose",
		skill_desc6 = "",
		desc = "尼罗遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "手持长矛对前方敌人使出上挑攻击后向下劈击，造成一定的伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "跃起并对前方的敌人使出劈击，对敌人造成伤害。",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，出现后便以完全体的姿态存在。挣脱束缚后完全兽化，展露利爪獠牙，在沙尘之中蠢蠢欲动。",
		skill_desc1 = "手持长矛向前方圆形范围内使出两段横扫，对近距离范围内的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "狂袭",
		id = 2061,
		information2 = "可以发动更为强大的近距离打击，并能进行更深层次的思考。"
	},
	[2062] = {
		skill3 = "",
		skill2 = "尘沙",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2062_tpose",
		skill_desc6 = "",
		desc = "尼罗遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "召唤出一道尘沙龙卷袭向敌人，造成一定的伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，从最初的就能以完全体的姿态存在。挣脱束缚后完全兽化，展露利爪獠牙，在沙尘之中蠢蠢欲动。",
		skill_desc1 = "从敌人脚下召唤出尖锐的石牙攻击敌人，数秒后炸裂并造成二段伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "刺刃",
		id = 2062,
		information2 = "可以发动更为强大的远距离冲击，并能进行更深层次的思考。"
	},
	[2063] = {
		skill3 = "泯灭",
		skill2 = "罪迹",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2063_tpose",
		skill_desc6 = "",
		desc = "众星遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "手持巨镰向下劈击，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "蓄力后挥舞巨镰向前方使出两段横扫，对敌人造成伤害。",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，出现后便以完全体的姿态存在。展现群星黯淡的一面，披挂破碎的面纱，被视为前往幽寂虚空的引路人。",
		skill_desc1 = "手持巨镰向前劈砍后横扫攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "咎罚",
		id = 2063,
		information2 = "可以发动更为强大的近距离打击，并能进行更深层次的思考。"
	},
	[2064] = {
		skill3 = "星陨",
		skill2 = "星芒",
		information3 = "觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 0,
		model_name = "2064_tpose",
		skill_desc6 = "",
		desc = "众星遗迹中出现的变种视骸个体，吸取了神域遗迹的能量发生异变。",
		race = 7,
		skill_desc2 = "召唤一道强力射线，对前方的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "挥舞法杖，对靠近的敌人使出劈击，造成一定的伤害。",
		skill5 = "",
		information1 = "不再需要侵蚀完成蜕变，从最初的就能以完全体的姿态存在。展现群星黯淡的一面，披挂破碎的面纱，被视为前往幽寂虚空的引路人。",
		skill_desc1 = "从敌人脚下召唤出能量体，爆炸后对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "星爆",
		id = 2064,
		information2 = "可以发动更为强大的远距离冲击，并能进行更深层次的思考。"
	},
	[2065] = {
		skill3 = "音刃",
		skill2 = "酣畅",
		information3 = "虽然登上了那象征着荣耀的舞台，演奏曲子的只是一具失去灵魂的空壳罢了。",
		type = 0,
		model_name = "2065_tpose",
		skill_desc6 = "",
		desc = "风度翩翩的演奏师，来自一支巡回演出的知名舞团。受邀参加阿尔蒂斯盛典后花了数月的时间来准备节目，不料这份期盼和喜悦的心情最终演变为令人扼腕的悲剧。",
		race = 7,
		skill_desc2 = "演奏渐进高潮，音波能量泉涌而出，为自身或友方单位附加一层护盾。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "演奏师感知危险的到来，向前方释出一道凌厉的音刃，滑步后撤以拉开和敌人的距离。",
		skill5 = "",
		information1 = "外形与普通的演奏者并无区别，但面具下是人类与视骸的合成怪物。",
		skill_desc1 = "演奏师快速运弓，向远距离的敌人发射一道音波，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "启奏",
		id = 2065,
		information2 = "演奏时的姿态依然保持着优雅和端庄，仍然欺骗着自己正在进行一场演出。"
	},
	[2066] = {
		skill3 = "朔月诡步",
		skill2 = "满月韵律",
		information3 = "虽然登上了那象征着荣耀的舞台，尽情舞动的只是一具失去灵魂的空壳罢了。",
		type = 0,
		model_name = "2066_tpose",
		skill_desc6 = "",
		desc = "热情奔放的舞者，来自一支巡回演出的知名舞团。受邀参加阿尔蒂斯盛典后花了数月的时间来准备节目，不料这份期盼和喜悦的心情最终演变为令人扼腕的悲剧。",
		race = 7,
		skill_desc2 = "默舞者冲向目标，在目标位置发动旋转攻击，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "默舞者蓄力后闪电般向前舞动，挥舞手中的轮刃对前方的敌人造成伤害。",
		skill5 = "",
		information1 = "外形与普通的舞者并无区别，但面具下是人类与视骸的合成怪物。",
		skill_desc1 = "默舞者连续挥动轮刃，对近距离的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "新月锋芒",
		id = 2066,
		information2 = "在舞台上热情地邀请观众与她们互动，但她们手中的圆月轮环已经变成了充斥着骸能的恐怖兵器。"
	},
	[2067] = {
		skill3 = "迅光斩",
		skill2 = "恫吓之舞",
		information3 = "陶醉在自己的演出中，发现入侵者时会不顾一切地向对方挥舞巨大的镰刃，直至将对方彻底驱逐。",
		type = 0,
		model_name = "2067_tpose",
		skill_desc6 = "",
		desc = "舞团压轴表演的主角，糅合不同原质区舞蹈风格的精妙舞步如今变得诡异而激进。",
		race = 7,
		skill_desc2 = "镰舞者蓄力后挥动巨镰，对攻击范围内的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "镰舞者闪现至敌人身边，挥舞镰刀发动强力一击。",
		skill5 = "",
		information1 = "原本是一位风格独特的舞者，遭到视骸侵蚀后依然保有着过去对舞蹈的执念，攻击方式如同战舞一般凌厉而狂放。",
		skill_desc1 = "连续挥动两次镰刃，对近距离的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "刺骨打击",
		id = 2067,
		information2 = "挥动着巨大的镰刀武器，将自己的真实面目隐藏起来，快速而出其不意的攻击方式令敌人感到分外棘手。"
	},
	[2068] = {
		skill3 = "洄音",
		skill2 = "捶奏",
		information3 = "命运在某个瞬间猝然改变，摇铃师拥有的只剩不见尽头的苦痛与哀寂。",
		type = 0,
		model_name = "2068_tpose",
		skill_desc6 = "",
		desc = "沉默的摇铃师，原本只是一位隐居在钟楼的老人，受到视骸侵蚀后变得盲目而疯狂，不分昼夜地摇动着手中的铃铛。",
		race = 7,
		skill_desc2 = "摇铃师愤怒地挥动铃铛攻击敌人，对附近的敌人造成伤害。",
		skill4 = "挽歌",
		skill_desc5 = "",
		skill_desc3 = "当摇铃师的生命值降低至一半以下时，摇铃师感到自己的生命受到威胁，迅速地向后撤退远离敌人。",
		skill5 = "",
		information1 = "曾经默默无闻地守护着钟楼，陶醉地聆听古钟每一次敲响的声音。",
		skill_desc1 = "摇铃师摇晃铃铛，向远方发射一颗音波球，对远距离的敌人造成伤害。",
		skill_desc4 = "当摇铃师的生命值降低至一半以下时，摇铃师晃动铃铛，在身边召唤出旋转的音波球，对周围的敌人造成伤害。",
		skill6 = "",
		skill1 = "低语",
		id = 2068,
		information2 = "空闲时间也会带上自己的手铃与当地的合唱团或者乐团合奏，带来一场场令观众心旷神怡的表演。"
	},
	[2069] = {
		skill3 = "",
		skill2 = "障碍清扫",
		information3 = "时常看到它们巡逻，搬运物资或提着工具箱的样子，憨态可掬的外表下，具有普通人类难以匹敌的力量，在这次深空之眼的智械暴动中，也是当之无愧的破坏王。",
		type = 0,
		model_name = "2069_tpose",
		skill_desc6 = "",
		desc = "深空之眼所制造的智械，可爱的外形深受大家的欢迎，同时也是维护大楼秩序的得力助手。",
		race = 8,
		skill_desc2 = "向前冲刺撞击，对沿途的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "深空之眼所使用的智械。大国主设计并提供部分技术，由隐科组进行制作，深空之眼引以为豪的作品，在性能上比市面的智械更为先进。",
		skill_desc1 = "高高抬起前轮，砸击前方的地面，威慑扰乱秩序的敌人，同时造成一定的伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "严肃警告",
		id = 2069,
		information2 = "这类智械用于日常维修、安保、搬运、还有基础的指引工作，所以设计看起来较为粗壮结实。"
	},
	[2070] = {
		skill3 = "",
		skill2 = "全面服务",
		information3 = "在骸能的侵蚀下，这些智械变得极其危险。",
		type = 0,
		model_name = "2070_tpose",
		skill_desc6 = "",
		desc = "深空之眼所制造，用于迎宾接待的智械，内部有一个加热装置和制冷装置，可以为客人、职员们提供热饮或冷饮。",
		race = 8,
		skill_desc2 = "举起机械臂，干净利落地削切周围一圈的障碍。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "深空之眼所使用的智械。大国主设计并提供部分技术，由隐科组进行制作，深空之眼引以为豪的作品，在性能上比市面的智械更为先进。",
		skill_desc1 = "抬起机械臂，向前释放出一道电弧，对远距离的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "社交距离",
		id = 2070,
		information2 = "为了能平稳地将饮料或食品递给客人，设计成了悬浮移动的方式。"
	},
	[2073] = {
		skill3 = "",
		skill2 = "鹰眼射术",
		information3 = "射击的技术非常出色，被授予「鹰眼」的称号，能够在远距离交战中轻松取胜。",
		type = 0,
		model_name = "2073_tpose",
		skill_desc6 = "",
		desc = "罗斯塔赫的赏金猎人，隶属于当地的公会，通过完成悬赏向公会换取情报与食宿。",
		race = 6,
		skill_desc2 = "以流畅的动作向后空翻，于空中丢出爆破物，并在落地后举枪向目标射击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "工作的危险性导致大部分的赏金猎人不会以真面目示人，拥有很强的反侦察力。",
		skill_desc1 = "向目标脚下掷出爆破物，会在一段时间后于落点引发爆炸。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "延时爆破",
		id = 2073,
		information2 = "大多数赏金猎人都深受贫苦生活摧残，常年混迹在罗斯塔赫的黑巷与珍酿馆，不要试图激怒他们。"
	},
	[2074] = {
		skill3 = "",
		skill2 = "断刃战法",
		information3 = "斩击的技术非常出色，被授予「断刃」的称号，能够在近距离交战中轻松取胜。",
		type = 0,
		model_name = "2074_tpose",
		skill_desc6 = "",
		desc = "罗斯塔赫的赏金猎人，隶属于当地的公会，通过完成悬赏向公会换取情报与食宿。",
		race = 6,
		skill_desc2 = "以全身的力量积蓄气势，随后发动大范围横扫，并立刻衔接有力的重劈终结目标。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "工作的危险性导致大部分的赏金猎人不会以真面目示人，拥有很强的反侦察力。",
		skill_desc1 = "向目标发动一次突进攻击，在接近的过程中连续斩击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "突击刃袭",
		id = 2074,
		information2 = "大多数赏金猎人都深受贫苦生活摧残，常年混迹在罗斯塔赫的黑巷与珍酿馆，不要试图激怒他们。"
	},
	[2076] = {
		skill3 = "",
		skill2 = "火箭突袭",
		information3 = "会利用尖锐的身体作为攻击手段，从水面下突然发动袭击，需要小心应对。",
		type = 0,
		model_name = "2076_tpose",
		skill_desc6 = "",
		desc = "源初种的视骸之一，拥有类似海洋生物的结构，全身布满锋利的棘刺。",
		race = 7,
		skill_desc2 = "身体合拢进入特殊姿态，高速向空中飞起后下坠攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "通常隐藏在海洋中鲜少被目击，但其对海洋航行造成的影响不容忽视。",
		skill_desc1 = "从水面中跃出，向目标快速发射一道激光。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "闪烁激光",
		id = 2076,
		information2 = "由于无法判断群体数量，需要定期派遣修正者清理。"
	},
	[2077] = {
		skill3 = "",
		skill2 = "水面冲撞",
		information3 = "会利用尖锐的身体作为攻击手段，从水面下突然发动袭击，需要小心应对。",
		type = 0,
		model_name = "2077_tpose",
		skill_desc6 = "",
		desc = "源初种的视骸之一，拥有类似海洋生物的结构，全身布满锋利的棘刺。",
		race = 7,
		skill_desc2 = "身体合拢进入特殊姿态，高速向前方长距离突进攻击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "通常隐藏在海洋中鲜少被目击，但其对海洋航行造成的影响不容忽视。",
		skill_desc1 = "从水面中跃出，向目标快速发射一道激光。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "闪烁激光",
		id = 2077,
		information2 = "由于无法判断群体数量，需要定期派遣修正者清理。"
	},
	[2078] = {
		skill3 = "",
		skill2 = "",
		information3 = "装备有专用的近程武器，能够应对各类突发情况。即便是制式型号，也代表着科尔盖最高理事会超越性的科技水平。",
		type = 0,
		model_name = "2078_tpose",
		skill_desc6 = "",
		desc = "隶属于科尔盖最高理事会的机动作战人员。",
		race = 6,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "科尔盖最高理事会安保基础构成，分布在各个部门，负责处理对内安保、对外作战等各种安全保障需求。",
		skill_desc1 = "用制式长柄武器对敌人进行两次高速刺击，令敌人失去反抗能力。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "防暴管制",
		id = 2078,
		information2 = "使用型号统一的装备，训练有素，通常会以小队为单位进行高效作战。"
	},
	[2079] = {
		skill3 = "",
		skill2 = "",
		information3 = "装备有专用的远程武器，能够应对各类突发情况。即便是制式型号，也代表着科尔盖最高理事会超越性的科技水平。",
		type = 0,
		model_name = "2079_tpose",
		skill_desc6 = "",
		desc = "隶属于科尔盖最高理事会的机动作战人员。",
		race = 6,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "科尔盖最高理事会安保基础构成，分布在各个部门，负责处理对内安保、对外作战等各种安全保障需求。",
		skill_desc1 = "用制式枪械向前方多个区域发射镇暴弹，令敌人失去反抗能力。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "镇压射击",
		id = 2079,
		information2 = "使用型号统一的装备，训练有素，通常会以小队为单位进行高效作战。"
	},
	[2080] = {
		skill3 = "",
		skill2 = "",
		information3 = "善于将扑击与高温火焰喷吐结合，如若遭遇请小队成员将其作为优先修正目标。",
		type = 0,
		model_name = "2080_tpose",
		skill_desc6 = "",
		desc = "云歌之变后，在虚恒地区发现的特殊兽类视骸，外形呈现出类似狮、虎的特征，可见少量高亮度的云歌石晶体结构。",
		race = 7,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "在林地与山地地带目击到的视骸，体型与野兽相当，推测为受到特殊侵蚀形成的兽种。",
		skill_desc1 = "从口中向前方扇形区域喷射出蓝色扇形火焰，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "烈焰破击",
		id = 2080,
		information2 = "观测结果显示，该目标为云歌石环境影响下产生的特殊变体，数量相对有限。"
	},
	[2081] = {
		skill3 = "",
		skill2 = "",
		information3 = "善于利用雷电与跳跃冲击相结合的手段进攻，如若遭遇请小队成员将其作为优先修正目标。",
		type = 0,
		model_name = "2081_tpose",
		skill_desc6 = "",
		desc = "云歌之变后，在虚恒地区发现的特殊兽类视骸，外形呈现出类似鹿的特征，角部位可见少量高亮度的云歌石晶体结构。",
		race = 7,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "在林地与山地地带目击到的视骸，体型与野兽相当，推测为受到特殊侵蚀形成的兽种。",
		skill_desc1 = "经过短暂蓄力后向前方发动一次冲击，对路径上的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "怒意冲击",
		id = 2081,
		information2 = "观测结果显示，该目标为云歌石环境影响下产生的特殊变体，数量相对有限。"
	},
	[2082] = {
		skill3 = "魇祟",
		skill2 = "魇影",
		information3 = "虽然其战斗能力不强，但它无异于兽骸群的眼耳喉舌，需将其视为优先修正目标。",
		type = 0,
		model_name = "2082_tpose",
		skill_desc6 = "",
		desc = "百兽夜行期间出现的特殊兽类视骸，外形呈现出蝙蝠的特征，拥有良好的飞行能力。",
		race = 7,
		skill_desc2 = "向前俯冲冲撞，并在结束时用双翼进行挥砍，对范围内的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "张开双翼在周身散布骸能，对进入范围内的敌人发出骸能波动造成伤害。",
		skill5 = "",
		information1 = "据观测，单独行动时它的思维能力低下，只会横冲直撞。",
		skill_desc1 = "经过短暂蓄力后，向目标发射一枚骸能球，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "魇魔",
		id = 2082,
		information2 = "在群体行动时，它会游离在战场上空，观察情况的同时传达鹿神的指令。"
	},
	[2086] = {
		skill3 = "飞旋风刃",
		skill2 = "震怒重砸",
		information3 = "虽然其战斗能力一般，但它制造的麻烦远超想象，需将其视为优先修正目标。",
		type = 0,
		model_name = "2086_tpose",
		skill_desc6 = "",
		desc = "百兽夜行期间出现的特殊兽类视骸，外形呈现出蜥蜴的特征，拥有强有力的尾刃与尖爪。",
		race = 7,
		skill_desc2 = "短暂蓄力后，向前跃起并用尾刃猛击地面，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "短暂蓄力后，向目标挥出风刃对直线上的敌人造成伤害。",
		skill5 = "",
		information1 = "据观测，单独行动时它的思维能力低下，只会横冲直撞。",
		skill_desc1 = "向目标连续爪击，随后跃起向前方用尾刃砸击地面。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "恐爪暗袭",
		id = 2086,
		information2 = "在群体行动时，它会游离在战场外侧，运用多种攻击手段骚扰敌人。"
	},
	[2087] = {
		skill3 = "",
		skill2 = "骸晶突刺",
		information3 = "虽然其战斗能力不强，但它无异于兽骸群的矛与盾，需谨慎对待。",
		type = 0,
		model_name = "2087_tpose",
		skill_desc6 = "",
		desc = "百兽夜行期间出现的特殊兽类视骸，外形呈现出野猪的特征，拥有良好的奔跑能力。",
		race = 7,
		skill_desc2 = "蓄力在头顶凝聚结晶尖刺，随后向前方发动突刺并使尖刺炸裂，对敌人造成伤害。如果在蓄力时遭到攻击，则结晶尖刺将被打碎，不会炸裂。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "据观测，单独行动时它的思维能力低下，只会横冲直撞。",
		skill_desc1 = "蓄力后向目标位置发起冲锋，冲锋结束时头顶的骸能尖刺爆裂，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "凶蛮冲撞",
		id = 2087,
		information2 = "在群体行动时，它会与其他兽骸配合，充当它们的盾牌，在必要时还会成为直插敌阵的长矛。"
	},
	[2088] = {
		skill3 = "",
		skill2 = "",
		information3 = "受骸能腐化后开始向周边环境无差别发动攻击，奇怪的是它似乎并不会对智械产生敌意，反而依旧执行着曾经的维修指令。",
		type = 0,
		model_name = "2088_tpose",
		skill_desc6 = "",
		desc = "虚恒地区用于地面勘探的专用智械，负责维护云歌石稳定设施与收集遗失的物资。",
		race = 8,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "浮空型探索机器人，常见于各类重力稳定系统中，主要负责设备的硬件诊断与检修。",
		skill_desc1 = "短暂地释放激光，从近处向远处进行垂直扫射，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "集束射线",
		id = 2088,
		information2 = "为保护设施安全会对入侵者发动电能冲击予以警告。"
	},
	[2089] = {
		skill3 = "",
		skill2 = "",
		information3 = "在战斗中，比起正面冲突，他们更喜欢偷袭，在暗处用火铳对敌人进行攻击，因为火铳的子弹附着鹿神骸能，所以往往百发百中。",
		type = 0,
		model_name = "2089_tpose",
		skill_desc6 = "",
		desc = "身穿长袍，以兜帽遮面的邪教徒，口中时常低声念叨着神秘的祷文。",
		race = 6,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "这些狂信徒本是鹿家旧部，被蛊惑后暗中祭祀鹿神，为夺回鹿家旧权而协助鹿神苏醒。",
		skill_desc1 = "受到重伤后，狂信徒会举枪自尽，骸能子弹将穿透狂信徒的尸体并追踪飞向目标敌人位置，随后发生爆炸对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "殉命之枪",
		id = 2089,
		information2 = "他们暗中进行各项秘密活动，以下京区为据点笼络人心，传播教义。"
	},
	[2094] = {
		skill3 = "秋鹿根须",
		skill2 = "惑鸦啼鸣",
		information3 = "数年前，鸦神将计就计被伊邪那美等人斩杀，抛弃了自己的肉体，成为了仅存在于想象中不死不灭的模因怪物，只要人们再次燃起对它的恐惧，鸦神便会归来。",
		type = 2,
		model_name = "2094_tpose",
		skill_desc6 = "",
		desc = "曾经统治笹波的五大山神之一，于百年前被天之子·朗香封印，鸦越家族曾经的供奉对象。",
		race = 7,
		skill_desc2 = "在身后召唤出惑鸦幻影发出啼叫，对自身周遭的敌人造成伤害，并对其造成精神冲击，使其侵蚀值大幅增加。",
		skill4 = "空伪之扉",
		skill_desc5 = "",
		skill_desc3 = "在身后召唤出秋鹿幻影，在目标位置释放荆棘根须，对敌人造成伤害并且将其束缚。",
		skill5 = "",
		information1 = "一直潜伏在暗处控制鸦家，将历代鸦越家家主视作傀儡，玩弄于股掌之间。",
		skill_desc1 = "在身后召唤巨蛇之影，向目标发射骸能光束，对敌人造成伤害。",
		skill_desc4 = "鸦神召唤出数扇空伪之扉，将触碰到空伪之扉的敌人全数吸入幻境，在其中唤出惑鸦与敌人交战。",
		skill6 = "",
		skill1 = "杯弓蛇影",
		id = 2094,
		information2 = "比起正面作战，鸦神更喜欢用计谋与话语蛊惑对手，让敌人在不知不觉中落入它设下的陷阱。"
	},
	[2095] = {
		skill3 = "",
		skill2 = "破空斩",
		information3 = "只有承受住鸦神惑火，精神和肉体都没有崩溃的人才能在御刀众中保住地位，否则便会被作为无用之人而抛弃。",
		type = 0,
		model_name = "2095_tpose",
		skill_desc6 = "",
		desc = "他们对外自称是鸦家的护卫，头戴着乌鸦面具，佩刀从不离身。",
		race = 6,
		skill_desc2 = "向目标方向腾空跃起并劈出一道斩击，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "鸦神为挑选龙切的适格者，授意鸦越千堂秘密召集了一批试刀小队，这才是御刀众的真实身份。",
		skill_desc1 = "经过短暂蓄力后，向目标方向快速进行两次斩击，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "十字闪",
		id = 2095,
		information2 = "这些御刀众每周会在比武场进行排位比试，在战斗中他们不仅要与自己原本的伙伴搏杀，还要抵抗惑火的侵蚀。"
	},
	[2096] = {
		skill3 = "",
		skill2 = "炫目之光",
		information3 = "只有心智坚定，无所畏惧的人才能保证在面对这种视骸时获胜，但也只是暂时的，只要闯入者仍旧在尝试寻求真相，这些怪物就会源源不断地重生。",
		type = 0,
		model_name = "2096_tpose",
		skill_desc6 = "",
		desc = "被鸦神创造而出的异化种视骸，受其模因能力的影响，其外观糅合了众人的想象。",
		race = 7,
		skill_desc2 = "短暂蓄力后，向目标放出混乱光波，禁锢范围内的敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "常常群聚行动，但却并没有思维能力，更不会协同作战。",
		skill_desc1 = "经过短暂蓄力后，向前方直线区域发射骸能射线，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "霓虹射线",
		id = 2096,
		information2 = "其胸口的显示屏会映射出每个人心中梦魇的姿态，能够敏锐地探知敌人心理，对胆怯的敌人穷追猛打。"
	},
	[2104] = {
		skill3 = "",
		skill2 = "",
		information3 = "平时不是在寻找乐子，就是在小偷小摸和争抢地盘。",
		type = 0,
		model_name = "2104_tpose",
		skill_desc6 = "",
		desc = "夏什瓦特贫民窟帮派的成员，在贫民窟中随处可见。",
		race = 6,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "好勇斗狠是他们的常态，但见事不妙也会胆怯后退，组织能力一盘散沙。",
		skill_desc1 = "向前方进行滑铲，对命中敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "铲地扬沙",
		id = 2104,
		information2 = "虽然没有接受过系统的格斗训练，不过丰富的街头生存经验，让他们懂得怎么以最大力气挥出拳头，也能熟练地使出阴招。"
	},
	[2105] = {
		skill3 = "",
		skill2 = "",
		information3 = "虽然面临危险，但因为彼此之间缺少合作，无法组织起有效的抵抗。",
		type = 0,
		model_name = "2105_tpose",
		skill_desc6 = "",
		desc = "普渡制药视为耗材的试药人员，来自底层贫弱无人关注的家庭，即便消失了也不会引起注意。",
		race = 6,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "被希玛和罗波那以提供工作的名义抓来，成为药物的实验品。",
		skill_desc1 = "向前方直线区域进行滑铲，对命中的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "垂死挣扎",
		id = 2105,
		information2 = "生活在残酷的实验环境里，每天都有可能因为试药失去生命。"
	},
	[2113] = {
		skill3 = "",
		skill2 = "",
		information3 = "以长枪作为武器，精通阵法，进可攻退可守，即使成为傀儡，举手投足仍无愧精锐之名。",
		type = 0,
		model_name = "2113_tpose",
		skill_desc6 = "",
		desc = "身着禁军特有的尖盔利甲，在被控制成为锚点后，其头盔上便统一饰以蛾面，仿佛宣示着对天之子的忠诚。",
		race = 6,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "本该守卫笹波的皇城禁军。在遭到精神控制后开始攻击民众，并将平民感染为朗香的锚点。",
		skill_desc1 = "转身蓄力向目标突刺并横扫，若命中则再次蓄力，向目标发动突刺后跃起劈砍，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "舍身枪",
		id = 2113,
		information2 = "禁军的意义在于守卫皇城和天之子，是笹波所信赖的精锐，纪律森严、上达天听。"
	},
	[2114] = {
		skill3 = "虚数环灭",
		skill2 = "扇区崩毁",
		information3 = "通常以激光来进行组合攻击，经常集体行动并进行组合攻击，非常难缠。",
		type = 0,
		model_name = "2114_tpose",
		skill_desc6 = "",
		desc = "盖亚系统为防止自身算力被非法占用，启动的专用清除程式。",
		race = 8,
		skill_desc2 = "直接向正前方发射激光，并分别对左侧、右侧进行扫射，对扇形范围的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "境界清除者通过旋转进行蓄力，并保持旋转从身体两侧发射激光，构成以自身为中心的圆，对圆范围内的敌人进行扫射打击。",
		skill5 = "",
		information1 = "这种自律程式会自动检索盖亚系统中出现异常算力消耗的位置，并根据合法性判断条例，将非系统允许的各类数据、程式清除。",
		skill_desc1 = "短暂地蓄力并发射激光，向目标方向进行直线射击，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "集束穿刺",
		id = 2114,
		information2 = "它象征着盖亚世界的最底层的规则和秩序，是异常算力的“清道夫”。"
	},
	[2118] = {
		skill3 = "",
		skill2 = "",
		information3 = "如果遭遇塔骸请务必立即清除，以防止其打开源层裂缝。",
		type = 0,
		model_name = "2118_tpose",
		skill_desc6 = "",
		desc = "源层诞生的原始视骸之一，由最低等级的虫骸聚合而成，形似背负棱柱的虫类。",
		race = 7,
		skill_desc2 = "",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "据观察没有思维能力，也不具备攻击与快速移动的手段，个体威胁程度较低。",
		skill_desc1 = "如果处于移动状态，塔骸将展开固定脚进入「驻守」模式；如果处于「驻守」模式，塔骸将收起骸能核心进入移动状态。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "模式切换",
		id = 2118,
		information2 = "但该种类视骸拥有打开源层通道的特殊权限，且通常产生于视骸聚集区，是视骸入侵表层的主要手段。"
	},
	[3004] = {
		skill3 = "灵刀·扶风",
		skill2 = "灵刀·碎月",
		information3 = "同时拥有可怕的智慧谋略，能从不同角度发动进攻，攻击方式隐蔽而诡异，防不胜防。",
		type = 1,
		model_name = "3004_tpose",
		skill_desc6 = "",
		desc = "一头银发的剑术高手。",
		race = 7,
		skill_desc2 = "少纳言向后急退，并释放出两道交叉的刀气回击敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "少纳言召唤两把灵刀，释放二刀流剑法攻击敌人。",
		skill5 = "",
		information1 = "本名竹中广元，辅佐宫蛇秀的家臣，为了秀的复仇理想选择贯彻自己的忠义，自愿与视骸结合。",
		skill_desc1 = "少纳言召唤一把灵刀，挥动灵刀制造刀气风暴。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "灵刀·盈华",
		id = 3004,
		information2 = "身体经过视骸化改造后凭借惊人的意志，保留了全部的思维能力和语言能力。\n能够通过一对特殊的游离义手使用复数灵刀，精湛、猛烈的剑法让敌人难以招架。"
	},
	[3005] = {
		skill3 = "武装进化",
		skill2 = "定点闪击",
		information3 = "集体行动时相当有秩序感，甚至连攻击的动作都十分整齐。",
		type = 1,
		model_name = "3005_tpose",
		skill_desc6 = "",
		desc = "高大的外形，拟人化的结构，拥有不俗的机动性。",
		race = 8,
		skill_desc2 = "蓄力后向前冲刺。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "进入强化模式，加快技能速度，缩短攻击间隔。",
		skill5 = "",
		information1 = "降低了装甲抗性和火力，同时减少了能耗，在攻占城市的大型战争中更具有战略意义。",
		skill_desc1 = "启动喷气推进装置冲向目标，用尖锐的武器挑飞敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "强袭作战",
		id = 3005,
		information2 = "在抛弃了部分重火力装备的前提下，同时又为高机动性采用了先进的人型构造，压缩了材料成本和生产时间，由此具备了量产化的条件。"
	},
	[3006] = {
		skill3 = "聚力护盾",
		skill2 = "破阵冲刺",
		information3 = "据说这种相互组合的方式来自于一种遥远文明的科技，至少设计出这三种基础智械的智械师们，在当时可从未想象过它们可以有这种形态。",
		type = 1,
		model_name = "3006_tpose",
		skill_desc6 = "",
		desc = "组合型智械，通过协同合作极大地提升了战斗力。",
		race = 8,
		skill_desc2 = "蓄力向前进行远距离冲刺。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "切换为防御姿态，升起护盾抵挡攻击。",
		skill5 = "",
		information1 = "之前单独作战时都不太强的三种基础智械，在组合完成后发生了质的变化。",
		skill_desc1 = "跃起后砸向地面，释放锯臂展开高速旋转攻击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "裂地轰击",
		id = 3006,
		information2 = "叉车的机动性，电锯的近距离作战能力，还有焊枪的远距离输出能力完美地体现在了这一组合体上。"
	},
	[3007] = {
		skill3 = "无情驱逐",
		skill2 = "大地震颤",
		information3 = "如今，忠心的大将依然镇守着宫蛇家的大门，只是这里早就没有了他想守护的事物。",
		type = 1,
		model_name = "3007_tpose",
		skill_desc6 = "",
		desc = "体型庞大的重甲武士，拥有极高的防御力。",
		race = 7,
		skill_desc2 = "右近卫挥动巨剑向下劈击，其威力之巨大连地面都足以震裂。",
		skill4 = "狂噬",
		skill_desc5 = "右近卫召唤盾墙，抵挡前方敌人的伤害，盾墙随着时间的推移逐步瓦解转化为剧烈波动的骸能，最终引发大范围爆炸。",
		skill_desc3 = "右近卫蓄力后冲刺至敌人身前，挥动武器横扫敌人。",
		skill5 = "金城之御",
		information1 = "本名直江长实，从宫蛇秀的父辈时期便一直侍奉宫蛇家的护卫队长，对宫蛇家有极深的感情。",
		skill_desc1 = "右近卫重重踏向地面，召唤出两只骸犬攻击敌人。",
		skill_desc4 = "右近卫吞噬一条骸犬，强化自身能力，进入“狂噬”状态，该状态下可释放额外技能。\n狂噬·破阵：右近卫蓄力后挥动武器大范围横扫敌人。\n狂噬·追击：右近卫挥动武器向前进行四次横扫，最后砸击地面。\n狂噬·地陷：右近卫挥动武器砸击地面，对前方的敌人造成两次范围攻击。\n狂噬·突围：右近卫闪现至敌人附近，挥动武器横扫攻击敌人。",
		skill6 = "",
		skill1 = "忠诚侍从",
		id = 3007,
		information2 = "同样接受了视骸化的改造，但因为过于强烈的情绪波动，失去了大部分的思考和语言能力。\n相较于一般人形视骸身材更为高大魁梧，挥舞重剑、使役恶犬视骸的作战方式宛若修罗。"
	},
	[3008] = {
		skill3 = "热血咆哮",
		skill2 = "快速斩",
		information3 = "不过在遇到伊森之后，被彻底击败的他却重新看到了希望。他开始称呼伊森为大哥，并坚信伊森能带领迷铁之家走出困境。",
		type = 1,
		model_name = "3008_tpose",
		skill_desc6 = "",
		desc = "性格散漫的青年，战斗时常常使出让人意想不到的攻击手段。",
		race = 6,
		skill_desc2 = "奥利海姆原地发动三次斩击，对附近的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "奥利海姆热血沸腾，攻击力提升。",
		skill5 = "",
		information1 = "迷铁之家的创始人兼前任领袖，虽说是领袖，其实不过是混混老大而已。",
		skill_desc1 = "奥利海姆挥舞双刀，高速旋转攻击敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "极限旋斩",
		id = 3008,
		information2 = "他意外得知了科尔盖一直打压罗斯塔赫的真相，并决心带领深受贫苦摧残的同伴们向科尔盖夺回属于罗斯塔赫的东西，然而市井出身的迷铁之家根本无法与科尔盖的武装力量抗衡，他制定的计划接连失败。"
	},
	[3009] = {
		skill3 = "锋刃掠影",
		skill2 = "试探敌情",
		information3 = "行动能力很强，擅长制作各式各样的陷阱，与其对战需要留意脚下。",
		type = 1,
		model_name = "3009_tpose",
		skill_desc6 = "",
		desc = "冷酷的女性刺客，擅长隐匿身形作战。",
		race = 6,
		skill_desc2 = "零一快速闪现至敌人身边发动一次攻击，结束后立刻闪身脱离战场，回到安全的位置。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "零一发射两波利刃攻击，对沿途的敌人造成伤害。",
		skill5 = "",
		information1 = "不知真名，只有代号的神秘女性，和奥利海姆同为迷铁之家的二把手。",
		skill_desc1 = "零一投出两把匕首攻击前方的敌人，匕首在落地后爆炸并造成更大的伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "回转利刃",
		id = 3009,
		information2 = "和伊森一样成为了被改造的人，并且被清除了之前全部的记忆，因为伊森的许诺留在迷铁之家。"
	},
	[3010] = {
		skill3 = "突破敌阵",
		skill2 = "清场专家",
		information3 = "其强壮的身体素质外加上精英标配的重型装甲，令「高墙」可以在单兵作战中具备极强的战斗力，同时也可以是自己团队中的强大护盾。",
		type = 1,
		model_name = "3010_tpose",
		skill_desc6 = "",
		desc = "高达两米的重型武装安保，战力强大。",
		race = 6,
		skill_desc2 = "高墙掷出爆弹，对前方的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "高墙进入扫射模式，向左、右和前方持续扫射攻击。",
		skill5 = "",
		information1 = "迷铁安保中的成员大致是从前身的「迷铁之家」公会中直接选调而出的，其中最优秀、最强壮的成员会由伊森亲自任命为小队长，并赋予他们「高墙」的称号。",
		skill_desc1 = "高墙跳跃至敌人附近造成范围伤害，随后开启喷火的重型武器攻击前方的敌人。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "重装烈焰",
		id = 3010,
		information2 = "每一位「高墙」都领导着一支数人编制的安保小队，虽然作战素养参差不齐，但彼此间的团结性是毋庸置疑的。"
	},
	[3012] = {
		skill3 = "幻影",
		skill2 = "覆灭",
		information3 = "危险程度相当高，因此被归类为聚合种，与之交战需要多加注意。",
		type = 1,
		model_name = "3012_tpose",
		skill_desc6 = "",
		desc = "游刃有余地穿梭于战场，指挥自己的幻影分身发动进攻。",
		race = 7,
		skill_desc2 = "幻骸瞬移至敌人附近，通过高速旋转羽翼持续造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "幻骸释放出幻影分身，干扰敌人的判断。召唤出的幻影将遵从自己的战斗本能对敌人发动进攻。",
		skill5 = "",
		information1 = "由一定数量的侵蚀种聚集后诞生的个体，观测到的数量相对有限。",
		skill_desc1 = "幻骸向敌人发射羽翼标记，羽翼标记会对周围的敌人造成伤害并持续存在。当场上存在六枚羽翼时，幻骸将一次性收回所有羽翼，并对回收轨迹上的所有敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "裁断",
		id = 3012,
		information2 = "会幻化出分身发动诡异的能量攻击，可以在战术方面进行简单的思考。"
	},
	[3013] = {
		skill3 = "绝岩·破",
		skill2 = "绝岩·撼",
		information3 = "沉重的攻击也相当的有破坏力，虽然行动迟缓，但危险程度并不亚于巨化种视骸。",
		type = 1,
		model_name = "3013_tpose",
		skill_desc6 = "",
		desc = "黑英岩石被视骸侵蚀后的产物，浑身包覆着坚硬的岩块。",
		race = 7,
		skill_desc2 = "黑英蓄力后三连砸击地面，对前方的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "黑英跳跃至敌人附近砸击地面，造成范围伤害。",
		skill5 = "",
		information1 = "不具备任何思维能力，被归类为地缚种。",
		skill_desc1 = "黑英蓄力后横扫敌人，对近距离的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "绝岩·崩",
		id = 3013,
		information2 = "身躯非常坚硬，且拥有再生能力，可以通过吸收岩石恢复肢体的残缺。"
	},
	[3014] = {
		skill3 = "画韵·银勾",
		skill2 = "画韵·桎梏",
		information3 = "没人知道他疯癫表现背后的真意，或许只有在画中世界与之一战，才有机会真正了解他。",
		type = 1,
		model_name = "3014_tpose",
		skill_desc6 = "",
		desc = "神色庄严，挥舞画笔战斗的视骸画师。",
		race = 7,
		skill_desc2 = "画师挥动左臂，朝敌人释放跟踪陷阱。若敌人没有在陷阱爆炸前成功闪避，则对敌人造成伤害并禁锢敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "画师挥动左臂，对前方的敌人造成二连戳刺攻击，然后释放地刺击飞敌人。",
		skill5 = "",
		information1 = "以前四处云游的僧人，因为画技高超，接受了宫蛇家的邀请成为了门客画师。\n但四年前的火灾不仅夺走了他的右臂，也夺走了宫蛇家平静安宁的生活。",
		skill_desc1 = "画师伸展左臂，聚集骸能召唤出一只视骸协助自己战斗。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "画韵·妙手",
		id = 3014,
		information2 = "曾一度拒绝改造的画师，如今却用这副视骸的身躯，不断地绘制一幕幕往昔的画面。"
	},
	[3016] = {
		skill3 = "跳跃追击",
		skill2 = "高频音爆",
		information3 = "虽然数量并不多，但复数蠊骸同时攻击可以做到撕开位面通道。",
		type = 1,
		model_name = "3016_tpose",
		skill_desc6 = "",
		desc = "由蚁骸与翼骸结合后诞生的源初种视骸。",
		race = 7,
		skill_desc2 = "蠊骸朝敌人的方向释放出高频音波攻击，音波结束后，蠊骸挥动前爪发动小范围的爪击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "蠊骸高高跃起，砸向敌人所处的位置，造成一定范围的伤害。",
		skill5 = "",
		information1 = "破坏欲望和攻击手段更强。",
		skill_desc1 = "蠊骸高速转动身体，对周围的敌人造成伤害后，在自己的附近召唤出两只蚁骸、两只翼骸。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "骸影增殖",
		id = 3016,
		information2 = "拥有强于翼骸的飞行能力，具备高机动性的同时会用强力的钩爪破坏视线内的所有存在。"
	},
	[3017] = {
		skill3 = "忠勇烙印",
		skill2 = "至暗伏击",
		information3 = "使用两把太刀作为武器，对于入侵者绝不会手下留情。",
		type = 1,
		model_name = "3017_tpose",
		skill_desc6 = "",
		desc = "出现在宫蛇家的人形视骸，进攻灵巧迅速，必须小心提防。",
		race = 7,
		skill_desc2 = "兵部卿蹲守于暗处伺机而动，趁敌不备时移至对方身前发动快速的二连攻击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "兵部卿聚力后向前释放出两道交叉的剑气，对远距离的敌人也能造成伤害。",
		skill5 = "",
		information1 = "由于技术的逐渐成熟，结合后依旧保留了大部分的思维能力。",
		skill_desc1 = "兵部卿挥动武器发动十字斩击，清扫战场上的阻碍。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "清扫战场",
		id = 3017,
		information2 = "生前作为宫蛇家的守卫，即便是视骸化的现在也忠心地保护着宫蛇家的安全。"
	},
	[3019] = {
		skill3 = "审判",
		skill2 = "巡游",
		information3 = "危险程度相当高，因此被归类为聚合种，与之交战需要多加注意。",
		type = 1,
		model_name = "3019_tpose",
		skill_desc6 = "",
		desc = "手持大剑与盾牌，攻守兼备的强力敌人。",
		race = 7,
		skill_desc2 = "战骸闪现至敌人附近发动强力攻击，并在原来所处的位置留下可以随时返回的标记光剑。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "当场上存在三把标记光剑后，战骸会再召唤两把，然后向敌人发射全部光剑，对远距离的敌人也能造成伤害。",
		skill5 = "",
		information1 = "由一定数量的侵蚀种聚集后诞生的个体，观测到的数量相对有限。",
		skill_desc1 = "战骸蓄力向前挥舞重剑，使出中距离突刺攻击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "威压",
		id = 3019,
		information2 = "会使用大型的剑盾进行有力的攻防，可以在战术方面进行简单的思考。"
	},
	[3020] = {
		skill3 = "怒焰追击",
		skill2 = "重锤驱逐",
		information3 = "该系列智械目前被安置在学院门口，以及一些重要物品的保管室前，其散发出的强大威慑力让宵小之辈不敢靠近。",
		type = 1,
		model_name = "3020_tpose",
		skill_desc6 = "",
		desc = "身材健硕高大的安保智械，威慑力十足、如同巨型雕塑般的外表受到了铃兰团成员的一致好评。",
		race = 8,
		skill_desc2 = "高举巨斧，重重地锤击地面，第二次锤击时发射一道能够追击敌人的冲击波，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "高举巨斧，发射三道追踪敌人的冲击波，对敌人造成伤害。",
		skill5 = "",
		information1 = "为了减轻铃兰团的安保压力，千星学院决定发展自己的力量，经过一年的联合研究，开发出一系列优秀的智械，其中就包括集力量、科技与艺术为一体的“弥诺陶洛斯”。",
		skill_desc1 = "高举巨斧，向着敌人的方向发起冲锋，并对沿途的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "巨像冲锋",
		id = 3020,
		information2 = "千万别被它看似笨重的外形所欺骗，强化的动力系统使得它的动作比一般的智械更为灵活。"
	},
	[3021] = {
		skill3 = "净化推进",
		skill2 = "异空移形",
		information3 = "拥有可以理解指令的智慧，在图灵的安排下协助奥蒂斯不断进行寻找坐标的实验。",
		type = 1,
		model_name = "3021_tpose",
		skill_desc6 = "",
		desc = "特殊的侵蚀种视骸，灵魂补完计划的失败产物，被坐标排斥后灵魂与记忆被图灵的骸能污染而成。",
		race = 7,
		skill_desc2 = "闪现至敌人附近，对敌人发动二连攻击。",
		skill4 = "死寂之境",
		skill_desc5 = "",
		skill_desc3 = "向目标方向疾速突进，对沿途的敌人造成伤害。",
		skill5 = "",
		information1 = "能够提炼出精纯的骸能作为自己的驱动力，颜色上也展现出高纯度的特性。",
		skill_desc1 = "挥舞双刀对敌人发动二连攻击。",
		skill_desc4 = "凝聚高纯度的能量球向敌人发射，能量球炸开并形成减速场限制敌人的行动。",
		skill6 = "",
		skill1 = "极致放逐",
		id = 3021,
		information2 = "会使用双刀进行进攻，能力包括但不限于闪现以及能量形态的转变，与之前的侵蚀种有较大的差别。"
	},
	[3022] = {
		skill3 = "感官封闭",
		skill2 = "震荡波流",
		information3 = "拥有可以理解指令的智慧，在图灵的安排下协助奥蒂斯不断进行寻找坐标的实验。",
		type = 1,
		model_name = "3022_tpose",
		skill_desc6 = "",
		desc = "特殊的侵蚀种视骸，灵魂补完计划的失败产物，被坐标排斥后灵魂与记忆被图灵的骸能污染而成。",
		race = 7,
		skill_desc2 = "从敌人脚下召唤出圆形的震荡波，击飞范围内的敌人。",
		skill4 = "聚能黑星",
		skill_desc5 = "",
		skill_desc3 = "从敌人脚下召唤出高能矩阵，迅速扩散的矩阵将形成一片减速场限制敌人的行动。",
		skill5 = "",
		information1 = "能够提炼出精纯的骸能作为自己的驱动力，颜色上也展现出高纯度的特性。",
		skill_desc1 = "召唤三枚能量体向敌人发射，对远距离的敌人造成伤害。",
		skill_desc4 = "闪现至敌人身边，并在前方成两枚能量球，能量球爆炸后会使被命中的敌人陷入混乱状态。",
		skill6 = "",
		skill1 = "念力狙击",
		id = 3022,
		information2 = "会使用念力进行远距离攻击，能力包括但不限于隐身以及瞬移，与之前的侵蚀种有较大的差别。"
	},
	[3023] = {
		skill3 = "幽秽泥沼",
		skill2 = "魇影突刺",
		information3 = "能够熟练地使用遗迹的能量，思维能力也有了进一步的提升，威胁巨大。觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 1,
		model_name = "3023_tpose",
		skill_desc6 = "",
		desc = "包裹在腐秽中的变异聚合种，释放出强烈而污浊的骸能，侵蚀敌人的意志。",
		race = 7,
		skill_desc2 = "迅猛地向前突刺，对远距离的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "释放双翼刺入脚下的地面，造成冲击伤害，且当自身血量较低时，对敌人附加持续一定时间的受创效果。若未能命中敌人，便从泥沼中召唤出随从攻击敌人。",
		skill5 = "",
		information1 = "圣树遗迹中出现的变种视骸个体，因为神域遗迹的能量发生异变。",
		skill_desc1 = "向前方扇形范围释放六颗飞弹，对范围内的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "侵蚀飞弹",
		id = 3023,
		information2 = "由一定数量的遗迹侵蚀种聚集后形成，拥有神域侵蚀种的绝对指挥权。全身沾染着被污浊的液体，成为腐蚀巨树的，恶意的代行者。"
	},
	[3024] = {
		skill3 = "血意",
		skill2 = "荆棘",
		information3 = "能够熟练地使用遗迹的能量，思维能力也有了进一步的提升，威胁巨大。觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 1,
		model_name = "3024_tpose",
		skill_desc6 = "",
		desc = "沐浴在绯红血色中的变异聚合体，蕴含着危险的憎恶与杀意，宛若游走在暗夜中的骇人恶灵。",
		race = 7,
		skill_desc2 = "凝聚大量骸能，在目标脚下召唤出尖锐的地刺，强化状态下地刺的影响范围将增大。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "当生命值低于一定比例时，自身进入强化状态，增强其他技能的效果。",
		skill5 = "",
		information1 = "真樱遗迹中出现的变种视骸个体，因为神域遗迹的能量发生异变。",
		skill_desc1 = "张开双翼，向周围散落蕴含着爆裂骸能的符咒，强化状态下散落符咒数量加倍。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "落樱",
		id = 3024,
		information2 = "由一定数量的遗迹侵蚀种聚集后形成，拥有神域侵蚀种的绝对指挥权。隐藏在绯红面纱下的视线饱含杀意，是游走在源层中的恶灵。"
	},
	[3025] = {
		skill3 = "",
		skill2 = "爆裂水弹",
		information3 = "能够熟练地使用遗迹的能量，思维能力也有了进一步的提升，威胁巨大。觊觎契物的共鸣之力聚集于此，是修正者探索神域遗迹的最大阻碍。",
		type = 1,
		model_name = "3025_tpose",
		skill_desc6 = "",
		desc = "身形灵巧的变异聚合种，操纵激流对敌人发动无孔不入的攻击，是个相当棘手的存在。",
		race = 7,
		skill_desc2 = "向目标发射水弹，若水弹未命中，则会在地面停留一段时间，待敌人靠近时立刻爆裂并造成伤害。若一定时间内没有敌人出现在附近，则自动爆裂消失。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "奥山遗迹中出现的变种视骸个体，因为神域遗迹的能量发生异变。",
		skill_desc1 = "跃起并聚集能量向目标脚下发动砸击，能量爆破后形成冲天激流，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "激流冲击",
		id = 3025,
		information2 = "由一定数量的遗迹侵蚀种聚集后形成，拥有神域侵蚀种的绝对指挥权。白骨最终化为垩土，象征着生命的终结，永恒的消逝。"
	},
	[3028] = {
		skill3 = "高效清扫",
		skill2 = "女仆的惩罚",
		information3 = "谨慎、果决的明塔不遗余力地排除一切可能扰乱协会秩序的因素，对试图进犯协会的敌人绝不手软，唯有面对俄尼里伊时才展露出难得的温柔一面。",
		type = 1,
		model_name = "3028_tpose",
		skill_desc6 = "",
		desc = "哈迪斯最得意的人偶作品，在神力的驱动下即使哈迪斯不在身边也可自由活动，且拥有一定的知识储备与思维能力。",
		race = 6,
		skill_desc2 = "明塔跃起后践踏地面，向前方较大扇形范围挥出重拳，用凌厉的拳风对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "明塔在琉刻的帮助下高速飞向目标，对目标使出连续冲拳，驱赶扰乱缪斯协会秩序的妨碍者。",
		skill5 = "",
		information1 = "战斗时在哈迪斯的操控下用手部强力的武装为敌人带去最深的绝望，平时作为缪斯协会的女仆，负责照顾协会成员们的起居和饮食。",
		skill_desc1 = "明塔高高跃起并朝着地面挥出重拳，巨大的冲击波呈环形扩散开来，对范围内的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "女仆的威慑",
		id = 3028,
		information2 = "闲暇时刻，两位女仆徜徉在缪斯协会内的私人图书馆中，学习与人类有关的知识。"
	},
	[3029] = {
		skill3 = "送客之道",
		skill2 = "女仆的裁定",
		information3 = "迅捷、机敏的琉刻在战斗中无往不胜，同时也将缪斯协会的上下事务打理得井井有条，只有在偶尔面对某种黑色小生物时，会激发出一股似乎不该属于人偶的异样情绪。",
		type = 1,
		model_name = "3029_tpose",
		skill_desc6 = "",
		desc = "哈迪斯最得意的人偶作品，在神力的驱动下即使哈迪斯不在身边也可自由活动，且拥有一定的知识储备与思维能力。",
		race = 6,
		skill_desc2 = "琉刻高高跃起，向前方敌人使出多段劈砍攻击，随后灵巧地飞旋并用凌厉的刀锋对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "琉刻在明塔的帮助下高速飞向目标，对目标使出横扫攻击，并掷出高速旋转的飞刀对敌人造成伤害。",
		skill5 = "",
		information1 = "战斗时在哈迪斯的操控下用手部强力的武装为敌人带去最深的绝望，平时作为缪斯协会的女仆，负责照顾协会成员们的起居和饮食。",
		skill_desc1 = "琉刻释放出一道不断向自身收缩的能量波，侦查范围内一切异动，任何触碰到能量波的敌人都将受到伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "女仆的侦查",
		id = 3029,
		information2 = "闲暇时刻，两位女仆徜徉在缪斯协会内的私人图书馆中，学习与人类有关的知识。"
	},
	[3031] = {
		skill3 = "幻影攻袭",
		skill2 = "星幕屏障",
		information3 = "与优雅的外表截然相反，进攻方式变化多端，且具有强大的破坏力。",
		type = 1,
		model_name = "3031_tpose",
		skill_desc6 = "",
		desc = "千星学院为庆典所研制的智械，用于在庆典节目上歌唱和伴舞，期盼着它能将庆典推上高潮。",
		race = 8,
		skill_desc2 = "伴舞者撑起洋伞，在身前张开能量屏障，抵御该方向上目标造成的数次伤害。",
		skill4 = "谢场表演",
		skill_desc5 = "",
		skill_desc3 = "伴舞者向前抛出洋伞，并闪身至敌人身侧挥剑攻击，对敌人造成伤害。",
		skill5 = "",
		information1 = "舞姿优雅迷人，轻盈地穿梭在舞台上，给观众带来视觉上的享受。",
		skill_desc1 = "伴舞者转动洋伞，向周围发射一道强力的射线，留下的轨迹在片刻后爆炸，对周围的敌人造成伤害。",
		skill_desc4 = "伴舞者挥动洋伞刺向敌人，当击中目标时，对敌人造成击退的效果；若未击中敌人，则迅速回到原本的姿态，不被敌人抓到一丝破绽。",
		skill6 = "",
		skill1 = "灼星之舞",
		id = 3031,
		information2 = "研究者花费了大量的时间为其设计舞姿，谱写专属的歌曲，然而这一切都因诺维赫的阴谋毁于一旦。"
	},
	[3032] = {
		skill3 = "迅式·闪",
		skill2 = "冲式·碎",
		information3 = "现如今已经很少能在擂台中看见他的身影，只接受真正强者的挑战。",
		type = 1,
		model_name = "3032_tpose",
		skill_desc6 = "",
		desc = "来自夏什瓦特的男性流浪拳手，传闻曾经因在地下拳场的比赛中失利而欠下巨款，为逃避债务才来到罗斯塔赫。",
		race = 6,
		skill_desc2 = "降低重心，以极快的速度向目标冲锋，随后打出足以粉碎巨石的重拳。",
		skill4 = "燕式·回",
		skill_desc5 = "",
		skill_desc3 = "以极快的速度施展拳手的步伐，在近身搏斗中用不可思议的速度躲避攻击。",
		skill5 = "",
		information1 = "为了生计，只能放下自己曾经作为武者的尊严，沦为一名只听从金钱召唤的雇佣打手。",
		skill_desc1 = "短暂蓄力后高高跃起，随后向目标发动有力的劈腿，犹如战斧劈砍。",
		skill_desc4 = "短暂蓄力后，对目标发动有力的上挑踢击，其姿宛如回身之燕。",
		skill6 = "",
		skill1 = "斧式·戮",
		id = 3032,
		information2 = "在罗斯塔赫的擂台中战无不胜，被称为「擂台王」，以凶悍的拳风著称。"
	},
	[3033] = {
		skill3 = "",
		skill2 = "移动飞弹",
		information3 = "武装相对来说比较旧式，存在一定的局限性，但并不妨碍量产后带来的威慑力。",
		type = 1,
		model_name = "3033_tpose",
		skill_desc6 = "",
		desc = "由伊森等人通过从工厂获得的技术资料改造修复的轻型双足战场装甲，能够通过遥控操作与自律作战。",
		race = 8,
		skill_desc2 = "短暂变形动作后，进入高速战车模式，对目标连续发动飞弹射击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "本机型搭载了智能火控系统，极高的命中率与强劲的火力使得这款智械在迷铁之家的一般成员中大受欢迎。",
		skill_desc1 = "短暂变形动作后，进入固定炮台模式，对前方扇形区域进行扫射。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "环形扫射",
		id = 3033,
		information2 = "虽然早期系统只能进行简单的自律作战， 但在完成AI核心的加载后能够以更灵活的自律模式进行战斗。"
	},
	[3035] = {
		skill3 = "无言的告诫",
		skill2 = "勇者的考验",
		information3 = "复杂的情绪驱使他在比赛中做出了不诚实的行为，与他一直以来所坚守的骑士精神背道而驰。",
		type = 1,
		model_name = "3035_tpose",
		skill_desc6 = "",
		desc = "铃兰骑士团的资深骑士，雅典娜的义兄。自幼接受严苛的骑士训练，以能够继承帕拉斯家族的骑士传统为荣。",
		race = 6,
		skill_desc2 = "阿尔戈手持长剑，飞速向前旋转并攻击沿途的敌人，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "阿尔戈向前冲刺，短暂隐匿身形后移动至敌人附近出现，向敌人脚下掷出长剑造成范围伤害。",
		skill5 = "",
		information1 = "十年如一日地坚持练习，使阿尔戈熟练掌握了一名优秀的骑士应有的技巧。他渴望着获得更为卓著的功勋。",
		skill_desc1 = "阿尔戈跃起并向前释放一道凌厉的交叉剑气，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "骑士的见面礼",
		id = 3035,
		information2 = "作为注视着雅典娜走上骑士道路的见证人，他难以想象这柄稚嫩的锋刃终有一天会残酷地刺破自己的野心。"
	},
	[3036] = {
		skill3 = "狂龙之势",
		skill2 = "追踪光弹",
		information3 = "擅长使用高温火焰、激光与物理手段结合的攻击方式，行动模型智能化程度高，需要谨慎应对。",
		type = 1,
		model_name = "3036_tpose",
		skill_desc6 = "",
		desc = "静督山曾经的主人所制造的智械，用于保护静督山中的工坊不受视骸攻击。",
		race = 8,
		skill_desc2 = "残炎守卫释放扩散性侦测领域，并朝领域内锁定内的敌人发射激光弹进行攻击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "残炎守卫利用自身模块化武器结构，对目标敌人使出包裹高温火焰的三连击，造成连续伤害。",
		skill5 = "",
		information1 = "有着高度一体化结构的异形守卫，由高纯度的云歌石晶体核心驱动悬浮，拥有强大的战斗力，能够应对多种突发事件。",
		skill_desc1 = "残炎守卫从口中喷出高温火柱并砸向地面，对前方敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "残炎之息",
		id = 3036,
		information2 = "由于常年缺乏修缮和维护，行动力有所下降，可能存在身份识别误差、对一切目标无差别攻击的情况。"
	},
	[3039] = {
		skill3 = "幽兰落",
		skill2 = "弧光舞",
		information3 = "其形如绽花，其势如细雨。其刃之秘，宛若幽境玄兰。",
		type = 1,
		model_name = "3039_tpose",
		skill_desc6 = "",
		desc = "受骸能影响初具人形的聚合种视骸，手化爪刃，镇守山间。",
		race = 7,
		skill_desc2 = "短暂蓄力后，回旋身躯发动优雅的旋击，对范围内的敌人造成伤害",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "跃至空中，随后发动高速斩击，并在命中地面时引发爆炸，对接触到的敌人造成伤害。",
		skill5 = "",
		information1 = "聚集了大量侵蚀种形成的视骸个体，战斗水平极高。身手灵活，优雅无比。",
		skill_desc1 = "挑起爪刃，凝聚骸能发动幻刺攻击，对前方敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "幻形刺",
		id = 3039,
		information2 = "通常会于虚恒地面的群山中出现，像是为了守护领地一般攻击所有来犯之人。"
	},
	[3040] = {
		skill3 = "斩剑式",
		skill2 = "踏剑式",
		information3 = "其形如枯木，其势如疾风。其剑之利，宛若傲骨苍梅。",
		type = 1,
		model_name = "3040_tpose",
		skill_desc6 = "",
		desc = "受骸能影响初具人形的聚合种视骸，手执利剑，把守山门。",
		race = 7,
		skill_desc2 = "短暂蓄力后，垫步向前发动强力的斩击，对前方敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "双剑交叉挥动，将凝聚的骸能以剑气形式斩出，对接触到的敌人造成伤害。",
		skill5 = "",
		information1 = "聚集了大量侵蚀种形成的视骸个体，战斗水平极高。身手灵活，剑技多变。",
		skill_desc1 = "高举利剑，凝聚骸能发动御剑攻击，对锁定的敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "御剑式",
		id = 3040,
		information2 = "通常会于虚恒地面的群山中出现，像是为了守护领地一般攻击所有来犯之人。"
	},
	[3041] = {
		skill3 = "蚀骨丧歌",
		skill2 = "烈性风场",
		information3 = "疾苦根源擅长进行毒性攻击，通过附着性的鳞粉造成持续性的伤害和影响。在没有特殊应对手段的情况下，建议慎重迎战。",
		type = 1,
		model_name = "3041_tpose",
		skill_desc6 = "",
		desc = "被某种未知力量创造出的特殊异化种视骸，拥有着近似于人类的形体和特殊的大型肢体关节，翅膀具有极强的毒性与破坏力。",
		race = 7,
		skill_desc2 = "疾苦根源挥动翅膀，在周身形成强大的风场，对接近的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "疾苦根源扎根在地面，向周围散发出大范围的毒性爆炸。",
		skill5 = "",
		information1 = "疾苦根源是从深源层中提取骸能，被某种未知力量尝试创造出的新型视骸物种，是某种模仿人类生命的「造物」之一。",
		skill_desc1 = "疾苦根源煽动翅膀，凝聚出毒性的鳞粉炸弹，对前方目标进行攻击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "鳞粉炸弹",
		id = 3041,
		information2 = "根据战斗报告，该目标具有强烈的攻击欲望，作为特殊智种视骸的护卫者身份，出现在危机爆发地区。"
	},
	[3042] = {
		skill3 = "终焉螺旋",
		skill2 = "深渊余烬",
		information3 = "封印加姆的微型隔离沙箱处于座钟中，到达指定时间后，加姆会被释放，操纵黑炎焚尽一切。",
		type = 1,
		model_name = "3042_tpose",
		skill_desc6 = "",
		desc = "百年前诞生的类犬型视骸，全身散发黑炎，头部拥有四个面，唾液接触任意数据后会化为永不熄灭的火焰。",
		race = 7,
		skill_desc2 = "加姆翻滚两次，向四周释放灰烬，最后燃烧灰烬。",
		skill4 = "天火坠落",
		skill_desc5 = "加姆两侧的头部张口喷射火焰，焚烧敌人。",
		skill_desc3 = "加姆向前突进，呈螺旋旋转状冲刺。",
		skill5 = "炼狱狂焰",
		information1 = "曾被当地修正者围剿，战斗过程中展现其压倒性实力。最终，当地修正者以全小队牺牲为代价将其封印在微型隔离沙箱中，致其腿部瘫痪萎缩，只能依靠前肢拖动下半身行动。",
		skill_desc1 = "加姆摆动尾巴，横扫一周。",
		skill_desc4 = "加姆张口向高空释放两个火球，再俯首释放一个水平发射的火球。",
		skill6 = "",
		skill1 = "死亡横扫",
		id = 3042,
		information2 = "机缘巧合之下，加姆被葛朗台·塔列朗发现，并在塔列朗前任家主操劳过度不幸离世后，被葛朗台·塔列朗用于清除威胁到自己与塔列朗家族利益的对手。"
	},
	[3046] = {
		skill3 = "断骨飞刺",
		skill2 = "骨刃三斩",
		information3 = "除了具备近身战能力以外，体内也装备着远程武器，能够适应不同距离的战斗。",
		type = 1,
		model_name = "3046_tpose",
		skill_desc6 = "",
		desc = "融合了机械和生物科技的改造人，被希玛命名为「复仇之拳」，承载着她复仇的怒火。",
		race = 6,
		skill_desc2 = "向前方做出三次斩击，对敌人造成伤害。",
		skill4 = "复仇擒抱",
		skill_desc5 = "",
		skill_desc3 = "将爪子插入地面，从背上向天空发射三枚骨刺，对敌人造成伤害。",
		skill5 = "",
		information1 = "使用大量格斗家数据集成的战斗程序，替代了自身原本用于思考的意识。",
		skill_desc1 = "蓄力之后，向地面砸击，对圆形范围内的敌人造成伤害。",
		skill_desc4 = "向前方猛扑，对敌人造成伤害。",
		skill6 = "",
		skill1 = "刺地重击",
		id = 3046,
		information2 = "既有基因编译技术的强化，又经受机械改造，从而获得了超越人类极限的身体能力。"
	},
	[3044] = {
		skill3 = "鹿神之威",
		skill2 = "骸火喷涌",
		information3 = "他们通常不会亲自下场作战，而是躲在远处负责指挥，必要时也会运用鹿神旗帜中的骸能施展法术攻击敌人，一旦战况不利，就会尝试在其他狂信徒的掩护下撤退。",
		type = 1,
		model_name = "3044_tpose",
		skill_desc6 = "",
		desc = "身穿长袍，以兜帽遮面，手持权杖的鹿神祭司，口中时常低声念叨着神秘的祷文。",
		race = 6,
		skill_desc2 = "挥舞权杖对前方半圆形区域横扫喷出骸能火焰，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "跃至空中高举权杖，吟唱一段时间借取鹿神骸能，期间会为自身生成护盾，吟唱结束时用权杖重击地面，引发剧烈的骸能波动。",
		skill5 = "",
		information1 = "这些狂信徒本是鹿家旧部，被蛊惑后暗中祭祀鹿神，为夺回鹿家旧权而协助鹿神苏醒。",
		skill_desc1 = "挥舞权杖向目标发动两次攻击并击退敌人，随后朝目标方向射出大量火球对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "腐焰燎原",
		id = 3044,
		information2 = "这些鹿神祭司作为狂信徒们的主心骨，暗中筹划着各项秘密活动，以下京区为据点笼络人心，传播教义。"
	},
	[4010] = {
		skill3 = "复合斩",
		skill2 = "华丽身法",
		information3 = "精通各种武器的使用，但却表现的非常懒散，反而给人深不可测的感觉。",
		type = 2,
		model_name = "4010_tpose",
		skill_desc6 = "",
		desc = "英俊的青年领导者，大部分身体被改造成了机械，脸上总是挂着轻浮的笑容。",
		race = 6,
		skill_desc2 = "伊森蓄力后挥刀挑飞敌人，对敌人造成连续攻击。",
		skill4 = "凝神一击",
		skill_desc5 = "",
		skill_desc3 = "伊森冲刺至敌人位置，对敌人使出强力的四连攻击。",
		skill5 = "",
		information1 = "失去了所有记忆，在一堆零件的废墟中醒来，全身80%的组织被改成机械的男子。",
		skill_desc1 = "伊森快速移动到敌人身边，挥动武器发动连续斩击。",
		skill_desc4 = "伊森短暂蓄力后冲向远距离的敌人，使出强力一击。",
		skill6 = "",
		skill1 = "潇洒登场",
		id = 4010,
		information2 = "迷铁之家目前的领导人，正在四处寻找关于自己身体的线索。"
	},
	[4012] = {
		skill3 = "千钧之坠",
		skill2 = "回环迅击",
		information3 = "在它成为一件毁天灭地的兵器前，对于库什尔方的制造者，它其实更意味着一件举世无双的艺术品。",
		type = 2,
		model_name = "4012_tpose",
		skill_desc6 = "",
		desc = "体格庞大的半人马型智械兵器。",
		race = 8,
		skill_desc2 = "库什尔方冲向敌人，挥动长枪使出挑飞攻击。",
		skill4 = "涂炭之陨",
		skill_desc5 = "",
		skill_desc3 = "库什尔方高高跃起后坠击地面，对敌人造成范围伤害。",
		skill5 = "",
		information1 = "「单兵作战」这个概念上无可超越的存在。",
		skill_desc1 = "库什尔方矫健地跃向敌人，挥动长枪使出三连突刺。",
		skill_desc4 = "库什尔方将长枪插入地面，注入惊人的能量并将其引爆。",
		skill6 = "",
		skill1 = "腾空突刺",
		id = 4012,
		information2 = "结合了先进科技，穷以斯皮尔特工业所有的高级资源所生产出来的兵器。"
	},
	[4013] = {
		skill3 = "",
		skill2 = "追踪炮击",
		information3 = "全身搭载了数量恐怖的重火力武器，一旦进入战斗，会以爆炸性的火力碾压战场。",
		type = 2,
		model_name = "4013_tpose",
		skill_desc6 = "",
		desc = "浑身长满电晶石的六足爬行视骸，原型是丑陋的蜘蛛，身上装备了许多重火力的智械装甲。",
		race = 7,
		skill_desc2 = "哈法斯释放出追踪射线，确定目标位置后释放强力炮击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "出现在诺伊汉萨区源层的智种视骸，受表层工业的影响，拥有极为巨大的机械身躯。",
		skill_desc1 = "哈法斯释放精准的导弹攻击，通过火力压制使敌人毫无招架之力。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "火力压制",
		id = 4013,
		information2 = "具有完备的思维能力和语言能力，相比于单纯的破坏，行为更具有强烈的目的性。"
	},
	[4014] = {
		skill3 = "秘技·万蛇斩",
		skill2 = "秘技·天火",
		information3 = "心性傲慢且残忍，喜欢玩弄猎物于股掌之间。能够使用数把太刀，发动潮水一般的连续攻势。\n此外，还拥有使役视骸大蛇的能力。以山神之姿降临战场的远吕知，预示着灾难将再次回到这片土地。",
		type = 2,
		model_name = "4014_tpose",
		skill_desc6 = "",
		desc = "成熟妖冶的女子，数只凶猛的巨蛇蛰伏在她身后，随时准备发动攻击。",
		race = 7,
		skill_desc2 = "远吕知操作巨蛇，向敌人喷射火焰。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "远吕知向前释放出数道凌厉的剑气，对敌人造成沉重的打击。",
		skill5 = "",
		information1 = "曾经统治笹波的五大山神之一，宫蛇家族的供奉对象，于百年前被封印。",
		skill_desc1 = "远吕知闪身至敌人身前，操纵巨蛇发动猛力斩击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "秘技·潜蛇",
		id = 4014,
		information2 = "如今被宫蛇秀召唤苏醒，在宫蛇家秘密进行人类与视骸的结合试验。"
	},
	[4015] = {
		skill3 = "吞涌星潮",
		skill2 = "深海巨啸",
		information3 = "虽然能再次开口吟唱动人的歌谣了，却也再没有办法对深爱的人说出想说的话。",
		type = 2,
		model_name = "4015_tpose",
		skill_desc6 = "",
		desc = "出现在宫蛇家的人形视骸，擅长使用动听的歌喉麻痹敌人的意志，常常能看到一只鲸鱼陪伴在她身侧。",
		race = 7,
		skill_desc2 = "鲸鱼掀起海啸，对前方的敌人造成巨大的冲击。",
		skill4 = "远古音律",
		skill_desc5 = "",
		skill_desc3 = "鲸鱼向空中喷吐水弹，水弹如流星般坠落至敌人附近造成范围攻击。",
		skill5 = "",
		information1 = "本名栗本葵，在宫蛇家被抚养长大，接任祭祀歌姬一职的年轻女性。\n在四年前的火灾中失去了优美的嗓音，召唤蛇神之后甚至无法再度歌唱。",
		skill_desc1 = "歌姬指引鲸鱼高高跃向空中，在下落点周围形成强力冲击，击退周围的敌人。",
		skill_desc4 = "鲸鱼的歌声化作音波，对前方敌人造成冲击。",
		skill6 = "",
		skill1 = "跃浪回声",
		id = 4015,
		information2 = "为了留在宫蛇秀的身边，接受了视骸化的改造，失去了思维能力，只保留了些微的记忆。"
	},
	[4016] = {
		skill3 = "舞鹤遗形",
		skill2 = "岐蛇尾刃",
		information3 = "对它来说，人类是力量，是子民，是工具，是虫子，亦是它朝思暮想的神国中不可或缺的一部分。而它的野心远不止于此，成为视骸、人类、修正者的共主才是它的终极目标。",
		type = 2,
		model_name = "4016_tpose",
		skill_desc6 = "",
		desc = "体型庞大的融合怪物，在蛾首人身的基础上又吞噬了蛇神、鹤神等山神的灰烬，自此成为执掌众山神的原始力量的人神。",
		race = 7,
		skill_desc2 = "将尾部像剑一般向前方进行数次挥砍，放出月牙形的骸能冲击波来从远处攻击敌人。",
		skill4 = "覆天神罚",
		skill_desc5 = "",
		skill_desc3 = "短暂蓄力后使用鹤翼向正前方进行快速劈砍，对敌人造成伤害。",
		skill5 = "",
		information1 = "诞生于笹波的强大视骸，数百年来一直以来用人类身份作为伪装，在暗中积蓄力量。意图控制并统领人类，创造自己的神国。",
		skill_desc1 = "盘旋后展开鹤翼飞到空中，锁定敌人后向其射出骸能火焰球，命中后对敌人造成伤害。",
		skill_desc4 = "于自己的正上方召唤骸能法阵覆盖天空，随机降下数道骸能法术冲击，对视界之内的敌人降下神罚。",
		skill6 = "",
		skill1 = "萤蛾流火",
		id = 4016,
		information2 = "心思缜密，为达成目的蛰伏百年，利用融合灰烬的庞大骸能将笹波孤立出来，意图用精神控制和复活的权能实现自己的愿望。"
	},
	[4020] = {
		skill3 = "猛进之势",
		skill2 = "爆裂火花",
		information3 = "其双拳的一击，可以直接撕开通往表层的通道。凭借单纯的破坏意志行动，威胁巨大，是首要清除对象。",
		type = 2,
		model_name = "4020_tpose",
		skill_desc6 = "",
		desc = "体型巨大，其强壮有力的双臂是最大的威胁。",
		race = 7,
		skill_desc2 = "哈加提用力砸击地面，释放大量爆裂的骸能火花击飞敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "横扫战场，用巨大的双臂击飞一切障碍。",
		skill5 = "",
		information1 = "在所有已观测到的视骸中也相当罕见的巨化种视骸，代号「哈加提」，形成的原因暂时不明。",
		skill_desc1 = "哈加提瞬移至敌人身边，高举双臂给予敌人沉重一击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "超空间打击",
		id = 4020,
		information2 = "推测是由于视骸大量吞噬源层物质形成的特殊个体，体型相当巨大，拥有超过一般视骸的破坏力。"
	},
	[4021] = {
		skill3 = "量子削切",
		skill2 = "骸能脉冲",
		information3 = "可以说它的存在本身就是打破源表层平衡的巨大威胁，如果放任不管，将会造成巨大的灾害。\n除了本身巨大的力量以外，由于吸收了过量的源质，「比弗隆斯」也会释放能量形态的远程攻击，危险程度极高！",
		type = 2,
		model_name = "4021_tpose",
		skill_desc6 = "",
		desc = "体型巨大，挥舞着异化的双臂肆无忌惮地破坏周围的一切。",
		race = 7,
		skill_desc2 = "比弗隆斯撞击双臂释放两股高能脉冲，对远距离的敌人造成沉重的打击。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "比弗隆斯从双臂中释放出两把骸能刀击飞前方的敌人。",
		skill5 = "",
		information1 = "特异的巨化种视骸，代号「比弗隆斯」，为深空之眼近几年观测到的第一体特殊巨化种视骸。",
		skill_desc1 = "比弗隆斯蓄力后向前释放冲拳，异化的手臂产生的威力不容小觑。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "蓄力冲拳",
		id = 4021,
		information2 = "由巨化种「哈加提」进一步吸收源层物质后变异产生，在短时间内获得了更为庞大的能量，破坏力再次有了夸张的提升。"
	},
	[4022] = {
		skill3 = "讨逆之蛾",
		skill2 = "灾厄落岩",
		information3 = "五山神与朗香原本都是诞生于笹波源层的融合种，因为吞噬了大量灰烬而产生分裂，包含朗香在内的六个视骸互相之间都有着吞噬对方的想法，但却又无法直接对其他个体出手。朗香一直在暗中谋划着消灭其他山神的计划，为重回一体做准备。",
		type = 2,
		model_name = "4022_tpose",
		skill_desc6 = "",
		desc = "表面上领导笹波人民的「天之子」，在鸦越遥的外表下隐藏的真身，是笹波区源层孕育的高级智骸。",
		race = 7,
		skill_desc2 = "召唤数块岩石砸向地面，对自身周围的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "飞至空中，将骸能聚集为一只振翅之蛾轰击敌人，对目标造成伤害。",
		skill5 = "",
		information1 = "平日里总是一副天真孩童的模样，话语中却会时不时透露出几分令人胆寒的残忍，她内心中暗藏着的野心，恐怕只有与其合作的伊鹤正芳能够窥得一二。",
		skill_desc1 = "飞至空中，幻化出自己的两个分身，一起朝目标释放骸能冲击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "羽化三身",
		id = 4022,
		information2 = "百年之前，朗香设计杀死鹤神并夺取其灰烬后紧接着将蛇、鹿、猿、鸦四山神封印，但自己也因此遭受重创，只得利用天之子这个伪装的身份休养生息。百年后随着五山神逐渐复苏，朗香也开始实施自己的计划。"
	},
	[4023] = {
		skill3 = "弦音烨煜",
		skill2 = "摇曳之声",
		information3 = "一直将祖母视作榜样的雅典娜，将贯彻自己心中的理想，驱逐一切可能会威胁到欧莫菲斯的侵略者。然而，再强大的力量也可能会随着信念的崩塌荡然无存……",
		type = 2,
		model_name = "4023_tpose",
		skill_desc6 = "",
		desc = "铃兰骑士团的团长，凯琳·帕拉斯收养的曾孙女，家族世代都是铃兰骑士团的团员，一直以来都以成为一名优秀的铃兰团骑士而努力。为人正直，秉承着正义、忠诚的骑士道。",
		race = 6,
		skill_desc2 = "雅典娜释放一团特殊的音波，音波持续向前飘移，触碰到敌人的片刻后音波将爆炸，对圆形范围内的敌人造成伤害，并使之进入睡眠状态。",
		skill4 = "铃兰组曲",
		skill_desc5 = "",
		skill_desc3 = "雅典娜向后闪避，并释放出一道缓慢向前移动的音波，触碰到音波的敌人将受到伤害。",
		skill5 = "",
		information1 = "欧莫菲斯的制度不可以被任何人破坏，铃兰团的荣耀不容任何人玷污，背负着这样沉重的责任，雅典娜一刻也不容许自己松懈。",
		skill_desc1 = "雅典娜依次使用两把武器，发动富于变化的两段攻击，对前方弧形范围内的敌人造成伤害。",
		skill_desc4 = "雅典娜奏响琴剑，释放出多段环状音波对大范围内的敌人造成伤害。",
		skill6 = "",
		skill1 = "变奏如虹",
		id = 4023,
		information2 = "超乎寻常的责任感和荣耀感使得她与周围的人格格不入，包围在数不清的崇拜者与仰慕者之间，似乎很难寻觅到一个真正与之平等相待的朋友。"
	},
	[4025] = {
		skill3 = "终末之诫",
		skill2 = "狂宴前奏",
		information3 = "被囚禁于镜中的漫长岁月似乎并未改变拉冬顽劣的性格，重获自由的他这次要向敌人加倍讨还他失去的东西。",
		type = 2,
		model_name = "4025_tpose",
		skill_desc6 = "",
		desc = "诞生于欧莫菲斯的视骸，外表如同神话中可怖的巨龙一般。心智觉醒后对人类世界充满好奇，将自己伪装成人类的模样，潜入人类社会大闹了一场。",
		race = 7,
		skill_desc2 = "拉冬俯冲而下，向目标冲刺并释放出高密度能量波，对轨迹上的敌人造成属性伤害。",
		skill4 = "陨落灾域",
		skill_desc5 = "",
		skill_desc3 = "拉冬凝聚能量，向目标发射一道强力射线，对敌人造成属性伤害。",
		skill5 = "",
		information1 = "比起单纯的破坏文明，拉冬对复杂的人性更有兴趣。他用挑唆的谎言使友人反目，有心的蛊惑使亲人分离，肆无忌惮地玩弄人心。",
		skill_desc1 = "拉冬挥舞利爪撕裂敌人，对敌人造成属性伤害。",
		skill_desc4 = "拉冬从空中召唤出一颗陨石，向目标方向发射，对敌人造成巨大的属性伤害，并将四周的一切卷入剧烈的风暴中。",
		skill6 = "",
		skill1 = "骇炎利爪",
		id = 4025,
		information2 = "对欧莫菲斯崇尚的艺术不屑一顾，认为许多创意不过是梦中的幻境、酩酊时的臆想罢了。"
	},
	[4026] = {
		skill3 = "贯海激流",
		skill2 = "幻潮涌动",
		information3 = "就像沉湎于海妖歌声的水手在触礁之前才惊醒一样，在气泡破裂时，被笼罩其中的人们才会意识到自己即将被毁灭。",
		type = 2,
		model_name = "4026_tpose",
		skill_desc6 = "",
		desc = "出现在边界之海附近的巨化种视骸，时常被人目击到的海上「女妖」的真身，将巨大的身躯隐藏在海面之下，暗中窥伺着海洋上发生的一切。",
		race = 7,
		skill_desc2 = "塞壬召唤数枚水弹袭向前方的敌人，对敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "塞壬掀起风浪，召唤出两道射线攻击海上的敌人。",
		skill5 = "",
		information1 = "拥有操作洋流与控制风暴的能力，虽然体型巨大但可以在海水中快速穿梭行动。",
		skill_desc1 = "塞壬凝聚高浓度的骸能弹向前发射，对远距离的敌人造成巨大打击。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "沉没打击",
		id = 4026,
		information2 = "它可以通过侵蚀源层数据从而篡改表层的现实，形成虚幻的气泡世界，被气泡笼罩的空间会随着气泡的破裂一同幻灭。"
	},
	[4027] = {
		skill3 = "",
		skill2 = "贯海激流",
		information3 = "就像沉湎于海妖歌声的水手在触礁之前才惊醒一样，在气泡破裂时，被笼罩其中的人们才会意识到自己即将被毁灭。",
		type = 2,
		model_name = "4027_tpose",
		skill_desc6 = "",
		desc = "出现在边界之海附近的巨化种视骸的伪装，洁白无瑕的海上「女妖」，被它的外表蛊惑的人浑然不觉自己早已落入陷阱。",
		race = 7,
		skill_desc2 = "塞壬掀起风浪，召唤出两道射线攻击海上的敌人。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "",
		skill5 = "",
		information1 = "拥有操作洋流与控制风暴的能力，虽然体型巨大但可以在海水中快速穿梭行动。",
		skill_desc1 = "塞壬召唤数枚水弹袭向前方的敌人，对敌人造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "幻潮涌动",
		id = 4027,
		information2 = "它可以通过侵蚀源层数据从而篡改表层的现实，形成虚幻的气泡世界，被气泡笼罩的空间会随着气泡的破裂一同幻灭。"
	},
	[4028] = {
		skill3 = "完全防御",
		skill2 = "自主防御反击",
		information3 = "金固从迷铁之家获得了这台智械，凭借它成功击败了马尔杜克的平叛部队，并生擒了马尔杜克。",
		type = 2,
		model_name = "4028_tpose",
		skill_desc6 = "",
		desc = "这种军用智械采用了最先进的人工智能技术和新型动力结构，能够应对各种复杂的战场情况，并且拥有极强的机动力。",
		race = 8,
		skill_desc2 = "利用背部装甲展开能够抵挡攻击的护盾，若受到攻击，则手臂会立刻转变剑形态进行反击。",
		skill4 = "横冲碾压",
		skill_desc5 = "立刻展开配备的机炮对周身进行扫射。",
		skill_desc3 = "向前方广范围生成护盾抵挡攻击，同时发射追踪飞弹清理高威胁目标。",
		skill5 = "机炮扫射",
		information1 = "其设计标准已经远超人类武器的范畴，根本不可能用于针对人类的战争，于是斯皮尔特高层秘密保留了技术文档。",
		skill_desc1 = "利用喷射高压气体的方式高速移动至目标身边，发动威力巨大的冲击。",
		skill_desc4 = "发射激光引导，随后对引导路径上的目标发动冲撞碾压。",
		skill6 = "",
		skill1 = "推进冲击",
		id = 4028,
		information2 = "伊森等人利用之前劫掠到的智械部件，参考技术资料建造了一台巨型智械，并按照技术文档的名称将其命名为「暗金属」。"
	},
	[4029] = {
		skill3 = "交叉激光",
		skill2 = "骸能制御",
		information3 = "驱动能源转变为骸能后，暗金属的持久作战能力也获得了极大的提升，寻常攻击无法对其造成伤害。",
		type = 2,
		model_name = "4029_tpose",
		skill_desc6 = "",
		desc = "在骸震中被骸能侵蚀的暗金属，相比机械更多地展现出了视骸的特征，能够运用双臂的巨刃撕碎对手。",
		race = 7,
		skill_desc2 = "利用背部装甲展开能够抵挡攻击的骸能护盾，若受到攻击，则手臂会立刻转变剑形态进行反击。",
		skill4 = "骸能冲撞",
		skill_desc5 = "高速推进升至空中，随后向目标发射双臂与胸口的骸能武装进行火力压制。",
		skill_desc3 = "蓄力准备后，由双臂处交叉释放广域激光扫射，扫射区域将在短暂延迟后爆发出骸能攻击。",
		skill5 = "机动空袭",
		information1 = "在一场突如其来的骸震中，暗金属被骸能侵蚀，成为视骸，金固最强力的倚仗突然变成了他最恐怖的噩梦。",
		skill_desc1 = "利用压缩骸能的方式高速移动至目标身边，发动威力巨大的冲击。",
		skill_desc4 = "发射骸能引导，随后对引导路径上的目标发动强力的骸能冲撞。",
		skill6 = "",
		skill1 = "骸能冲击",
		id = 4029,
		information2 = "骸化后的暗金属会展现出与之前截然不同的战斗风格，其速度和力量都将获得提升，变得狂暴无比。"
	},
	[4030] = {
		skill3 = "腐根化剑",
		skill2 = "百兽呼引",
		information3 = "其意识与肉体被分离，秋鹿家族会以活人献祭的方式使其保持封印状态。但肉体部分会逐渐苏醒，依照本能腐化百兽发动攻击以夺回自己被分离的意识为目的行动。",
		type = 2,
		model_name = "4030_tpose",
		skill_desc6 = "",
		desc = "曾经统治笹波的五大山神之一，于百年前被天之子·朗香封印，秋鹿家族曾经的供奉对象。",
		race = 7,
		skill_desc2 = "鹿神高声嘶吼，召唤腐化兽骸为其作战。",
		skill4 = "腐树孳生",
		skill_desc5 = "",
		skill_desc3 = "鹿神从体内抽出骸能根须化成的长剑，向目标发动势不可挡的连续劈砍。",
		skill5 = "",
		information1 = "是百兽夜行的源头，隐于幕后腐化百兽并暗中控制着兽骸们的动向。",
		skill_desc1 = "鹿神将双臂插入地下注入骸能，在目标脚下生成数波骸能根须刺穿地面对敌人造成伤害。",
		skill_desc4 = "鹿神将骸能根须插入地面注入骸能，随后根须迅速生长为大树，向自身周边大范围区域释放骸能波动，对敌人造成伤害。",
		skill6 = "",
		skill1 = "裂地根须",
		id = 4030,
		information2 = "鹿神就像是一种能够无限分裂的菌丝，能侵入植物，腐化动物，在土地中蔓延。"
	},
	[4031] = {
		skill3 = "回旋俯冲",
		skill2 = "心智冲击",
		information3 = "解放能力后会显现出截然不同的「黑武神形态」，使其能够驾驭更强的力量，但因其自身缺陷和芯片损耗，武神形态下的身体也极不稳定。",
		type = 2,
		model_name = "4031_tpose",
		skill_desc6 = "",
		desc = "帕拉凯瑟主导的铸塔计划中，诞生的拥有掌控「过去」之力的人造修正者，能够在一定时间内改变特定对象的记忆。",
		race = 6,
		skill_desc2 = "短暂蓄力后，将压缩后的神力压入地面，引发巨大冲击。",
		skill4 = "极黑夜翼",
		skill_desc5 = "乌尔德升至空中开始准备，随后召唤出心智投影并释放全力向地面攻击，期间受到攻击的角色都会被蛊惑心神。",
		skill_desc3 = "乌尔德升入空中，盘旋后瞄准目标发动一次强力的俯冲斩击。",
		skill5 = "终焉谢幕",
		information1 = "通常会以少年的形象出现，依靠记忆更改的能力，基本不需要亲自战斗。",
		skill_desc1 = "将神力灌入武器中，并向前方区域进行大范围的横扫。",
		skill_desc4 = "在翅膀上凝聚神力团随后一口气释放，神力团会在靠近锁定目标后加速飞行，并在撞击目标后引发爆炸。",
		skill6 = "",
		skill1 = "死亡挥扫",
		id = 4031,
		information2 = "更改记忆的能力虽然强大，但缺点是每次使用会消耗神力，损坏芯片寿命。为了补充神力，开始大肆猎杀修正者。"
	},
	[4032] = {
		skill3 = "碎地狂尘",
		skill2 = "撼山怒击",
		information3 = "也时常踏上格斗场接受挑战，在收起骸能的情况下，通过强大的格斗技巧和身体素质，一次次夺得冠军。",
		type = 2,
		model_name = "4032_tpose",
		skill_desc6 = "",
		desc = "图灵安插在夏什瓦特的智种视骸，性格张狂易怒，伪装成人类潜伏在社会中。",
		race = 7,
		skill_desc2 = "向前移动撞击敌人，再发出一记向上的勾拳，对命中的敌人造成伤害。",
		skill4 = "",
		skill_desc5 = "",
		skill_desc3 = "跃至空中向地面猛砸三次，每次砸击发出环状的冲击波，对敌人造成伤害。",
		skill5 = "",
		information1 = "表面的身份是「猎豹帮」的老大，经营着地下格斗场。",
		skill_desc1 = "罗波那挥手向前发射出三个投射物，将被击中的敌人变为金块。随后罗波那将敌人抱起，从空中砸向地面，对敌人造成造成伤害。",
		skill_desc4 = "",
		skill6 = "",
		skill1 = "鎏金抱摔",
		id = 4032,
		information2 = "具有顶级的格斗技巧，习惯将骸能当作拳脚去战斗，视作自身肉体的延伸。"
	},
	[4034] = {
		skill3 = "鎏金狂舞",
		skill2 = "地裂爪",
		information3 = "多年前被封印进玩偶之中，但因金乌的冒失，夕被遗忘在艾因索菲的一角，于艾因索菲跨年夜之际逃脱了封印，引发骚乱。",
		type = 2,
		model_name = "4034_tpose",
		skill_desc6 = "",
		desc = "来自虚恒的神秘视骸，锋利的爪牙、头上的犄角是他的强力武器，拥有着以一抵百的野蛮力量。",
		race = 7,
		skill_desc2 = "用锋锐的爪子斩裂地面，并发动远距离的冲击波。",
		skill4 = "灾变吐息",
		skill_desc5 = "",
		skill_desc3 = "向前冲刺，将爪击命中的敌人包裹在金块内使其无法行动，随后对其发动猛烈的连击。",
		skill5 = "",
		information1 = "体型庞大结实，脾性暴躁，往往需要几人合力才能勉强牵制。",
		skill_desc1 = "用自己的犄角向敌人发动高速猛烈的多次冲撞，会破坏路径上的一切障碍。",
		skill_desc4 = "对前方进行三次吐息后，短暂蓄力，进行一次大范围吐息，对敌人造成伤害。",
		skill6 = "",
		skill1 = "硝烟冲撞",
		id = 4034,
		information2 = "长年沉睡，每逢岁时便会苏醒，现身时会暴走，对周边生物进行无差别攻击。但据说，只要听到爆竹的声音就会逃走。"
	},
	[4036] = {
		skill3 = "雾影收割",
		skill2 = "覆灭镰舞",
		information3 = "在她看来，修正者执意守护的世界本身就是残缺的，唯有将一切归于虚无，将万物重构，世界才能迎来新生。",
		type = 2,
		model_name = "4036_tpose",
		skill_desc6 = "",
		desc = "诞生于虚恒源层的智骸，潜伏在人类社会中相当一段时间，以其智慧与美貌在商界中如鱼得水。",
		race = 7,
		skill_desc2 = "向目标发动斩击的同时跳起，在空中短暂蓄力后向前砸下同时放出骸能冲击，对范围内的敌人造成伤害。",
		skill4 = "命则必殒",
		skill_desc5 = "",
		skill_desc3 = "抛出镰刀后短暂消失，随后从雾气中现身向目标发动强力斩击。",
		skill5 = "",
		information1 = "平日里以身材高挑的优雅女性面貌示人，战斗会则化为雾影中的收割者。",
		skill_desc1 = "手持镰刀向前冲刺，划出一道骸能裂隙，在到达终点时骸能裂隙引爆，对路径上的敌人造成伤害。",
		skill_desc4 = "高举镰刀，将周围的敌人牵引向自身，随后与骸能雾影一同向目标发出致命的二连斩击。",
		skill6 = "",
		skill1 = "彼岸送葬",
		id = 4036,
		information2 = "她在转化为视骸的过程中，脑海里不断重复着虚恒诞生的场景，由此对这虚拟世界的创生与毁灭抱有强烈的执念。"
	},
	[4037] = {
		skill3 = "赤红落影",
		skill2 = "弃誓之剑",
		information3 = "「我因何存在？」「视骸为何要攻击文明？」图灵渴求原质之心，究竟是为了知晓视骸的本质，还是为了探寻自我，真正的答案恐怕只有他自己知晓。",
		type = 2,
		model_name = "4037_tpose",
		skill_desc6 = "",
		desc = "无人知晓图灵是何时诞生的，也无人知晓他究竟是什么人，看起来只是一位有着褐色皮肤、白色长发的知性青年，但他却能同时操控神能与骸能。",
		race = 6,
		skill_desc2 = "图灵将左手晶体聚成长剑，向目标发起延绵不绝的连续攻击。",
		skill4 = "天陨崩落",
		skill_desc5 = "",
		skill_desc3 = "图灵跃入空中，将骸能注入晶体剑向目标地点重劈，落地时晶体爆炸向周围造成骸能冲击。",
		skill5 = "",
		information1 = "图灵统领着大量智骸，在近期由智骸引发的多起事件的背后，都有着图灵的影子。",
		skill_desc1 = "图灵在身前凝聚惊人骸能，化为追踪敌人的长枪向目标掷出。",
		skill_desc4 = "图灵高高跃起，召唤巨大骸能晶体向目标地点砸下，将大范围内的敌人卷入猛烈的骸能爆炸中。",
		skill6 = "",
		skill1 = "湮灭之枪",
		id = 4037,
		information2 = "有着足以对抗原初权能、改变物理法则的强大力量，不论要让世间付出怎样的代价，他都将继续探寻真理。"
	},
	[4038] = {
		skill3 = "百穿之誓",
		skill2 = "圣树投影",
		information3 = "数次的失败与重启改变了奥丁的想法，因过往经历已经抛弃了天真或软弱的想法，在很多事上变得狠辣果决，不带一丝犹豫的行动只因为她一直坚定着自己的道路。",
		type = 2,
		model_name = "4038_tpose",
		skill_desc6 = "",
		desc = "深空之眼的最高领导人，组织的发起者和创立者，是修正者阵营对抗视骸的核心人物。",
		race = 6,
		skill_desc2 = "奥丁连续投影伪制权钥，向目标发动如潮水般的连续攻击。",
		skill4 = "黄昏将至",
		skill_desc5 = "",
		skill_desc3 = "奥丁跃入空中，以神力向冈格尼尔起誓，蓄力后对目标所在位置掷出，其威力足以贯穿一切。",
		skill5 = "",
		information1 = "作为原初修正者，奥丁在一次次的失败和重启中寻找着消灭视骸的方法。",
		skill_desc1 = "奥丁升入空中，连续空间移动的同时向目标投出神罚之枪，最后手持冈格尼尔从高空发动强烈的突击。",
		skill_desc4 = "奥丁手持冈格尼尔向目标发动近身突击，以封锁空间之势斩断所有未来。",
		skill6 = "",
		skill1 = "流星突袭",
		id = 4038,
		information2 = "早期曾有以一己之力对抗整个源层片区视骸的事迹，被誉为是「有记载以来最强的修正者」。"
	},
	[4039] = {
		skill3 = "殒灭落雨",
		skill2 = "俱亡之光",
		information3 = "如果你能看到这里，说明你已经在追寻真相的道路上走得太远……关于惑鸦的任何情报都应当被隐藏。惑鸦并不具有真实的形体，但我们不应当去界定它，不应当去记忆它，记住，鸦神已经被消灭。",
		type = 2,
		model_name = "4039_tpose",
		skill_desc6 = "",
		desc = "据观测，惑鸦的形态类似于一只三足乌鸦，它的头上有着数对颜色不同的眼睛，除此之外，它和普通乌鸦别无二致。",
		race = 7,
		skill_desc2 = "惑鸦聚集骸能，向目标喷射毁灭性的光束，对命中的敌人造成伤害。",
		skill4 = "暗鸦影袭",
		skill_desc5 = "",
		skill_desc3 = "惑鸦挥动双翼，召唤无数如雨点般落下的骸能波，对命中的敌人造成伤害。",
		skill5 = "",
		information1 = "它能使听见其鸣叫之人产生恐慌，会使对方想起最难以忘怀的过去，难以自拔。",
		skill_desc1 = "惑鸦在目标位置唤出两股猛烈旋转前进的飓风，对命中的敌人造成伤害。",
		skill_desc4 = "惑鸦飞至半空，随后以迅猛之势向目标发动俯冲攻击，对命中的敌人造成伤害。",
		skill6 = "",
		skill1 = "狂啸飓风",
		id = 4039,
		information2 = "听到了惑鸦的鸣叫声后，请立即执行X-A01强制对策，消除当日的一切记忆，并按照手册指示离开当前所在位置。"
	},
	[4040] = {
		skill3 = "冲坠错斩",
		skill2 = "斩地掀波",
		information3 = "为了不被抛弃，她而开始越发渴望力量，利用「吸收」让自己不断变强。只为成为帕拉凯瑟期望中的样子。",
		type = 2,
		model_name = "4040_tpose",
		skill_desc6 = "",
		desc = "帕拉凯瑟「铸塔计划」的人造修正者，编号0700，作为「07」系列人造修正者的原型机，因为是多次试验后调试出的最稳定、性能最强的集体，所以不具备量产性。",
		race = 6,
		skill_desc2 = "跃向空中旋转蓄力，用触手猛地抽击地面，并对敌人造成伤害，之后猛地将触手掀起，造成大范围的冲击波，对范围内的敌人进行致命打击。",
		skill4 = "赤索旋绞",
		skill_desc5 = "变身蓄力后跃向空中，重重砸向地面，对周围敌人造成大范围震击。",
		skill_desc3 = "飞到空中蓄力后向前俯冲，落地时甩开触手发动攻击，对面前范围内的敌人造成伤害。",
		skill5 = "触域碎击",
		information1 = "作为人造修正者，从一开始就被灌输以「工具」的身份存在，所以并不将自己视为「人类」。她没有朋友，成为帕拉凯瑟的利刃是她唯一的目标 。",
		skill_desc1 = "左右触手合二为一，后仰蓄力并向前方伸长猛刺，对敌人造成伤害，之后立刻收回右边触手作为支撑，用左边触手逆时针横扫一圈，来攻击身边的敌人。",
		skill_desc4 = "于原地蓄力，后倒立连续旋转，持续用触手攻击四周，以击破敌人防御，随后跃向空中用触手抓住敌人，将敌人摔到身后重重砸地造成伤害。",
		skill6 = "",
		skill1 = "嵌刺合旋",
		id = 4040,
		information2 = "虽然相对其他个体，0700拥有更优秀的神能适应性。但经过试验表明，0700只是一个比普通修正者更强的「神能容器」，这使得帕拉凯瑟对她非常失望。"
	},
	get_id_list_by_race = {
		[6] = {
			2020,
			2030,
			2049,
			2050,
			2073,
			2074,
			2078,
			2079,
			2089,
			2095,
			2104,
			2105,
			2113,
			3008,
			3009,
			3010,
			3028,
			3029,
			3032,
			3035,
			3046,
			3044,
			4010,
			4023,
			4031,
			4037,
			4038,
			4040
		},
		[8] = {
			2018,
			2019,
			2021,
			2022,
			2025,
			2040,
			2041,
			2043,
			2044,
			2045,
			2069,
			2070,
			2088,
			2114,
			3005,
			3006,
			3020,
			3031,
			3033,
			3036,
			4012,
			4028
		},
		[7] = {
			2017,
			2026,
			2027,
			2029,
			2032,
			2033,
			2036,
			2037,
			2038,
			2055,
			2056,
			2057,
			2058,
			2059,
			2060,
			2061,
			2062,
			2063,
			2064,
			2065,
			2066,
			2067,
			2068,
			2076,
			2077,
			2080,
			2081,
			2082,
			2086,
			2087,
			2094,
			2096,
			2118,
			3004,
			3007,
			3012,
			3013,
			3014,
			3016,
			3017,
			3019,
			3021,
			3022,
			3023,
			3024,
			3025,
			3039,
			3040,
			3041,
			3042,
			4013,
			4014,
			4015,
			4016,
			4020,
			4021,
			4022,
			4025,
			4026,
			4027,
			4029,
			4030,
			4032,
			4034,
			4036,
			4039
		}
	},
	all = {
		2017,
		2018,
		2019,
		2020,
		2021,
		2022,
		2025,
		2026,
		2027,
		2029,
		2030,
		2032,
		2033,
		2036,
		2037,
		2038,
		2040,
		2041,
		2043,
		2044,
		2045,
		2049,
		2050,
		2055,
		2056,
		2057,
		2058,
		2059,
		2060,
		2061,
		2062,
		2063,
		2064,
		2065,
		2066,
		2067,
		2068,
		2069,
		2070,
		2073,
		2074,
		2076,
		2077,
		2078,
		2079,
		2080,
		2081,
		2082,
		2086,
		2087,
		2088,
		2089,
		2094,
		2095,
		2096,
		2104,
		2105,
		2113,
		2114,
		2118,
		3004,
		3005,
		3006,
		3007,
		3008,
		3009,
		3010,
		3012,
		3013,
		3014,
		3016,
		3017,
		3019,
		3020,
		3021,
		3022,
		3023,
		3024,
		3025,
		3028,
		3029,
		3031,
		3032,
		3033,
		3035,
		3036,
		3039,
		3040,
		3041,
		3042,
		3046,
		3044,
		4010,
		4012,
		4013,
		4014,
		4015,
		4016,
		4020,
		4021,
		4022,
		4023,
		4025,
		4026,
		4027,
		4028,
		4029,
		4030,
		4031,
		4032,
		4034,
		4036,
		4037,
		4038,
		4039,
		4040
	}
}
