return {
	{
		distortion_effect = 0,
		name = "极简",
		resolution = 2,
		monster_effect = 2,
		frame = 0,
		teammate_effect = 1,
		hdr = 0,
		reflection_effect = 0,
		user_effect = 2,
		physical_simulation = 0,
		id = 1,
		high_quality = 0,
		anti_aliasing = 0
	},
	{
		distortion_effect = 0,
		name = "流畅",
		resolution = 2,
		monster_effect = 2,
		frame = 0,
		teammate_effect = 1,
		hdr = 1,
		reflection_effect = 0,
		user_effect = 2,
		physical_simulation = 0,
		id = 2,
		high_quality = 0,
		anti_aliasing = 0
	},
	{
		distortion_effect = 0,
		name = "清晰",
		resolution = 2,
		monster_effect = 2,
		frame = 0,
		teammate_effect = 1,
		hdr = 1,
		reflection_effect = 0,
		user_effect = 2,
		physical_simulation = 1,
		id = 3,
		high_quality = 0,
		anti_aliasing = 0
	},
	{
		distortion_effect = 1,
		name = "高清",
		resolution = 2,
		monster_effect = 2,
		frame = 0,
		teammate_effect = 1,
		hdr = 1,
		reflection_effect = 1,
		user_effect = 2,
		physical_simulation = 1,
		id = 4,
		high_quality = 1,
		anti_aliasing = 1
	},
	{
		distortion_effect = 1,
		name = "超清",
		resolution = 3,
		monster_effect = 3,
		frame = 1,
		teammate_effect = 2,
		hdr = 1,
		reflection_effect = 1,
		user_effect = 3,
		physical_simulation = 1,
		id = 5,
		high_quality = 1,
		anti_aliasing = 1
	},
	{
		distortion_effect = 0,
		name = "省电",
		resolution = 1,
		monster_effect = 1,
		frame = 0,
		teammate_effect = 1,
		hdr = 0,
		reflection_effect = 0,
		user_effect = 1,
		physical_simulation = 0,
		id = 6,
		high_quality = 0,
		anti_aliasing = 0
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6
	}
}
