return {
	[2] = {
		operation_stop_id = 811,
		open_condition = 0,
		shop_background = "",
		group_name = "每日采购",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "每日采购",
		params = "",
		refresh_num_limit = 20,
		system = "1",
		display_index = 2,
		initiative_refresh = 1,
		id = 2,
		display_group = 1,
		cost_id = {
			"CURRENCY_TYPE_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		},
		shop_label = {
			4,
			3,
			1
		}
	},
	[3] = {
		operation_stop_id = 805,
		open_condition = 0,
		shop_background = "",
		group_name = "组合补给",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "限时补给",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 1,
		initiative_refresh = 0,
		id = 3,
		display_group = 1,
		shop_label = "",
		cost_id = {}
	},
	[4] = {
		operation_stop_id = 806,
		open_condition = 0,
		shop_background = "",
		group_name = "组合补给",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "日常补给",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 2,
		initiative_refresh = 0,
		id = 4,
		display_group = 1,
		shop_label = "",
		cost_id = {}
	},
	[5] = {
		operation_stop_id = 804,
		open_condition = 0,
		shop_background = "",
		group_name = "组合补给",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "新手补给",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 3,
		initiative_refresh = 0,
		id = 5,
		display_group = 1,
		shop_label = "",
		cost_id = {}
	},
	[6] = {
		operation_stop_id = 808,
		open_condition = 0,
		shop_background = "",
		group_name = "组合补给",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "凭证兑换",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 4,
		initiative_refresh = 0,
		id = 6,
		display_group = 1,
		shop_label = "",
		cost_id = {}
	},
	[10] = {
		operation_stop_id = 820,
		open_condition = 0,
		shop_background = "",
		group_name = "交易中心",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "辉芒商店",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 10,
		display_group = 2,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DRAW"
		}
	},
	[11] = {
		operation_stop_id = 832,
		open_condition = 0,
		shop_background = "",
		group_name = "交易中心",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "合作商店",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 2,
		initiative_refresh = 0,
		id = 11,
		display_group = 2,
		cost_id = {
			53014,
			53015
		},
		shop_label = {
			1,
			2
		}
	},
	[12] = {
		operation_stop_id = 816,
		open_condition = 0,
		shop_background = "",
		group_name = "交易中心",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "情报兑换",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 3,
		initiative_refresh = 0,
		id = 12,
		display_group = 2,
		shop_label = "",
		cost_id = {
			40901,
			40902
		}
	},
	[13] = {
		operation_stop_id = 821,
		open_condition = 0,
		shop_background = "",
		group_name = "交易中心",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "矩阵供应",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 4,
		initiative_refresh = 0,
		id = 13,
		display_group = 2,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_CLUB_COIN_B"
		}
	},
	[14] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "交易中心",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "同调轨迹",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 5,
		initiative_refresh = 0,
		id = 14,
		display_group = 2,
		shop_label = "",
		cost_id = {
			41601
		}
	},
	[15] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "角色换装",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "换装商店",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 1,
		initiative_refresh = 0,
		id = 15,
		display_group = 2,
		shop_label = "",
		cost_id = {}
	},
	[16] = {
		operation_stop_id = 807,
		open_condition = 0,
		shop_background = "",
		group_name = "角色换装",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "直购商店",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 2,
		initiative_refresh = 0,
		id = 16,
		display_group = 2,
		shop_label = "",
		cost_id = {}
	},
	[17] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "角色换装",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "再贩商店",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 3,
		initiative_refresh = 0,
		id = 17,
		display_group = 2,
		shop_label = "",
		cost_id = {}
	},
	[18] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "角色换装",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "换装券获取",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 4,
		initiative_refresh = 0,
		id = 18,
		display_group = 2,
		shop_label = "",
		cost_id = {}
	},
	[20] = {
		operation_stop_id = 817,
		open_condition = 0,
		shop_background = "",
		group_name = "凭证置换",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "黑区净化",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 20,
		display_group = 3,
		cost_id = {
			"CURRENCY_TYPE_MYTHIC",
			"CURRENCY_TYPE_FINAL_MYTHIC"
		},
		params = {
			{
				SUIT_ALL_LABEL = "ALL_GOODS",
				POS_ALL_LABEL = "ALL_GOODS"
			}
		},
		shop_label = {
			1,
			3
		}
	},
	[22] = {
		operation_stop_id = 818,
		open_condition = 0,
		shop_background = "",
		group_name = "凭证置换",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "多维变量",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 2,
		initiative_refresh = 0,
		id = 22,
		display_group = 3,
		cost_id = {
			"CURRENCY_TYPE_MATRIX_CERTIFICATION"
		},
		shop_label = {
			1,
			2
		}
	},
	[23] = {
		operation_stop_id = 819,
		open_condition = 0,
		shop_background = "",
		group_name = "凭证置换",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "梦境再构",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 3,
		initiative_refresh = 0,
		id = 23,
		display_group = 3,
		cost_id = {
			"CURRENCY_TYPE_BOSS_CHALLENGE",
			"CURRENCY_TYPE_BOSS_CHALLENGE_S",
			"CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE"
		},
		shop_label = {
			1,
			4
		}
	},
	[24] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "移转观测",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "恒定观测",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 1,
		initiative_refresh = 0,
		id = 24,
		display_group = 3,
		shop_label = "",
		cost_id = {}
	},
	[25] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "移转观测",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "移转观测",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 2,
		initiative_refresh = 0,
		id = 25,
		display_group = 3,
		shop_label = "",
		cost_id = {}
	},
	[32] = {
		operation_stop_id = 814,
		open_condition = 0,
		shop_background = "",
		group_name = "刻印研发",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "刻印研发",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 3,
		initiative_refresh = 0,
		id = 32,
		display_group = 4,
		cost_id = {
			41002
		},
		shop_label = {
			1,
			3
		}
	},
	[34] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "首充福利",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "首充6元",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 1,
		initiative_refresh = 0,
		id = 34,
		display_group = 4,
		shop_label = "",
		cost_id = {}
	},
	[35] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "首充福利",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "首充18元",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 2,
		initiative_refresh = 0,
		id = 35,
		display_group = 4,
		shop_label = "",
		cost_id = {}
	},
	[36] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "首充福利",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "观测赠礼",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 3,
		initiative_refresh = 0,
		id = 36,
		display_group = 4,
		shop_label = "",
		cost_id = {}
	},
	[37] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "首充福利",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "合约福利",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 4,
		initiative_refresh = 0,
		id = 37,
		display_group = 4,
		shop_label = "",
		cost_id = {}
	},
	[41] = {
		operation_stop_id = 850,
		open_condition = 0,
		shop_background = "",
		group_name = "凭证置换",
		chain_last_visible = 0,
		show_in_shop = 1,
		activity_id = 0,
		remark = "迭代校验",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 4,
		initiative_refresh = 0,
		id = 41,
		display_group = 3,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_CORE_COIN"
		}
	},
	[50] = {
		operation_stop_id = 833,
		open_condition = 0,
		shop_background = "TextureConfig/Shop_activity/Sa_0002",
		group_name = "餐厅商店",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "餐厅商店",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 50,
		display_group = 6,
		shop_label = "",
		cost_id = {
			39
		}
	},
	[51] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "游园商店",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "游园商店",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 51,
		display_group = 7,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[58] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "主题家具",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "周年旅途",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 58,
		display_group = 8,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[57] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "主题家具",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "春意满堂",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 57,
		display_group = 8,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[56] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "主题家具",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "校园时光",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 2,
		initiative_refresh = 0,
		id = 56,
		display_group = 8,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[55] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "主题家具",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "碧海长夏",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 3,
		initiative_refresh = 0,
		id = 55,
		display_group = 8,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[54] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "主题家具",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "奇异恩典",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 4,
		initiative_refresh = 0,
		id = 54,
		display_group = 8,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[53] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "主题家具",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "雾隐洞天",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 5,
		initiative_refresh = 0,
		id = 53,
		display_group = 8,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[52] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "主题家具",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "心居套装",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 6,
		initiative_refresh = 0,
		id = 52,
		display_group = 8,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[90] = {
		operation_stop_id = 822,
		open_condition = 0,
		shop_background = "",
		group_name = "物资兑换所",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "物资兑换所",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 4,
		initiative_refresh = 0,
		id = 90,
		display_group = 9,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_HELLA_SHOP_COIN"
		}
	},
	[91] = {
		operation_stop_id = 824,
		open_condition = 0,
		shop_background = "",
		group_name = "异能置换机",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 70721,
		remark = "异能置换机",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 91,
		display_group = 10,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_SUMMER_PT"
		}
	},
	[92] = {
		operation_stop_id = 825,
		open_condition = 0,
		shop_background = "",
		group_name = "藏品鉴定所",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 81461,
		remark = "藏品鉴定所",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 92,
		display_group = 11,
		shop_label = "",
		cost_id = {
			53003
		}
	},
	[93] = {
		operation_stop_id = 827,
		open_condition = 0,
		shop_background = "",
		group_name = "强音收束仪",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 91462,
		remark = "强音收束仪",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 93,
		display_group = 12,
		shop_label = "",
		cost_id = {
			53006
		}
	},
	[94] = {
		operation_stop_id = 828,
		open_condition = 0,
		shop_background = "",
		group_name = "样品解析站",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 91461,
		remark = "样品解析站",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 2,
		initiative_refresh = 0,
		id = 94,
		display_group = 13,
		shop_label = "",
		cost_id = {
			53007
		}
	},
	[95] = {
		operation_stop_id = 829,
		open_condition = 0,
		shop_background = "",
		group_name = "情报终端",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 101461,
		remark = "情报终端",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 95,
		display_group = 14,
		shop_label = "",
		cost_id = {
			53011
		}
	},
	[96] = {
		operation_stop_id = 830,
		open_condition = 0,
		shop_background = "",
		group_name = "琳琅商行",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 111461,
		remark = "琳琅商行",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 96,
		display_group = 15,
		shop_label = "",
		cost_id = {
			53012
		}
	},
	[97] = {
		operation_stop_id = 845,
		open_condition = 0,
		shop_background = "",
		group_name = "琳琅商行",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 222721,
		remark = "琳琅商行",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 97,
		display_group = 15,
		shop_label = "",
		cost_id = {
			53087
		}
	},
	[98] = {
		operation_stop_id = 831,
		open_condition = 0,
		shop_background = "",
		group_name = "战略储藏室",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 121461,
		remark = "战略储藏室",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 98,
		display_group = 16,
		shop_label = "",
		cost_id = {
			53013
		}
	},
	[99] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "数据置换机",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "数据置换机",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 99,
		display_group = 17,
		shop_label = "",
		cost_id = {
			54,
			55,
			56
		}
	},
	[100] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "攻坚配给线",
		chain_last_visible = 1,
		show_in_shop = 0,
		activity_id = 192291,
		remark = "支援补给",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 100,
		display_group = 18,
		shop_label = "",
		cost_id = {
			54033
		}
	},
	[101] = {
		operation_stop_id = 0,
		open_condition = 100101,
		shop_background = "",
		group_name = "攻坚配给线",
		chain_last_visible = 1,
		show_in_shop = 0,
		activity_id = 192291,
		remark = "物资枢纽",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 2,
		initiative_refresh = 0,
		id = 101,
		display_group = 18,
		shop_label = "",
		cost_id = {
			54033
		}
	},
	[102] = {
		operation_stop_id = 0,
		open_condition = 100102,
		shop_background = "",
		group_name = "攻坚配给线",
		chain_last_visible = 1,
		show_in_shop = 0,
		activity_id = 192291,
		remark = "核心配给",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 3,
		initiative_refresh = 0,
		id = 102,
		display_group = 18,
		shop_label = "",
		cost_id = {
			54033
		}
	},
	[103] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "攻坚配给线",
		chain_last_visible = 1,
		show_in_shop = 0,
		activity_id = 212291,
		remark = "支援补给",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 103,
		display_group = 18,
		shop_label = "",
		cost_id = {
			54051
		}
	},
	[104] = {
		operation_stop_id = 0,
		open_condition = 100103,
		shop_background = "",
		group_name = "攻坚配给线",
		chain_last_visible = 1,
		show_in_shop = 0,
		activity_id = 212291,
		remark = "物资枢纽",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 2,
		initiative_refresh = 0,
		id = 104,
		display_group = 18,
		shop_label = "",
		cost_id = {
			54051
		}
	},
	[105] = {
		operation_stop_id = 0,
		open_condition = 100104,
		shop_background = "",
		group_name = "攻坚配给线",
		chain_last_visible = 1,
		show_in_shop = 0,
		activity_id = 212291,
		remark = "核心配给",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 3,
		initiative_refresh = 0,
		id = 105,
		display_group = 18,
		shop_label = "",
		cost_id = {
			54051
		}
	},
	[200] = {
		operation_stop_id = 823,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 0,
		remark = "数据置换",
		params = "",
		refresh_num_limit = 0,
		system = "2",
		display_index = 1,
		initiative_refresh = 0,
		id = 200,
		display_group = 19,
		shop_label = "",
		cost_id = {
			"CURRENCY_TYPE_RECHARGE_DIAMOND_FREE"
		}
	},
	[201] = {
		operation_stop_id = 834,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 131461,
		remark = "塔列朗贸易所",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 201,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53016
		}
	},
	[202] = {
		operation_stop_id = 835,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 141951,
		remark = "天禄商号",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 202,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53017,
			54014,
			1
		}
	},
	[203] = {
		operation_stop_id = 836,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 151461,
		remark = "猫咪黑市",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 203,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53021
		}
	},
	[204] = {
		operation_stop_id = 838,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 171951,
		remark = "案卷归档处",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 204,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53023,
			54017,
			1
		}
	},
	[205] = {
		operation_stop_id = 837,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 142063,
		remark = "玲珑瑰藏",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 205,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53022
		}
	},
	[206] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 181461,
		remark = "碧海游商",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 206,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53027
		}
	},
	[207] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 181951,
		remark = "天禄商行",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 207,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53028,
			54024,
			1
		}
	},
	[208] = {
		operation_stop_id = 839,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 191951,
		remark = "下京杂货",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 208,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53032,
			54030,
			1
		}
	},
	[209] = {
		operation_stop_id = 840,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 191952,
		remark = "下京集市",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 209,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53033,
			54031,
			1
		}
	},
	[210] = {
		operation_stop_id = 841,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 201461,
		remark = "情报交流处",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 210,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53079
		}
	},
	[211] = {
		operation_stop_id = 842,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 201462,
		remark = "赛会后勤",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 211,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53080,
			54039,
			1
		}
	},
	[212] = {
		operation_stop_id = 843,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 211461,
		remark = "赛场服务台",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 212,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53085,
			54047,
			1
		}
	},
	[213] = {
		operation_stop_id = 844,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 211462,
		remark = "废品回收站",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 213,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53086,
			54048,
			1
		}
	},
	[214] = {
		operation_stop_id = 846,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 231461,
		remark = "息间烹茶",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 214,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53092,
			54052,
			1
		}
	},
	[215] = {
		operation_stop_id = 847,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 231462,
		remark = "互助结社",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 215,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53098,
			54056,
			1
		}
	},
	[216] = {
		operation_stop_id = 848,
		open_condition = 0,
		shop_background = "TextureBg/SPHeroChallenge/heroChallenge_bg_shop01",
		group_name = "潜质觉醒",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 242841,
		remark = "旧时墨兰德",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 216,
		display_group = 21,
		shop_label = "",
		cost_id = {
			53100,
			53101
		}
	},
	[217] = {
		operation_stop_id = 849,
		open_condition = 0,
		shop_background = "TextureConfig/Shop_activity/Sa_0001",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 241461,
		remark = "后勤补给点",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 217,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53103,
			54060,
			1
		}
	},
	[218] = {
		operation_stop_id = 850,
		open_condition = 0,
		shop_background = "",
		group_name = "置换中心",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 241462,
		remark = "后勤补给点",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 218,
		display_group = 19,
		shop_label = "",
		cost_id = {
			53104,
			54061,
			1
		}
	},
	[220] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "福利商店",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 261463,
		remark = "福利商店",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 220,
		display_group = 22,
		shop_label = "",
		cost_id = {}
	},
	[300] = {
		operation_stop_id = 0,
		open_condition = 0,
		shop_background = "",
		group_name = "夜宴之邀",
		chain_last_visible = 0,
		show_in_shop = 0,
		activity_id = 181462,
		remark = "游艇服务中心",
		params = "",
		refresh_num_limit = 0,
		system = "1",
		display_index = 1,
		initiative_refresh = 0,
		id = 300,
		display_group = 20,
		shop_label = "",
		cost_id = {
			53029,
			53030,
			53031,
			1,
			32
		}
	},
	get_id_list_by_system = {
		{
			2,
			10,
			11,
			12,
			13,
			14,
			20,
			22,
			23,
			32,
			41,
			50,
			51,
			58,
			57,
			56,
			55,
			54,
			53,
			52,
			90,
			91,
			92,
			93,
			94,
			95,
			96,
			97,
			98,
			99,
			100,
			101,
			102,
			103,
			104,
			105,
			201,
			202,
			203,
			204,
			205,
			206,
			207,
			208,
			209,
			210,
			211,
			212,
			213,
			214,
			215,
			216,
			217,
			218,
			220,
			300
		},
		[2] = {
			3,
			4,
			5,
			6,
			15,
			16,
			17,
			18,
			24,
			25,
			34,
			35,
			36,
			37,
			200
		}
	},
	all = {
		2,
		3,
		4,
		5,
		6,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		20,
		22,
		23,
		24,
		25,
		32,
		34,
		35,
		36,
		37,
		41,
		50,
		51,
		58,
		57,
		56,
		55,
		54,
		53,
		52,
		90,
		91,
		92,
		93,
		94,
		95,
		96,
		97,
		98,
		99,
		100,
		101,
		102,
		103,
		104,
		105,
		200,
		201,
		202,
		203,
		204,
		205,
		206,
		207,
		208,
		209,
		210,
		211,
		212,
		213,
		214,
		215,
		216,
		217,
		218,
		220,
		300
	}
}
