DormFurnitureManager = import(".DormFurnitureManager")
DormCharacterManager = import(".DormCharacterManager")
DormCharacterActionManager = import(".DormCharacterActionManager")
BackHomeDataManager = import(".BackHomeDataManager")
DormMultiFurnitureStructureManager = import(".DormMultiFurnitureStructureManager")
