return {
	RECENT_MATE = 20,
	MAX_BUBBLE_WIDTH = 445,
	RECOMMEND_COUNT = 5,
	RECOMMEND_REFRESH_TIME = 10,
	FRIEND_TYPE = {
		APPLYED = 4,
		APPLY = 3,
		FRIEND = 5,
		BKACK_LIST = 6,
		SEACHER = 1,
		RECOMMEND = 2
	},
	ON_COLOR = Color(0, 0.584, 1, 1),
	OFF_COLOR = Color(0.918, 0.918, 0.918, 1),
	ADD_FRIEND_SOURCE = {
		COOPERATION_ROOM = 1,
		COOPERATION_RESULT = 2,
		MOON_CAKE_DELEGATE = 5,
		IDOL_DANCE_GAME = 7,
		DORM = 4,
		PLAYER_INFO = 3,
		FIREND_VIEW = 0,
		ACTIVITY_COMMON = 6
	}
}
