return {
	INQUERY = 8,
	CD_KEY = 1,
	ACTIVITY = 13,
	OFFICIAL_WEBSITE = 4,
	QUESTIONNAIRE = 2,
	MANUAL_WORD_VERIFY = 16,
	SHOP_TAOBAO = 14,
	SUGGEST = 6,
	CHANGE_NICK = 9,
	ATTENTION = 3,
	USER_CENTER = 5,
	SHARE_FLAG = 11,
	FORUM = 7,
	CHANGE_SIGN = 10,
	INFOMATION = 15,
	PLATFORM = {
		BILIBILI = 3,
		WEIBO = 1,
		WECHAT = 2,
		FACEBOOK = 5,
		DISCORD = 6,
		YOUTUBE = 7,
		TWITTER = 4
	},
	SURVEY_TYPE = {
		NORMAL = 1,
		REGRESSION = 2
	},
	OPERATION_STOP = {
		DAMAGE_TEST = 902,
		JOIN_CLUB = 201,
		CHANGE_CLUB_SIGN = 203,
		CHANGE_CLUB_NICK = 202
	}
}
