return {
	NOT_NEED_CACHE_CONT_ID = -1,
	DEFAULT_TEAM_INDEX = 0,
	NEED_DEFAULT_TEAM = 1,
	CAN_SWITCH_RESTRICT_HERO = 1,
	DEFAULT_COMBO_SKILL_ID = 0,
	MAX_HERO_POS_COUNT = 3,
	DETAULT_CONT_ID = 0,
	RESERVE_TYPE = {
		GUILD_BOSS = 20,
		DEFAULT = 0,
		ATTRIBUTE_ARENA = 305,
		ABYSS = 104,
		MULTI_CHESS = 105,
		SURVIVE_SOLO = 203,
		GUILD_ACTIVITY = 206,
		SEQUENTIAL_BATTLE = 302,
		BOSS_CHALLENGE = 102,
		PROPOSAL = 9999,
		CORE_VERIFICATION = 67,
		SOLO_CHALLENGE = 210,
		NOT_NEED_RESERVE = -1,
		CHESS = 101,
		PLOT = 1,
		MYTHIC_FINAL = 103
	},
	MYTHIC_CONT_ID = {
		FINAL = 3,
		NORMAL = 1,
		FINAL_MULTI = 2
	},
	RESTRICT_HERO_SWITCH_MODE = {
		OWN_AND_TRIAL = 1,
		FORBID = 0,
		TRIAL = 2
	}
}
