manager.net:Bind(10600, function (slot0)
	SystemData:InitData(slot0)
	SystemRedPoint:InitSystemUnlockDispatch()
	DrawData:RefreshNewDraw()
end)
manager.net:Bind(10602, function (slot0)
	SystemData:ModifyData(slot0)
	DrawData:RefreshNewDraw()
end)
