slot0 = require("protobuf")

module("chapter_hrl_pb", package.seeall)

slot1 = {
	CHAPTER_INFO_FIELD_LIST = {}
}
CHAPTER_INFO = slot0.Descriptor()
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD = slot0.FieldDescriptor()
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD = slot0.FieldDescriptor()
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD = slot0.FieldDescriptor()
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.name = "id"
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.full_name = ".common.chapter_info.id"
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.number = 1
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.index = 0
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.label = 2
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.has_default_value = false
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.default_value = 0
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.type = 13
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD.cpp_type = 3
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.name = "star_list"
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.full_name = ".common.chapter_info.star_list"
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.number = 2
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.index = 1
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.label = 1
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.has_default_value = false
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.default_value = 0
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.type = 13
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD.cpp_type = 3
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.name = "clear_times"
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.full_name = ".common.chapter_info.clear_times"
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.number = 3
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.index = 2
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.label = 2
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.has_default_value = false
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.default_value = 0
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.type = 13
slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD.cpp_type = 3
CHAPTER_INFO.name = "chapter_info"
CHAPTER_INFO.full_name = ".common.chapter_info"
CHAPTER_INFO.nested_types = {}
CHAPTER_INFO.enum_types = {}
CHAPTER_INFO.fields = {
	slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_ID_FIELD,
	slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_STAR_LIST_FIELD,
	slot1.CHAPTER_INFO_FIELD_LIST.CHAPTER_INFO_CLEAR_TIMES_FIELD
}
CHAPTER_INFO.is_extendable = false
CHAPTER_INFO.extensions = {}
chapter_info = slot0.Message(CHAPTER_INFO)

return chapter_hrl_pb
