slot0 = require("protobuf")

module("item_hrl_pb", package.seeall)

slot1 = {
	ITEM_NET_REC_FIELD_LIST = {},
	CONVER_ITEM_REC_FIELD_LIST = {},
	MATERIAL_NET_REC_FIELD_LIST = {},
	OVERDUE_NOTIFICATION_FIELD_LIST = {}
}
ITEM_NET_REC = slot0.Descriptor()
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD = slot0.FieldDescriptor()
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD = slot0.FieldDescriptor()
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD = slot0.FieldDescriptor()
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD = slot0.FieldDescriptor()
CONVER_ITEM_REC = slot0.Descriptor()
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD = slot0.FieldDescriptor()
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD = slot0.FieldDescriptor()
MATERIAL_NET_REC = slot0.Descriptor()
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD = slot0.FieldDescriptor()
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD = slot0.FieldDescriptor()
OVERDUE_NOTIFICATION = slot0.Descriptor()
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD = slot0.FieldDescriptor()
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD = slot0.FieldDescriptor()
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD = slot0.FieldDescriptor()
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.name = "id"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.full_name = ".common.item_net_rec.id"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.number = 1
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.index = 0
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.label = 2
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.has_default_value = false
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.default_value = 0
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.type = 13
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD.cpp_type = 3
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.name = "num"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.full_name = ".common.item_net_rec.num"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.number = 2
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.index = 1
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.label = 2
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.has_default_value = false
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.default_value = 0
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.type = 5
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD.cpp_type = 1
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.name = "time_valid"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.full_name = ".common.item_net_rec.time_valid"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.number = 3
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.index = 2
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.label = 1
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.has_default_value = false
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.default_value = 0
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.type = 13
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD.cpp_type = 3
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.name = "convert_from"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.full_name = ".common.item_net_rec.convert_from"
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.number = 4
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.index = 3
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.label = 1
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.has_default_value = false
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.default_value = nil
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.message_type = CONVER_ITEM_REC
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.type = 11
slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD.cpp_type = 10
ITEM_NET_REC.name = "item_net_rec"
ITEM_NET_REC.full_name = ".common.item_net_rec"
ITEM_NET_REC.nested_types = {}
ITEM_NET_REC.enum_types = {}
ITEM_NET_REC.fields = {
	slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_ID_FIELD,
	slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_NUM_FIELD,
	slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_TIME_VALID_FIELD,
	slot1.ITEM_NET_REC_FIELD_LIST.ITEM_NET_REC_CONVERT_FROM_FIELD
}
ITEM_NET_REC.is_extendable = false
ITEM_NET_REC.extensions = {}
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.name = "id"
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.full_name = ".common.conver_item_rec.id"
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.number = 1
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.index = 0
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.label = 2
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.has_default_value = false
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.default_value = 0
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.type = 13
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD.cpp_type = 3
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.name = "num"
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.full_name = ".common.conver_item_rec.num"
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.number = 2
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.index = 1
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.label = 2
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.has_default_value = false
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.default_value = 0
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.type = 5
slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD.cpp_type = 1
CONVER_ITEM_REC.name = "conver_item_rec"
CONVER_ITEM_REC.full_name = ".common.conver_item_rec"
CONVER_ITEM_REC.nested_types = {}
CONVER_ITEM_REC.enum_types = {}
CONVER_ITEM_REC.fields = {
	slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_ID_FIELD,
	slot1.CONVER_ITEM_REC_FIELD_LIST.CONVER_ITEM_REC_NUM_FIELD
}
CONVER_ITEM_REC.is_extendable = false
CONVER_ITEM_REC.extensions = {}
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.name = "id"
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.full_name = ".common.material_net_rec.id"
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.number = 1
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.index = 0
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.label = 2
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.has_default_value = false
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.default_value = 0
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.type = 13
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD.cpp_type = 3
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.name = "num"
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.full_name = ".common.material_net_rec.num"
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.number = 2
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.index = 1
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.label = 2
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.has_default_value = false
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.default_value = 0
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.type = 13
slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD.cpp_type = 3
MATERIAL_NET_REC.name = "material_net_rec"
MATERIAL_NET_REC.full_name = ".common.material_net_rec"
MATERIAL_NET_REC.nested_types = {}
MATERIAL_NET_REC.enum_types = {}
MATERIAL_NET_REC.fields = {
	slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_ID_FIELD,
	slot1.MATERIAL_NET_REC_FIELD_LIST.MATERIAL_NET_REC_NUM_FIELD
}
MATERIAL_NET_REC.is_extendable = false
MATERIAL_NET_REC.extensions = {}
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.name = "id"
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.full_name = ".common.overdue_notification.id"
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.number = 1
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.index = 0
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.label = 2
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.has_default_value = false
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.default_value = 0
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.type = 13
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD.cpp_type = 3
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.name = "num"
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.full_name = ".common.overdue_notification.num"
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.number = 2
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.index = 1
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.label = 2
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.has_default_value = false
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.default_value = 0
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.type = 13
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD.cpp_type = 3
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.name = "time_valid"
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.full_name = ".common.overdue_notification.time_valid"
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.number = 3
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.index = 2
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.label = 2
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.has_default_value = false
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.default_value = 0
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.type = 13
slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD.cpp_type = 3
OVERDUE_NOTIFICATION.name = "overdue_notification"
OVERDUE_NOTIFICATION.full_name = ".common.overdue_notification"
OVERDUE_NOTIFICATION.nested_types = {}
OVERDUE_NOTIFICATION.enum_types = {}
OVERDUE_NOTIFICATION.fields = {
	slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_ID_FIELD,
	slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_NUM_FIELD,
	slot1.OVERDUE_NOTIFICATION_FIELD_LIST.OVERDUE_NOTIFICATION_TIME_VALID_FIELD
}
OVERDUE_NOTIFICATION.is_extendable = false
OVERDUE_NOTIFICATION.extensions = {}
conver_item_rec = slot0.Message(CONVER_ITEM_REC)
item_net_rec = slot0.Message(ITEM_NET_REC)
material_net_rec = slot0.Message(MATERIAL_NET_REC)
overdue_notification = slot0.Message(OVERDUE_NOTIFICATION)

return item_hrl_pb
